### ISSUE TITLE
Hearth Memory Issue

### ISSUE THREAD

**Issue by ConnallM** [Momo-Studios/Cold-Sweat-Rework-Forge#10]
placed around 3 hearths in the nether and after a while, fps drops to between 0 and 2, and then kicks out of the server and prevents any further logins until DIM-1 is deleted
[problem_hearth.log](https://github.com/Momo-Studios/Cold-Sweat-Rework-Forge/files/7450796/problem_hearth.log)
d.

**Comment by MikulGamour** [comment]
Thank you for the log. Unfortunately, the server just printed a bunch of gibberish when it kicked you from the server, meaning we couldn't track down the exact cause of your issue. We've done several things to improve the performance of the Hearth and things related to it, so we hope that it'll be enough to solve the problem.

**Comment by OfficialLahusa** [comment]
This problem still persists in r.2.0.3.1. I only have to place a handful of hearths, and seconds later the FPS will drop down to 1. When reconnecting I receive the following error message:
`Internal Exception: io.netty.handler.codec.DecoderException: javal.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 2097158bytes where max allowed: 2097152`

**Comment by OfficialLahusa** [comment]
Note: The hearths I was using were in the nether.

**Comment by OfficialLahusa** [comment]
This forced us to remove the mod from our pack until it's fixed, because it is currently unplayable

**Comment by MikulGamour** [comment]
We're working on a fix that will hopefully rectify these issues, but there are some delays which prevent us from releasing it. I apologize that you had to remove the mod.

**Comment by OfficialLahusa** [comment]
Thank you for your help, we wish to add it back as soon as we can and will continue to give you feedback. This mod is great!

**Comment by OfficialLahusa** [comment]
This corrupted our entire SMP save, by the way, so maybe you should leave a note on curseforge to run regular backups (which we luckily did)
