### ISSUE TITLE
[PROBLEM] World creation get stuck at 0% on the new version

### ISSUE THREAD

**Issue by Sacri-Pan** [Momo-Studios/Cold-Sweat-Rework-Forge#103]
Here is the log

[latest.log](https://github.com/Momo-Studios/Cold-Sweat/files/9963806/latest.log)

**Comment by MikulDev** [comment]
This pack doesn't make it to the title screen for me, even with Cold Sweat removed, so I can't properly troubleshoot whatever issue it is. 
I've implemented fix that _might_ work, based on some of the logs I read while trying to get the pack to work, but I cannot be sure. At the very least it will improve compatibility with performance mods like Rubidium, Magnesium, Optifine, BetterFPS, etc.
This patch will come in the form of a minor update; probably 2.1.11.2
