### ISSUE TITLE
Cold sweat compalibility with waystones

### ISSUE THREAD

**Issue by Aerhtjiz** [Momo-Studios/Cold-Sweat-Rework-Forge#104]
Game crashes when using waystone to teleport in game, I've been to the issues of the github for waystone and the person that replies said that it was a issue with cold sweat.
https://www.dropbox.com/s/ju5g1xhrramt7g4/2022-11-05-2.log?dl=0

**Comment by MikulDev** [comment]
Please update Cold Sweat to the newest version (2.1.11.1). If this problem persists, please post the new crash report

**Comment by Aerhtjiz** [comment]
yea that worked thank you
