### ISSUE TITLE
[1.18.2]Exception in server tick loop When Creating New World.

### ISSUE THREAD

**Issue by OcrSu** [Momo-Studios/Cold-Sweat-Rework-Forge#105]
[crash-2022-11-10_11.18.54-client.txt](https://github.com/Momo-Studios/Cold-Sweat/files/9977043/crash-2022-11-10_11.18.54-client.txt)
ColdSweat-2.2-b01a.jar

**Comment by MikulDev** [comment]
Some config settings have changed in the way they're written, meaning old configs are causing a crash. This issue can be fixed be deleting your item-settings.toml config file. Cold Sweat will fix the problem automatically in the future.
