### ISSUE TITLE
Crash : Duplicate id value for 18 !

### ISSUE THREAD

**Issue by Blugori** [Momo-Studios/Cold-Sweat-Rework-Forge#106]
Hi, after updating cold sweat for 1.18 (ver 2.2-b01a), and trying to load an already existing world, I got a crash saying "duplicate id value for 18!"
I play with a lot of other mods, I'm just letting you know about this :)

[latest.log](https://github.com/Momo-Studios/Cold-Sweat/files/9980740/latest.log)

**Comment by Blugori** [comment]
Dosent happen when creating a new world, even with all mods loaded.

**Comment by MikulDev** [comment]
Try using the latest beta (2.2-b02b) to see if this issue has been resolved. The problem stems from the custom data Cold Sweat injects into goats that allows them to be sheared.

**Comment by Blugori** [comment]
Everythong works fine with the newer version ! Thank you, keep going please, your mod is really great !
