### ISSUE TITLE
[1.18.2] Incompatibility with Dynamic Trees causing worlds to not load.

### ISSUE THREAD

**Issue by Mic1e** [Momo-Studios/Cold-Sweat-Rework-Forge#108]
- Minecraft Version: 1.18.2
- Forge Version: 40.1.85
- Cold Sweat Version: 2.2-b01c
- Dynamic Trees Version: 0.11.0-Beta4

[Here is the log.](https://mclo.gs/kz1QSkl)

Hello, I've been working on a modpack recently and wanted to add Cold Sweat to it, however when I did, loading into worlds got stuck at 0-2% every time, it wouldn't crash nor produce any obvious errors on world load but it would just get stuck. I messed around and came to the conclusion that either removing Cold Sweat or Dynamic Trees fixed the issue so there must be some incompatibility between the two.
I'd also like to mention that there seems to be a rare occurrence where loading into a world might work with the two mods but that's hardly 'playable'.

**Comment by MikulDev** [comment]
Thanks for reporting; I was able to re-create the issue in a test world. Attached is a version of 2.2-b01c with a fix that worked for me. Please report back if this helps!

Unzip the file below and put the .jar in your mods folder:
[CS-2.2-test.zip](https://github.com/Momo-Studios/Cold-Sweat/files/10197101/CS-2.2-test.zip)

**Comment by Mic1e** [comment]
Thanks for the quick reply! I tested the attached version on a couple of new and old worlds with my full mod list enabled and everything seems to be working just fine!

Thanks for the quick fix!

**Comment by Proxwian** [comment]
Still doesn't work, please reopen
