### ISSUE TITLE
Crash with Create's Toolbox

### ISSUE THREAD

**Issue by SeanChengN** [Momo-Studios/Cold-Sweat-Rework-Forge#11]
ColdSweat-r2.0.3.1
create-mc1.16.5_v0.3.2f

When I do the following operations, the game is automatically saved and exited, 
and then I cannot enter the world again.
![ColdSweat-Test1](https://user-images.githubusercontent.com/20624068/142976863-894d1fd7-893a-4c1c-ab8c-3f8e6e3dd96c.gif)
[crash-2021-11-23_13.43.11-client.txt](https://github.com/Momo-Studios/Cold-Sweat-Rework-Forge/files/7586030/crash-2021-11-23_13.43.11-client.txt)

**Comment by MikulGamour** [comment]
We're looking into a few similar issues that cause the same crash. This should be fixed in the next update.
