### ISSUE TITLE
1.18.2 Incompatibility with race mods

### ISSUE THREAD

**Issue by StygianIkazu** [Momo-Studios/Cold-Sweat-Rework-Forge#112]
This mod has a seriously inconvenient conflict with mods like Dragon Survival and CreRaces. Those mods make it so that certain races cannot be in rain or water but are immune to fire damage, and other races cannot leave water for long or they suffocate. The conflict this mod causes is that while the fire immune races don't burst into flames, they DO still get all of the debuffs, rendering their main benefit useless, and water races can still freeze to death in water.

**Comment by MikulDev** [comment]
What solution to this problem would you propose? There are hundreds of Origins mods, and most of them will inevitably have this issue. If I remember correctly, Origins primarily operates through datapacks, so it theoretically should be possible for users to add fire/ice resistance to races as needed. 
There is no universal way for Cold Sweat to automatically know that a race is immune to heat or cold, meaning every race in every mod would have to be manually hard-coded for support. If this isn't the case, please let me know.

**Comment by StygianIkazu** [comment]
CreRaces and Dragon Survival are not Origins mods. They are separate race mods. I can understand not wanting to manually support Origins with so many addons and an already-available method of adding support. The two mods I mentioned do not have this option, though, as far as I'm aware.

**Comment by MikulDev** [comment]
Looking around, I see that neither of these mods are open source, meaning it would be very difficult, if even possible, to decompile their code and figure out how it works. If they could make their project open source, I could do it-- though knowing most mod developers they just might rather make the compat themselves than publish their code. 

There's a chance you could use datapacks to give fire resistance or ice resistance to certain races as needed. This shouldn't be too difficult for the dragons. I'm not sure about CreRaces, though.

**Comment by StygianIkazu** [comment]
Fair enough, I'll mention the incompatibility to them then. Thanks for looking into it.

**Comment by MikulDev** [comment]
You're welcome. Apologies for the delayed response. I'll be keeping this open for a while in case there are any developments.
