### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by Willem07** [Momo-Studios/Cold-Sweat-Rework-Forge#114]
Please tell me the crash from minecraft when trying to create a chunk, is the problem in the chameleon?

mod version: ColdSweat-2.2-b03c
[latest.log](https://github.com/Momo-Studios/Cold-Sweat/files/11024044/latest.log)

`at dev.momostudios.coldsweat.common.entity.ChameleonEntity.m_20240_(ChameleonEntity.java:620) ~[ColdSweat-2.2-b03c.jar%2377!/:2.2-b03c]`

**Comment by Willem07** [comment]
I noticed that after deleting cold sweat, I managed to enter the world

**Comment by MikulDev** [comment]
There have been a few changes made to the chameleon in 2.2-b03d. Try updating to that version and see if the issue persists.

**Comment by Willem07** [comment]
This solves my problem
