### ISSUE TITLE
[1.18.2] Crash when sleeping using Somnia Awoken

### ISSUE THREAD

**Issue by DeshiDesu** [Momo-Studios/Cold-Sweat-Rework-Forge#116]
Somnia-Awoken-1.18.2-3.0.104.jar
ColdSweat-2.2-b03e.jar
MC 1.18.2 Singleplayer
Forge 40.2.1

My game crashed after reaching -100 temperature while the world is simulated through sleeping using the Somnia Awoken mod.

https://spark.lucko.me/QgtCQJDYK2
[crash-2023-03-30_22.16.00-server.txt](https://github.com/Momo-Studios/Cold-Sweat/files/11117630/crash-2023-03-30_22.16.00-server.txt)

**Comment by MikulDev** [comment]
Although this occurred when Cold Sweat was loaded, the crash report indicates that it was actually Somnia Awoken that directly caused the crash to happen. I can't find any indication that Cold Sweat code is at fault here.

**Comment by DeshiDesu** [comment]
Sorry the crash was caused by First Aid. I reported the issue on their issue tracker.
