### ISSUE TITLE
[1.18.2] Incompatibility: Items do not drop after death when using First Aid

### ISSUE THREAD

**Issue by DeshiDesu** [Momo-Studios/Cold-Sweat-Rework-Forge#118]
I'm not even sure if this is even related to Cold Sweat but I'd like to confirm with the Cold Sweat devs.

**Issue:**
> Dying from -100 or 100 temperature will not drop your items from your inventory (All of it). They are basically deleted from the world.
> This does not occur if less than -100 or 100 temperatures.

**Mods:**
> FirstAid 1.11.1
> ColdSweat-2.2-b04a.jar

**Comment by MikulDev** [comment]
Thanks for posting. I was able to find the issue, and a fix will be making its way into the next beta (b04b).

**Comment by DeshiDesu** [comment]
Thank you!
