### ISSUE TITLE
[1.18.2] Bug: Player does not exit bed when taking temperature damage using First Aid

### ISSUE THREAD

**Issue by DeshiDesu** [Momo-Studios/Cold-Sweat-Rework-Forge#119]
**This is a crash resulted in a rare case with three different Mods:**
> FirstAid 1.11.1
> ColdSweat (any version)
> Somnia Awoken 1.18.2-3.0.105

**Issue:**
> With Somnia awoken mod, you can simulate the world instead of skipping the night when sleeping.
> When taking temperature damage at night, the player does not exit the bed and takes damage until death.
> After reaching 0 hearts, First Aid crashes the game with this log:
> [crash-2023-04-05_20.33.12-server.txt](https://github.com/ichttt/FirstAid/files/11170191/crash-2023-04-05_20.33.12-server.txt)

I have already submitted an issue to First Aid since the crash is in fact caused by First Aid, but I'd also like to report this issue here since I found it weird that you could not exit the bed after taking temperature damage using a specific setup. Please investigate and let me know if I am wrong!

**Comment by MikulDev** [comment]
I could add that as a feature, but this bug is the result of a larger incompatibility between Somnia and First Aid. From what I'm seeing, any lethal damage while sleeping would trigger this; not just freezing/burning. Because of that, this seems like more of a feature request than a bug report, unless there's something I'm missing.

**Comment by DeshiDesu** [comment]
Nope, you've more or less got the gist of it. I know zero modding nor how these mods work so I'm not entirely sure what exactly is causing it to fail when using all these mods. Your response suggests that this bug is not related to cold sweat  at all, which is one of the answers I was seeking for. If the underlying cause of the issue is related to other mods, then I wouldn't want your time spent on something that could be solved by contacting their devs instead. Nevertheless, I appreciate the insight and for taking your time with me.
