### ISSUE TITLE
Lava temperature problem

### ISSUE THREAD

**Issue by Pouchrat** [Momo-Studios/Cold-Sweat-Rework-Forge#12]
ColdSweat-r2.0.3.1.jar

I didn't seem to be getting much heat from lava, so I sat in it and it only made the temperature go up 11 degrees (Fahrenheit) from normal.

![image](https://user-images.githubusercontent.com/38634418/143158514-b650c99c-32b4-4384-aff4-29a0999f7f71.png)

![image](https://user-images.githubusercontent.com/38634418/143158487-d3cc83f4-0816-4c31-a633-85328cbdada3.png)

**Comment by MikulGamour** [comment]
Do you have the "Insulated" effect? It causes things from the environment to have a weaker effect on you. Other than that I don't know how to diagnose your issue from just photos (which isn't really your fault, it's just hard to pin down).

**Comment by Pouchrat** [comment]
Nope, was just in creative without armor or anything. (And switching to survival didn't change anything--though I didn't jump into the lava in survival lol!) But also I played with it some more, and adding more lava did make it hotter, at least. (This is only 2 blocks.)

**Comment by MikulGamour** [comment]
We've released a new version of the mod. Since we can't seem to recreate this issue, could you tell us if this issue still happens in version 2.1?

**Comment by Pouchrat** [comment]
Yeah, it still happens! I tried it out on an instance without any other mods, and it still happened. It's not a huge deal, though! It still gets to like 300+ if there's a whole pool of lava, just not when there's only a few blocks of it. I guess that could make lava a fairly effective heater if you can get it before it kills you! :)

**Comment by MikulGamour** [comment]
Apologies, but I don't know if we can fix your issue. We still can't recreate it, making troubleshooting basically impossible. Either way, thank you for bringing this up.
