### ISSUE TITLE
[1.18.2] Cold sweat item tooltips crash

### ISSUE THREAD

**Issue by DeshiDesu** [Momo-Studios/Cold-Sweat-Rework-Forge#120]
I noticed hovering over a mod menu button crashes the game. (Not sure if related) Hovering over items in inventory shows null above hotbar.

Also, version 2.2-b04b is nowhere to be found in the files page. Was it deleted?

**Mod version:**
> coldsweat-2.2-b04b.jar

**Crash:**
> [crash-2023-04-29_01.21.23-client.txt](https://github.com/Momo-Studios/Cold-Sweat/files/11358441/crash-2023-04-29_01.21.23-client.txt)

**Comment by MikulDev** [comment]
Try re-downloading b04b. There was some debug stuff left over and that's what caused the crash

**Comment by DeshiDesu** [comment]
Thanks

**Comment by DeshiDesu** [comment]
> Collaborator

There's no b04b yet, when will it come?

**Comment by MikulDev** [comment]
The new website has a bug that causes new files to not show up for a long time. It's there on the legacy website

**Comment by DeshiDesu** [comment]
It also wasn't there on the legacy website for a while, but I see it now. Thanks.

**Comment by MikulDev** [comment]
Alright, glad it's finally showing. CurseForge can be difficult like that sometimes
