### ISSUE TITLE
[1.16.5] Game Crash

### ISSUE THREAD

**Issue by 12345-mcpython** [Momo-Studios/Cold-Sweat-Rework-Forge#121]
May incompatible with rubidium and oculus.

log: https://gist.github.com/12345-mcpython/68b61c6f26b019440bff63b294a0c4e1

**Comment by MikulDev** [comment]
Recreating the pack you're using causes the game to crash, even without Cold Sweat. Could you send me the exact mods you're using (either a download link or modpack file from CurseForge/GDLauncher/MultiMC) so I can diagnose this issue? Thank you.

**Comment by 12345-mcpython** [comment]
CurseForge modpack: 

[RWorld-beta0.1.zip](https://github.com/Momo-Studios/Cold-Sweat/files/11516800/RWorld-beta0.1.zip)

**Comment by MikulDev** [comment]
In the modpack you provided, I get the crash you reported (something about Oculus mixins) even if Cold Sweat isn't loaded. 
From my testing, the issue actually seems to be with B3M (Вращение Земли Майнкрафтская), and has nothing to do with Cold Sweat being loaded at all. Try removing the mod and see if that resolves your issue.
