### ISSUE TITLE
[1.18.2] Crash: Exception in server tick loop

### ISSUE THREAD

**Issue by DeshiDesu** [Momo-Studios/Cold-Sweat-Rework-Forge#122]
>Forge 40.2.2
ColdSweat-2.2-b04b.jar

**Description:**
After respawning my game crashed with this message:
> java.util.ConcurrentModificationException: null

**Crash Report:**
> [crash-2023-05-14_00.51.52-server.txt](https://github.com/Momo-Studios/Cold-Sweat/files/11471175/crash-2023-05-14_00.51.52-server.txt)

**Comment by MikulDev** [comment]
Thanks for the report. Unfortunately, this issue is pretty difficult to track because it only happens in very specific scenarios, but I'll definitely give it another shot.

**Comment by DeshiDesu** [comment]
It was only one minute after creating the world that it crashed so I was pretty bummed out when it happened. Hope it gets fixed nonetheless.
