### ISSUE TITLE
Strange incompatibility between create and cold sweat

### ISSUE THREAD

**Issue by rjulib00** [Momo-Studios/Cold-Sweat-Rework-Forge#123]
[crash-2023-05-28_12.46.05-client.txt](https://github.com/Momo-Studios/Cold-Sweat/files/11584350/crash-2023-05-28_12.46.05-client.txt)

something about fluid

also I have the feeling is another mod, but removing create from the modpack the crash doesnt occurs

**Comment by MikulDev** [comment]
You're using a more recent version of Create than Cold Sweat was built for, so it's breaking a couple things. I'll fix that in the next beta, but for now if you want it to work you can use `1.18.2 v0.5.0i`
