### ISSUE TITLE
Suggestion: Spoiled food

### ISSUE THREAD

**Issue by DcNdrew** [Momo-Studios/Cold-Sweat-Rework-Forge#124]
I suggest that you should let food placed in iceboxes. Why? In Spoiled mod you can set what container prevents spoiling. :)

**Comment by MikulDev** [comment]
The latest 1.19 version now has tags that determine what items can be placed into the icebox/boiler, so you can add food items to the list. This change will also be coming to 1.18 and 1.16 soon.
