### ISSUE TITLE
Futurepack composite armor makes you freeze in winter

### ISSUE THREAD

**Issue by DcNdrew** [Momo-Studios/Cold-Sweat-Rework-Forge#125]
Hi!
Minecraft: 1.18.5
Cold Sweat: 2.1.11.1
I wear Futurepack's composite armor (which is supposed to be used in outer space) and I freeze in a room where is a working hearth in winter. If I take it off, everything is fine,

**Comment by MikulDev** [comment]
Does it prevent you from getting potion effects? That's the only reason why I think it might not work, unless the mod has some compat with Cold Sweat that doesn't work properly.

**Comment by MikulDev** [comment]
If you're still experiencing issues, try updating to the latest beta version. I will be closing this issue if I don't hear back.
