### ISSUE TITLE
[1.18.2] ColdSweat-2.1.11.1 crash

### ISSUE THREAD

**Issue by Proxwian** [Momo-Studios/Cold-Sweat-Rework-Forge#126]
[crash-2023-06-02_11.03.29-client.txt](https://github.com/Momo-Studios/Cold-Sweat/files/11632177/crash-2023-06-02_11.03.29-client.txt)

Happens when killed by Scarlet Persecutor from BornInChaos on dedicated server. Does not tested with beta version, sorry

**Comment by MikulDev** [comment]
If this happens on the latest beta, let me know. The piece of code causing this issue doesn't even exist anymore.
