### ISSUE TITLE
1.19 ColdSweat-2.2-b04e

### ISSUE THREAD

**Issue by DoggyBoneDavo** [Momo-Studios/Cold-Sweat-Rework-Forge#128]
Constant server crash, version beforehand works.

**Comment by MikulDev** [comment]
There's nothing I can do with this information. Post the crash log.

**Comment by DoggyBoneDavo** [comment]
sorry I forgot to attach the logs, heres the log
[crash-2023-06-13_11.05.25-fml.txt](https://github.com/Momo-Studios/Cold-Sweat/files/11731541/crash-2023-06-13_11.05.25-fml.txt)

**Comment by MikulDev** [comment]
This is similar to an issue posted on the Discord. I've already implemented a fix for it, which will go live shortly. Thanks for the extra info.
