### ISSUE TITLE
Crash on 1.19.2, Client and Server

### ISSUE THREAD

**Issue by Talan67** [Momo-Studios/Cold-Sweat-Rework-Forge#129]
Cold Sweat Version: 2.2-b04e
Forge Version: 43.2.11

When exiting the Cold Sweat config menu accessed via options, the game crashes with this exit code:

The game crashed whilst mouseclicked event handler
Error: java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because "saver" is null

On my server the game crashes upon launching, heres the crash report: https://pastebin.com/zrKtj8dd

**Comment by MikulDev** [comment]
The server crash will be fixed momentarily, but please provide the crash report for the other issue. The little excerpt you gave me isn't very enlightening

**Comment by Talan67** [comment]
here's the crash report for the client: https://pastebin.com/XNBxBXHY

**Comment by MikulDev** [comment]
This is a fascinating crash. I also can't seem to recreate it. Would you mind sending me your `world-settings.toml` file?

**Comment by Talan67** [comment]
https://pastebin.com/uqviTgXX

**Comment by MikulDev** [comment]
Does this happen reliably? I still can't get the crash to trigger in a production or test environment. There's a very slim chance that it's due to a mod you have installed, but I doubt it.

**Comment by MikulDev** [comment]
I finally figured it out. The configs aren't loaded into memory until the integrated server has started (AKA the player loads a world). This means that if you try to edit config settings from the main menu before doing anything else it will cause the game to crash. I think I've fixed this issue now.
