### ISSUE TITLE
Campfire seems to do nothing; Other issues as well

### ISSUE THREAD

**Issue by p1ut0nium-git** [Momo-Studios/Cold-Sweat-Rework-Forge#13]
I live in a cold biomes o plenty biome (snowy coniferous forest), and have serene seasons installed. It is the middle of winter. Ambient temp is around -10F.

I have all my diamond armor insulated.

- Campfire seems to not increase temp/keep player warm at all.
- Also insulated armor seems to not slow down player temp change
- Pouring hot water skin on player seems to not work either.
- Changing server difficulty from 3 to 1 seems to change nothing.
- Player temp drops to 100 and freezes to death fairly quickly.

Only the hearth seems to work. Keeps ambient temp at ~75F

Is this normal? Difficulty seems really out of whack.

Forge version: 1.16.5-36.2.9
ColdSweat version: 2.1-1
Serene Seasons version: 4.0.1.122

**Comment by MikulGamour** [comment]
Hello, sorry to see that you're having problems.
To help narrow down the issue, could you update your version of Cold Sweat to 2.1? There were many backend changes in the update that might fix your issues. If not, then we'll have a look.

**Comment by p1ut0nium-git** [comment]
Sorry. I listed the version incorrectly. I am using version 2.1-1

**Comment by p1ut0nium-git** [comment]
Also, I have some other mods that might be negatively impacting things. For instance:

- snow real magic 1.16.4-2.8.0

lots of snow on the ground too.

**Comment by MikulGamour** [comment]
Hey, just an update to say we haven't forgot about this issue, it's just that we can't replicate it on our end so it's very difficult to diagnose. The next update changes a lot of backend things, so this might be resolved naturally when that releases.
