### ISSUE TITLE
Serene Seasons causing issues with Cold Sweat (1.19.2/ ColdSweat-2.2-b04h.jar)

### ISSUE THREAD

**Issue by SHXRKIEgg** [Momo-Studios/Cold-Sweat-Rework-Forge#131]
**Brief Summary of the Issue**
So I am trying to use Cold Sweat in my Modpack to add it to the next update and it seems to have this issue with serene seasons.
TempModifier "sereneseasons:season" does not have a default constructor or is not registered!

**Crash Report Link**
Here is the latest.log due to it just freezing creating a world and is stuck at %45 and doesn't crash
[latest.log](https://github.com/Momo-Studios/Cold-Sweat/files/11924955/latest.log)

**Comment by SHXRKIEgg** [comment]
Does doesnt occur all the time but it does once in a while

**Comment by MikulDev** [comment]
I've now reworked how this system works to avoid this happening in the future. Thank you for the report.
