### ISSUE TITLE
World freeze after generating a jungle (1.19.2/2.2-b04h)

### ISSUE THREAD

**Issue by Edoliviro** [Momo-Studios/Cold-Sweat-Rework-Forge#132]
** The game freezes after going to a jungle biome, i still can move, but nothing updates**
(going to a jungle biome.)

The game stops making logs before it can process the freeze

Modlist:

Cold Sweat
Rubidium
Reforgium
Rubidium Extras
Rubidium Dynamic lights

**Comment by Edoliviro** [comment]
update: apparently it's causing copious amounts of server lag.

Removing balm resolved the problem before enabling all the mods of the modpack back.


mods installed when removing balm resolved the problem happened are:

cold sweat
parcool
actions of stamina
feathers
Rubidium
some common lib mods that you see in modpacks

**Comment by gamermodcraft** [comment]
exact same problem here, when a jungle generate the game freeze instantly

**Comment by MikulDev** [comment]
I've found the source of this issue, so it will be fixed next update. Thank you for your report.
