### ISSUE TITLE
[1.19.2] [ColdSweat-2.2-b04h.jar] Temperature is buggy

### ISSUE THREAD

**Issue by SiverDX** [Momo-Studios/Cold-Sweat-Rework-Forge#137]
https://imgur.com/a/WqHvMs3

Standing near lava has no effect
Burning ticks of fire / moving in fire seems to increase it but at the same time it tries to get back to 0

Frozen ocean (goes down):
![image](https://github.com/Momo-Studios/Cold-Sweat/assets/22003703/dec16ec9-6e7e-4618-99e1-bb63f7587a99)

Frozen ocean next to lava block (stays at 0):
![image](https://github.com/Momo-Studios/Cold-Sweat/assets/22003703/d989c833-336e-4e59-b63d-0637eabfddee)

Desert (stays at 0):
![image](https://github.com/Momo-Studios/Cold-Sweat/assets/22003703/dd8a766a-90a9-4672-a880-289abdef255d)

**Comment by SiverDX** [comment]
(Doesn't crash, don't know how to remove that tag)

**Comment by SiverDX** [comment]
Swimming in lava (very slowly going up):
![image](https://github.com/Momo-Studios/Cold-Sweat/assets/22003703/ed94f7bb-acca-445b-8fb9-f630fe97f796)

![image](https://github.com/Momo-Studios/Cold-Sweat/assets/22003703/77563d41-c51a-4939-91a1-3d79403053ca)

Moving away (it's going back down to 0):
![image](https://github.com/Momo-Studios/Cold-Sweat/assets/22003703/8128f01a-93cb-4f6a-9972-dc43c683a659)

![image](https://github.com/Momo-Studios/Cold-Sweat/assets/22003703/9eacd92e-a1c3-4a4d-ba22-9bf4c0c9a00e)

**Comment by SiverDX** [comment]
After restarting the game several times it worked for a bit:

![image](https://github.com/Momo-Studios/Cold-Sweat/assets/22003703/4d29669a-959e-4f2e-b9a7-65c43bc88a2b)

![image](https://github.com/Momo-Studios/Cold-Sweat/assets/22003703/99ce8767-d6bb-4ef8-84a2-1bdf07f4f0a2)

Being in lava does not seem to get registered as bad though (it's basically the same as being close to it)

---

![image](https://github.com/Momo-Studios/Cold-Sweat/assets/22003703/3c021438-047f-4edf-8753-08c9d913f973)

But not it's bugged again (happen shortly after the screenshot above)

![image](https://github.com/Momo-Studios/Cold-Sweat/assets/22003703/ed3f9fbd-2a2b-4266-848e-9be6da227c13)

![image](https://github.com/Momo-Studios/Cold-Sweat/assets/22003703/2f8ab989-d5e6-49ff-8946-8ac2f526e4bf)

**Comment by SiverDX** [comment]
I know I'm kinda spamming right now

I rejoined the world (singeplayer btw) and it was still bugged
I left the game open for a couple of minutes and now it works again

And like correctly, temperature shown by `Thermometer` can get to 90 when in lava (previously it got stuck at like 50) etc.

![image](https://github.com/Momo-Studios/Cold-Sweat/assets/22003703/8c2a7bef-c260-4569-b160-e7b852f65d93)

---

Nevermind bugged again
Was just walking around placing ice blocks, testing the temperature effect

![image](https://github.com/Momo-Studios/Cold-Sweat/assets/22003703/ff44df38-157d-4a4e-b654-727e6600bd73)

**Comment by MikulDev** [comment]
So, what exactly are you trying to test here? From the information I'm seeing (which, although I appreciate it, is only partially helpful because I don't know what the temperature was before and after the blocks had their effect), this seems to be intended behavior. There is no temperature difference between being submerged in lava and standing directly next to it.

I also haven't seen this issue or been able to reproduce it, and nobody on the Discord server has reported it. 

Just so we're on the same page, the lava affects the `WORLD` temperature type, and when the thermometer reads above 37.75, you start overheating.

**Comment by SiverDX** [comment]
In the tests sometimes temperature modifiers seem get lost / not applied
I'm using a lot of mods that could be why but I'm not sure which type could be causing this behaviour

Right now it seems to work correctly again

**Comment by MikulDev** [comment]
What version are you using there? Or are you using source code?

**Comment by SiverDX** [comment]
version is in title 
debug is same version (loaded through curseforge)

**Comment by MikulDev** [comment]
Alright, my bad. It's still not very easy to tell why this is happening. Are these statistics taken in the same place? I'm having a hard time understanding what scenarios all these screenshots were taken in.
> ![image](https://user-images.githubusercontent.com/22003703/252016277-ff44df38-157d-4a4e-b654-727e6600bd73.png)
> ![image](https://user-images.githubusercontent.com/22003703/252015821-8c2a7bef-c260-4569-b160-e7b852f65d93.png)

**Comment by SiverDX** [comment]
If it occurs again I'll make more clear screenshots

can't even say anymore which belong together 😐

**Comment by SiverDX** [comment]
Standing next to lava source - temperature stays at 0
Start of PlayerTempCap tick
![image](https://github.com/Momo-Studios/Cold-Sweat/assets/22003703/8f86dce6-f6ba-4b68-b1bc-bf8a5e682fcb)

End of PlayerTempCap tick had no changes

At the same time when moving away (`terralith:yellowstone` biome):
![image](https://github.com/Momo-Studios/Cold-Sweat/assets/22003703/fb39653c-378c-4703-9c4f-2dd0573c3bf1)

(CORE is actually changing)
Moving next to the lava again raises the temperature (somewhat slow though) but it stops at 0

Something seems off with high temperatures when this bug occurs
Currently the thermostat shows 16 celsius next to the lava in the `yellowstone` biome
And 10 when moving away from the lava

(This is all with no items equipped, no effects active etc.)

---

Desert biome
![image](https://github.com/Momo-Studios/Cold-Sweat/assets/22003703/ecdd5244-ee8d-4e7b-bb93-089c756306ba)

Standing next to lava
![image](https://github.com/Momo-Studios/Cold-Sweat/assets/22003703/3298a241-2af5-4c77-917b-b936656a5161)

Next tick:
![image](https://github.com/Momo-Studios/Cold-Sweat/assets/22003703/640f1ad3-819f-46c4-855b-66afd866c10a)

Put an ice block next to the lava - modifiers:
![image](https://github.com/Momo-Studios/Cold-Sweat/assets/22003703/c713f077-3624-4f10-a1fa-42ab13182e92)

![image](https://github.com/Momo-Studios/Cold-Sweat/assets/22003703/a7b89d7d-c43f-4ae1-92ac-2af9fa99ff1f)

![image](https://github.com/Momo-Studios/Cold-Sweat/assets/22003703/0fb06d96-9136-42c6-a8bc-8eceb5df578c)

Wanted to check what the modifiers etc. should be for that spot but restarting the game etc. does not fix the issue right now

**Comment by MikulDev** [comment]
I'm really sorry if I am still misunderstanding, but it kind of seems like this works as intended. Your first example in the Yellowstone biome demonstrates the system working properly (note how `WORLD` jumps up all the way from -0.2 to 0.7). 

Just to reiterate, blocks do NOT directly affect your body temperature. They affect the `WORLD`. When `WORLD` reaches a certain threshold (either below 10C or above 37C), then your `CORE` temperature starts decreasing/increasing at a steady pace.

**Comment by SiverDX** [comment]
But when I'm in a desert next to a lava source my temperature should be rising VERY fast
But with this issue here it literally just stays at 0 because the world temperature does not go over the threshold (or just barely depending on the time of day)

I know that when this issue disappears the world temperature will heavily increase (up to 90 celsius etc)

**Comment by SiverDX** [comment]
It fixed itself right now for example:
![image](https://github.com/Momo-Studios/Cold-Sweat/assets/22003703/4f4645e8-eeb3-4229-aa59-7b258263d6ef)

This was hard stuck at 40 a second before

**Comment by MikulDev** [comment]
Ok, I just had a sudden realization because I just got finished working on an issue that uses the same bit of code as this issue does. Try this version and see if it works, if you please (GitHub doesn't allow .JAR files, so you'll have to unzip it first):
[ColdSweat-2.2-b04i.zip](https://github.com/Momo-Studios/Cold-Sweat/files/12062945/ColdSweat-2.2-b04i.zip)

**Comment by SiverDX** [comment]
Ok, trying it out
Will update if something pops up

**Comment by MikulDev** [comment]
I'm going to mark this as resolved soon if there aren't any problems anymore. Please let me know

**Comment by SiverDX** [comment]
Actually can close this now, kinda forgot to do that
From the tests I did there were no problems with the test version and using the latest official version things seem fine too

**Comment by MikulDev** [comment]
Great, glad to hear it
