### ISSUE TITLE
[suggestion] Shift default habitable temperatures by -5 F

### ISSUE THREAD

**Issue by ColonelGerdauf** [Momo-Studios/Cold-Sweat-Rework-Forge#140]
Not only does it make the mod more playable in a typical setting, but the temperature range of 45F `0.309966618979494515` to 95F `1.5` is a bit more realistic and easier to write down.

**Comment by MikulDev** [comment]
I don't really see the point of doing this. It's not a very drastic change anyway, plus 50 and 100 are nicer numbers than 45 and 95 (in Celsius the minimum temperature is an even 10 as well). These settings are very easy to change if you're not happy with them.

**Comment by MikulDev** [comment]
I may reduce the maximum temperature to 95, or even 90, since that is a little high for "livable" temperatures
