### ISSUE TITLE
Wiki update request

### ISSUE THREAD

**Issue by scalyhat** [Momo-Studios/Cold-Sweat-Rework-Forge#145]
It would be nice to have an up to date wiki. Blocks lke the Hearth do not behave exactly as described in the wiki, presumably because they've been changed, and some items are not described in the wiki.
Some wiki pages haven't been updated for more than a year.

**Comment by MikulDev** [comment]
I will have more time to update the wiki when 2.2 is fully released. At the moment I just can't, but I agree it does need to happen considering the radical overhaul that 2.2 turned out to be
