### ISSUE TITLE
[1.19.2] [ColdSweat-2.2-b04j] Hearth insulation zone conflict

### ISSUE THREAD

**Issue by scalyhat** [Momo-Studios/Cold-Sweat-Rework-Forge#146]
Hearths can stop providing insulation and not restart with time or upon chunk reloads.

### To reproduce:
![image](https://github.com/Momo-Studios/Cold-Sweat/assets/30766104/0fb34bea-4972-40c2-880c-b399aeb1287c)
0) Have a box where insulation works fine.
1) Add a disconnected room with a hearth, let it heat up fully.
2) Create a doorway between the two rooms.
3) Leave the immediate area for some time, then come back in.
4) The zone which the first hearth insulated will not be insulated - in this case, the first room is cold, while the second one isn't.
![image](https://github.com/Momo-Studios/Cold-Sweat/assets/30766104/4c89f612-e494-43cd-9aa8-53f42cc013d4)
4.1) Occasionally, the insulation effect will also vanish from the second room in this setup.
5) If the chunks are unloaded and then reloaded, the hearths will show the air particles for zoning, but the insulation effect does not appear.

### Extra:
![image](https://github.com/Momo-Studios/Cold-Sweat/assets/30766104/bd655dcb-7fb4-4864-ac2f-f5eddff1c5b5)
The insulation zone is present, but no effect is applied.

### Expected:
* Both hearths provide insulation nearby within their ranges.

**Comment by MikulDev** [comment]
This problem will be fixed in the next release
