### ISSUE TITLE
[1.19.2] [ColdSweat-2.2-b04j] Inconsistent hearth insulation updates

### ISSUE THREAD

**Issue by scalyhat** [Momo-Studios/Cold-Sweat-Rework-Forge#147]
The insulation effect from the hearth does not behave consistently in dynamic situations, takes a very long in-game time to propagate - potentially enough to freeze to death.

### To reproduce:
![image](https://github.com/Momo-Studios/Cold-Sweat/assets/30766104/22399cf7-ed0b-4910-bbe6-de3a7a078cff)
1) Heat up hearth in this layout
2) Break the 2 birch planks (they are in turn surrounded by more walls, so the space is still enclosed)
3) The insulation effect will not immediately appear in the new space, and will not propagate there within a minute (as far as tested).
P.S. If that space was initially empty, the hearth will fill it with insulation; however, if you place blocks there and wait, breaking them leads to the same bug.

This may not happen multiple times in the same space due to insulation zones sometimes lingering inside wall blocks.

### Expected:
The effect will be extended to the new space quickly enough for the player to not freeze if standing in that space.

### Suggestions for fix:
* Add a force zone update button to the hearth
* Add a config option to change update frequency

**Comment by MikulDev** [comment]
This problem will be fixed in the next release
