### ISSUE TITLE
How to modify the effect of Insulation Ingredients in Cold Sweat version 1.18.2(2.1.11.1)

### ISSUE THREAD

**Issue by HerryBob** [Momo-Studios/Cold-Sweat-Rework-Forge#149]
**Describe the change/addition you'd like**
I want to define the items that provide insulation when when it's sewn on

**Additional context**
My english is poor, I hope you understand what I mean

**Comment by MikulDev** [comment]
I don't understand; this is already a feature

**Comment by MikulDev** [comment]
Apologies, I misread the title. You will have to use beta versions to use this feature. 2.1.11.1 is several months old.

**Comment by HerryBob** [comment]
ok thanks
