### ISSUE TITLE
Cold sweat causing CURIOS to turn invisible

### ISSUE THREAD

**Issue by Edoliviro** [Momo-Studios/Cold-Sweat-Rework-Forge#15]
i'm currently using the beta 

- ColdSweat-b2.1-1
- Optifine HD U G8
- Performant 3.56m

**Comment by MikulGamour** [comment]
We've gotten this report on our Discord server. A fix is coming for this issue very soon.

**Comment by MikulGamour** [comment]
This issue has been fixed in Cold Sweat 2.1. Thank you for reporting!
