### ISSUE TITLE
Block temperature working incorrectly (MC forge 1.19.2/Cold Sweat 2.2-b04k)

### ISSUE THREAD

**Issue by nickyprowse21** [Momo-Studios/Cold-Sweat-Rework-Forge#150]
**Describe the bug**
Block temperatures in the most recent update seem to have been messed up. Several issues around blocks not changing the temperature correctly, for example heat sources no longer consistently warming up the surrounding area, or block temperatures being ignored in the presence of other blocks. Specifically, placing one heat source then placing a different one will ignore the temperature of the first and only apply the second

**To Reproduce**
Unsure on how to replicate it exactly as sometimes it works as intended but other times it does not

**Expected behavior**
Temperature in specific location in previous update, in radius of 2 campfires during winter (2.2-b04j):
![2023-07-30_23 35 29](https://github.com/Momo-Studios/Cold-Sweat/assets/126621414/b99069b0-cba7-4409-8c3e-81a47508d458)

Temperature in the same location in current update (2.2-b04k):
![2023-07-30_23 37 14](https://github.com/Momo-Studios/Cold-Sweat/assets/126621414/3605ea06-729d-4861-9d4e-2da50abb7fe1)

**Additional context**
As shown in the images it seems whatever change between versions means that the campfires in this location do not affect the player's temperature anymore, although campfires in other locations do still change the temperature.

**Comment by MikulDev** [comment]
Thank you for the detailed report. I've actually already found a solution to this problem, and it should be fixed next update
