### ISSUE TITLE
[1.18.2-ColdSweat-2.2-b04k] World still gets frozen

### ISSUE THREAD

**Issue by Rocketcat19** [Momo-Studios/Cold-Sweat-Rework-Forge#151]
Describe
As the title says, world still gets frozen when entering the jungle or savanna.

Mods
AdvancedCompas-forge-1.18.2-1.2.11
ColdSweat-2.2-b04k
SereneSeasons-1.18.2-7.0.0.15

Log 
[Render thread/WARN]: Unable to parse the boolean system property 'java.net.preferIPv6Addresses':system - using the default value: false

**Comment by MikulDev** [comment]
That log is definitely not the issue, but thanks regardless. I've already found a solution to this issue, which will be fixed next beta.
