### ISSUE TITLE
Rendering Issue with Legendary Tooltips (MC 1.19.2/v2.2-bo4k)

### ISSUE THREAD

**Issue by FryoKnight** [Momo-Studios/Cold-Sweat-Rework-Forge#152]
### **Describe the bug:**
When both [Legendary Tooltips](https://www.curseforge.com/minecraft/mc-mods/legendary-tooltips) and Cold Sweat are installed, and Item Render is on, items no longer renders their Insulation in the Tooltip (though space for it still remains).

### **To Reproduce:**
1. Install Cold Sweat
2. Install [Legendary Tooltips](https://www.curseforge.com/minecraft/mc-mods/legendary-tooltips) (and it's dependencies).
   2a. Change Config for Item Rendering to "Equipment" or "All" if not already on.
3. Look at a insulated item.
4. See issue.

### **Expected behavior:**
The aesthetics of [Legendary Tooltips](https://www.curseforge.com/minecraft/mc-mods/legendary-tooltips) with the Insulation displayed.

### **Additional context:**
I have noticed on _rare_ occasions, the Insulation bar will properly render on some occasions, but seems to be a issue with "Item Rendering". This seems to mostly affect armor pieces, as rendering on them is on by default.

Turning off the Rendering does fix the issue for now though.

### **Images include to show the issue (Equipment Render enable):**
![2023-07-31_17 57 05](https://github.com/Momo-Studios/Cold-Sweat/assets/33318750/9b8b30db-2033-4f4a-ad91-23775b7e8148)
![2023-07-31_17 57 06](https://github.com/Momo-Studios/Cold-Sweat/assets/33318750/ad84748c-f986-4790-a94b-719fec7ebe11)
![2023-07-31_17 57 08](https://github.com/Momo-Studios/Cold-Sweat/assets/33318750/4a199667-1eb1-4a5f-bb13-d14c666a73fc)
![2023-07-31_17 57 09](https://github.com/Momo-Studios/Cold-Sweat/assets/33318750/d6c4840d-a4a2-4814-9919-21ee3e5a0a16)
![2023-07-31_17 57 10](https://github.com/Momo-Studios/Cold-Sweat/assets/33318750/5edfbd0f-f280-402a-923c-544ab445a672)
![2023-07-31_17 57 11](https://github.com/Momo-Studios/Cold-Sweat/assets/33318750/dd95fd53-3711-480c-a550-3549d49a00f0)

### **Mods involved:**
Minecraft v1.19.2
Forge v43.2.21
[Iceberg](https://www.curseforge.com/minecraft/mc-mods/iceberg/files/4300529) v1.1.4 (Dependency)
[Prism](https://www.curseforge.com/minecraft/mc-mods/prism-lib/files/3993293) v1.0.2 (Dependency)
[Legendary Tooltips](https://www.curseforge.com/minecraft/mc-mods/legendary-tooltips/files/4278509) v1.4.0
[Cold Sweat](https://www.curseforge.com/minecraft/mc-mods/cold-sweat/files/4664445) v2.2-b04k

**Comment by MikulDev** [comment]
I would definitely take this up with the developers and see if they would know why this is occurring. I find it strange that this only happens with items that have the 3D model in the tooltip.

**Comment by MikulDev** [comment]
Seems like the devs still haven't responded to your issue. I'm going to close this, since I assume it's an issue on their end.
