### ISSUE TITLE
Mixin Crash on Load(Forge 43.2.21 | Cold Sweat 1.19.2-2.2-b05a)

### ISSUE THREAD

**Issue by BookerCatch** [Momo-Studios/Cold-Sweat-Rework-Forge#154]
Something about incompatible changes at opcode 108 in the MixinCampfire class. Please see attached log. Only Cold Sweat loaded on Forge 43.2.21

[latest.log](https://github.com/Momo-Studios/Cold-Sweat/files/12245746/latest.log)

**Comment by MikulDev** [comment]
Is there a crash log? This doesn't say anything.

**Comment by MikulDev** [comment]
Thank you for the quick find. I will be releasing a patch momentarily
