### ISSUE TITLE
Conflict with Cracker's Wither Storm Mod 1.16.5

### ISSUE THREAD

**Issue by SEDIIK** [Momo-Studios/Cold-Sweat-Rework-Forge#157]
Encountered a crash when launching the world with Cracker's Wither Storm Mod. I attach the error log to the message
Version: ColdSweat-2.2-b05c.jar

[tl-logger11116632114494325097.txt](https://github.com/Momo-Studios/Cold-Sweat/files/12410978/tl-logger11116632114494325097.txt)

**Comment by MikulDev** [comment]
This will be fixed in the next version. Thanks for the report.
