### ISSUE TITLE
REI and Cold sweat mixin incompatibility

### ISSUE THREAD

**Issue by GoddessStorm** [Momo-Studios/Cold-Sweat-Rework-Forge#158]
Having both mods installed results in the game stalling on launch due to a mixin related issue. I was told to report it and link these two files.
https://github.com/shedaniel/RoughlyEnoughItems/blob/9.x-1.19/forge/src/main/java/me/shedaniel/rei/mixin/forge/MixinEffectRenderingInventoryScreen.java#L48 

https://github.com/Momo-Studios/Cold-Sweat/blob/1.19.x-FG/src/main/java/dev/momostudios/coldsweat/mixin/MixinEffectsScreen.java

**Comment by MikulDev** [comment]
I've gotten a few reports in the past about this issue, and deemed it impossible to fix, but I took another crack at it and figured out a way. This will be fixed in the next version
