### ISSUE TITLE
[1.16.5 ColdSweat-2.2-b05c FORGE] Tooltip - insulating icons poorly displayed

### ISSUE THREAD

**Issue by zanecek** [Momo-Studios/Cold-Sweat-Rework-Forge#159]
The isolation icons on the first tooltip row are displayed over (through) information on first row from some other mods:
- Quark (when Client - Improved Tooltips - ON): over their armor icons
- Elenaidodge2: over their armor weight icons (so called feathers)
- UntranslatedItems: over item name in second language
- maybe some others...?
![2023-08-31_02 19 12](https://github.com/Momo-Studios/Cold-Sweat/assets/62807156/5520e97d-0cf5-47a2-9941-4fe3401a7eb5)

Thx for your help.

**Comment by MikulDev** [comment]
Thanks for reporting this. I've found out how to fix the issue
