### ISSUE TITLE
Latest Cold Sweat Update Causes Pre-Existing Worlds to Crash

### ISSUE THREAD

**Issue by Phweeeee** [Momo-Studios/Cold-Sweat-Rework-Forge#16]
[crash-2021-12-16_13.39.58-server.txt](https://github.com/Momo-Studios/Cold-Sweat-Rework-Forge/files/7729994/crash-2021-12-16_13.39.58-server.txt)
[latest.log](https://github.com/Momo-Studios/Cold-Sweat-Rework-Forge/files/7729995/latest.log)

(No debug generated, weird.)

**Comment by MikulGamour** [comment]
What version is this happening in?

**Comment by Phweeeee** [comment]
Latest beta update for 1.16.  ColdSweat-b2.1-2.jar is where i happens. It works perfectly fine on the version before it. I've also deleted configs and it didn't fix it.

**Comment by MikulGamour** [comment]
I've found the source of the issue. It'll be fixed in the next beta
