### ISSUE TITLE
[1.16.5 ColdSweat-2.2-b05d FORGE] Biome temperature configuration error

### ISSUE THREAD

**Issue by zanecek** [Momo-Studios/Cold-Sweat-Rework-Forge#161]
After the first start, a default configuration is created.
File world_settings.toml, "Biome Temperatures" contain a predefined values, f.e.
["minecraft:jungle", 76, 87, "F"]

After the first entry into the ingame config (without any changes) temperatures in file will change to MC unit, but without unit change.
["minecraft:jungle", 1.0476190476190477, 1.3095238095238095, "F"]

And it makes it very cold in a hot biome. "F" should be changed to "MC".
![2023-09-07_02 21 38](https://github.com/Momo-Studios/Cold-Sweat/assets/62807156/9b859ee5-5dc6-4220-ba19-dff771dc6c41)

**Comment by MikulDev** [comment]
Thanks for the report. This issue has been fixed in the patch I just released :)
