### ISSUE TITLE
[1.16.5 ColdSweat-2.2-b05f FORGE] Very large number of conflicts with mods

### ISSUE THREAD

**Issue by SEDIIK** [Momo-Studios/Cold-Sweat-Rework-Forge#163]
I have a mod build for over 300 mods. And since the version of your mod 2.2-b05f start conflicts of a very large number of mods. Running separately mods with conflicts crashed.
To the message I attach the error log, it shows all the conflicts of your mod with other mods.
[tl-logger10501553456202538937.txt](https://github.com/Momo-Softworks/Cold-Sweat/files/12706981/tl-logger10501553456202538937.txt)

**Comment by MikulDev** [comment]
Thanks for the report. I've found the source of the issue.
