### ISSUE TITLE
[1.19.2] Mixins Crash

### ISSUE THREAD

**Issue by Proxwian** [Momo-Studios/Cold-Sweat-Rework-Forge#164]
Crash when creating/joining singleplayer world. 1 of 5 launches leads to crash

[crash-2023-09-25_14.15.30-server.txt](https://github.com/Momo-Softworks/Cold-Sweat/files/12716181/crash-2023-09-25_14.15.30-server.txt)

**Comment by MikulDev** [comment]
That's definitely an interesting place to crash from. I've now made a check to account for this; thanks for the report.
