### ISSUE TITLE
Insulation disappears (1.19.2)

### ISSUE THREAD

**Issue by thedeerirty** [Momo-Studios/Cold-Sweat-Rework-Forge#165]
So far, I've only been able to reproduce this issue myself, but I'm running a server with this mod, and I've noticed that often times logging in with insulated armor causes it to no longer be insulated. This applies to both modded and vanilla armors, from what I've seen/found.  So far I've only tested with leather and wool as insulators.

**Comment by MikulDev** [comment]
This may be related to the known bug in the project's Discord. On multiplayer servers, when the player opens their inventory in creative mode, all custom item data (like insulation) is lost. This is actually the fault of Vanilla/Forge, due to the way the creative menu is handled internally. There's unfortunately nothing I can really do about it; and trust me, I've tried.

**Comment by thedeerirty** [comment]
Oh hm, that makes sense. It always seemed to correlate with joining the server, but it could be that, yeah.

**Comment by MikulDev** [comment]
I haven't observed an issue like this happening in survival multiplayer or single player, which is why I assumed it was the issue I mentioned. If you could test this scenario in both survival and creative to be sure, that'd be great

**Comment by thedeerirty** [comment]
Sure, I'll try to pay attention when I'm playing next. I'm gonna go out on a limb and assume its the same issue, given that it has only happened to me (from my knowledge) and I'm the only person able to freely access creative, but I'll keep a look out for maybe other weird circumstances.

**Comment by Rocksnotch** [comment]
I also have this issue, where my insulation seems to just disappear upon loading into a server or switching to creative.

Edit: I should say it ALSO happened when I went to the Nether and back, poof all insulation gone.
Edit 2: The Backtank from Create, when placed on the ground then picked back up, ALSO loses insulation.

**Comment by MikulDev** [comment]
I can't confirm these issues in testing. It doesn't happen to me when loading into a server or changing dimensions, only when I open the creative menu. I will reopen this issue if there's any further info.

**Comment by dragonshardz** [comment]
Confirming it's caused by opening inventory in Creative/Spectator mode, so ultimately a Forge bug still extant in 1.20.1 and probably newer.
