### ISSUE TITLE
Load crash

### ISSUE THREAD

**Issue by al-wei** [Momo-Studios/Cold-Sweat-Rework-Forge#166]
1.16.5  ColdSweat-2.2

My modpack added ColdSweat and started the game crashed.
https://gist.github.com/al-wei/e417c55ea51fb70e96be1dcaa61a54eb

**Comment by MikulDev** [comment]
I see four mods that have mixin errors, but nothing mentioning Cold Sweat:
Redirector
SimplySeasons
Sodium
Rubidium

I think the main culprit is Rubidium, but those other mods have mixin issues that don't crash the game. Try removing Rubidium and see if that helps (For now, just to see if it works)

**Comment by ColonelGerdauf** [comment]
Well, Sodium is a Fabric-only mod, and ties back to Rubidium

A suggestion I will make is temporarily swapping Rubidium with Embeddium (alongside the addons) and see if that improves anything. Embeddium is also a Sodium fork, one that promises to focus on bug fixing relative to Rubidium.

**Comment by MikulDev** [comment]
Fow now, I would just do what Gerdauf says. Rubidium has over 200 open issues, many of which are very old. It's unlikely that you'll get a response soon.
I'm closing this issue for now
