### ISSUE TITLE
startup crash

### ISSUE THREAD

**Issue by codec-d** [Momo-Studios/Cold-Sweat-Rework-Forge#169]
log shows that the game crashed during startup due to an issue with a Mixin injection in the cold_sweat mod
`Critical injection failure: @Inject annotation on renderItemNamePre could not find any targets matching 'renderSelectedItemName(Lnet/minecraft/client/gui/GuiGraphics;I)V' in net/minecraft.client.gui.Gui. Using refmap cold_sweat.mixin-refmap.json`

 the mixin cold_sweat.mixin.json is trying to inject into the method renderSelectedItemName in the Gui class, but that method does not exist.

I'm using forge 47.1.3. many mods require this specific verison so this could just be a compat issue (likely) if the latest version of forge is being used.

also using Oculus

**Comment by MikulDev** [comment]
This issue is fixed now in 2.2.1. Thanks for the report.
