### ISSUE TITLE
Crash When Shift-Clicking Invalid Item into Boiler/Icebox

### ISSUE THREAD

**Issue by 6371peter** [Momo-Studios/Cold-Sweat-Rework-Forge#17]
Mod Version:ColdSweat-r2.1
Forge Version:1.16.5 Forge 36.2.22
Java 8(8.0.311)

Place Boiler(or Ice Box),then right-click it open GUI,hold shift and left-click any Boiler(or Ice Box) unable to accepts item(just like stone),then game will no-response.When hold shift and left-click right item(for example:click coal into Boiler),game will run normally.I try run game only ColdSweat but it still no-response.

**Comment by MikulGamour** [comment]
Thank you for reporting. We will fix this issue next update.
