### ISSUE TITLE
[1.20.1] coldsweat 2.2.1 Goat Armor Crash

### ISSUE THREAD

**Issue by codec-d** [Momo-Studios/Cold-Sweat-Rework-Forge#172]
The crash seems to happen randomly when rendering an entity, specifically a mob from the Iron's Spellbooks mod. it looks like a complex interaction between ColdSweat's goat armor, the spellcasting mob entity, and the rendering systems.

Appears to indicate that the armorSlot variable is null when it tries to call ordinal() on it.

```
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.EquipmentSlot.ordinal()" because "armorSlot" is null
	at com.momosoftworks.coldsweat.common.item.GoatArmorItem$1.getHumanoidArmorModel(GoatArmorItem.java:34) ~[ColdSweat-2.2.1.jar%23618!/:2.2.1] {re:classloading}
```
I'm not sure how to consistently reproduce this crash yet. Let me know if any other info would be helpful in tracking this down!

Crash report - https://pastebin.com/0wQkQshK

**Comment by MikulDev** [comment]
Is it possible for mobs from this mod to wear armor from other mods? It seems it might be that there's a mob wearing goat armor in a `null` slot, or something in the mob renderer is passing `null` to the armor renderer. Basically, `armorSlot` should definitely never be null.

**Comment by codec-d** [comment]
may be able to close this, after a weekend of debugging I found the source of a separate issue. I found a similar rendering bug caused by azurelib (epic empires mod) will verify if that was the case here.

**Comment by MikulDev** [comment]
Thank you for your sleuthing. I'll close this for now, but I can always reopen it if you're sure it's something to do with Cold Sweat.
