### ISSUE TITLE
IDEA: cen you pls add water flasks or Canteens

### ISSUE THREAD

**Issue by ShadowSlayerFX1** [Momo-Studios/Cold-Sweat-Rework-Forge#173]
a item that cen hold water and be drinked from multable times without having to refill it

**Comment by MikulDev** [comment]
I doubt I will add something like this. I think waterskins in their current form are powerful enough. Also keep in mind that you can keep a waterskin in your hotbar to gradually soak up its temperature without consuming the water inside.
