### ISSUE TITLE
[1.19.2 SteamPunk LPS] Applying Insulation to Create Backtank Removes insulation when placing it then picking it up

### ISSUE THREAD

**Issue by Rocksnotch** [Momo-Studios/Cold-Sweat-Rework-Forge#174]
As of 10/9/23, whenever I apply insulation to a Create backtank then place it down to charge said backtank (or just place it in the world) then pick it back up, it removes all insulation on said backtank. 

This also applies for if I break it with the Wrench or break it with a pickaxe/any other acceptable tool.

**Comment by MikulDev** [comment]
I've had this issue pop up on the Discord server, and we came to the conclusion that it's likely a Create issue, not Cold Sweat. What's probably happening is that custom mod data isn't being preserved when it's placed in block form.

**Comment by Rocksnotch** [comment]
Ah that is a bit unfortunate. I might then make an issue post on Create then about it.
Thank you for the quick reply!
