### ISSUE TITLE
intergration with pneumaticcraft

### ISSUE THREAD

**Issue by ilovehorrorcats** [Momo-Studios/Cold-Sweat-Rework-Forge#176]
I think the heat sinks from the mod should affect the surounding temp

**Comment by MikulDev** [comment]
You can probably accomplish this with configs. Look in the `world-settings.toml` file under `"Block Temps"`

**Comment by ilovehorrorcats** [comment]
I do not know what to do. The heat sink temp varies and can range from extremly hot to room temp to extremly cold

**Comment by MikulDev** [comment]
You can make multiple Block Temp entries for the same block, each with different block states and temperatures. The best way to see this is to open the F3 menu and look on the right at what the heat sink's block state is, then add it accordingly. There are examples in the config of how to do this, like the campfires.
