### ISSUE TITLE
[1.20.1] CRASH

### ISSUE THREAD

**Issue by d-rick** [Momo-Studios/Cold-Sweat-Rework-Forge#177]
Empecé a congelarme y el juego de cerro.

dejo el informe de error:
[crash-2023-10-12_10.43.29-server.txt](https://github.com/Momo-Softworks/Cold-Sweat/files/12884452/crash-2023-10-12_10.43.29-server.txt)

**Comment by MikulDev** [comment]
Duplicate of #175
