### ISSUE TITLE
(1.20.1) Chameleon is aligned too far when on players head

### ISSUE THREAD

**Issue by Ciberuss2253** [Momo-Studios/Cold-Sweat-Rework-Forge#178]
When I tame a chameleon and wear it on my head it appears to be very high from me, makes it hard to right click off head.  
![2023-10-12_18 19 37](https://github.com/Momo-Softworks/Cold-Sweat/assets/147777134/2191333c-b1fb-4773-803e-ad4c83944fee)

**Comment by MikulDev** [comment]
The Great Leon is flying away!
Alright, thanks for the report. There are some new rendering quirks I hadn't quire ironed out, but I managed to fix it.
