### ISSUE TITLE
The effect of temperatures on the game world.

### ISSUE THREAD

**Issue by SawFowl** [Momo-Studios/Cold-Sweat-Rework-Forge#179]
I had an idea for the effect of ambient temperature on various mechanics of the game.
For example, lack of growth of wheat, potatoes, carrots, etc. at negative temperatures. And at elevated temperature, depending on its level, there is a decrease in the radius of oration of farmland. The list of crops that will be affected should probably be customizable to make it more compatible with other mods.

**Comment by MikulDev** [comment]
This reminds me of #77. It's unlikely that this will make it into the base mod, but maybe as an addon eventually.
