### ISSUE TITLE
[Translate]I try translate en_us.json into Chinese

### ISSUE THREAD

**Issue by 6371peter** [Momo-Studios/Cold-Sweat-Rework-Forge#18]
[zh_cn.zip](https://github.com/Momo-Studios/Cold-Sweat-Rework-Forge/files/7812791/zh_cn.zip)
I try translate zh_cn.json according to en_us.json.Mod version:ColdSweat-r2.1

**Comment by MikulGamour** [comment]
Thank you! We will put this in the next version.
