### ISSUE TITLE
in various world sckulk biomes you die from freezing in about 7 seconds even tho its above ground

### ISSUE THREAD

**Issue by Thunderrock424242** [Momo-Studios/Cold-Sweat-Rework-Forge#181]
mod link is here https://www.curseforge.com/minecraft/mc-mods/various-world

**Comment by MikulDev** [comment]
You can change the temperature of the biome in the configs if it's not correct.

**Comment by Thunderrock424242** [comment]
The mods biome won't show in the config

**Comment by MikulDev** [comment]
You can add it using the provided format.
