### ISSUE TITLE
[1.20.1] v2.2 Crash on player damage tick

### ISSUE THREAD

**Issue by TomasTobrman** [Momo-Studios/Cold-Sweat-Rework-Forge#183]
Minecraft version: 1.20.1
Mod version: 2.2 & 2.2.1 (Modrinth)
Forge version: 47.2.1 (latest at time of writing)

When the center temperature meter gets to 100 and damage is supposed to be dealt to the player, the client crashes.

crash-log: [https://pastebin.com/vuL4ArP3](https://pastebin.com/vuL4ArP3)

Tested with both 2.2 beta and 2.2.1 release versions from Modrinth by themselves, and in a full modpack. Same results every time.

I have found a closed issue #182 related to this exact problem with a claim of it being fixed. If so, please clarify in which version of the mod is this fixed.

Thank you for your time and any results that might come from this 😊

**Comment by TomasTobrman** [comment]
I now tested it in 1.19.2 and it worked fine there

**Comment by MikulDev** [comment]
This has been fixed in the latest update. Try it with 2.2.2.

**Comment by TomasTobrman** [comment]
Works great, thank you 😊
