### ISSUE TITLE
[INCOMPATIBILITY]

### ISSUE THREAD

**Issue by Willem07** [Momo-Studios/Cold-Sweat-Rework-Forge#184]
Fog does not work correctly with the [alexscaves-1.0.4](https://www.curseforge.com/minecraft/mc-mods/alexs-caves/files/4809682) mod

[ColdSweat-2.2.2](https://www.curseforge.com/minecraft/mc-mods/cold-sweat/files/4805548)
![2023-10-23_17 56 20](https://github.com/Momo-Softworks/Cold-Sweat/assets/51959206/155dc86f-2f61-4670-acdb-c4642789cdac)
![2023-10-23_17 56 35](https://github.com/Momo-Softworks/Cold-Sweat/assets/51959206/6c2386fb-974a-451f-8112-5b8f9e265df6)

[citadel-2.4.5-1.20.1](https://www.curseforge.com/minecraft/mc-mods/citadel/files/4786380)
[1.20.1-forge-47.2.1](https://maven.minecraftforge.net/net/minecraftforge/forge/1.20.1-47.2.1/forge-1.20.1-47.2.1-installer.jar)

**Comment by Twobis** [comment]
unfortunately not fixed but, if you set the Heatstroke fog value to false in the main config it will solve the problem.

**Comment by MikulDev** [comment]
I think disabling the setting is your best bet. Both mods mess with the fog, and I guess Alex's Caves just wins out. Or maybe you can disable it on their end, I don't know.
