### ISSUE TITLE
CRASH 

### ISSUE THREAD

**Issue by d-rick** [Momo-Studios/Cold-Sweat-Rework-Forge#185]
Al momento de configurar ingame el contraste de la GUI el juego se cerro
[crash-2023-10-25_08.31.13-client.txt](https://github.com/Momo-Softworks/Cold-Sweat/files/13166577/crash-2023-10-25_08.31.13-client.txt)

**Comment by MikulDev** [comment]
I can't recreate this issue reliably. Likely a rare issue with the Forge config system
