### ISSUE TITLE
Crash when taking freezing damage

### ISSUE THREAD

**Issue by rohbust** [Momo-Studios/Cold-Sweat-Rework-Forge#186]
[latest.log](https://github.com/Momo-Softworks/Cold-Sweat/files/13221338/latest.log)
When your player takes damage from being cold, the game crashes. something about "player damage ticking being private," im not a coding nerd, the people im in a vc with are tho. LOL

**Comment by MikulDev** [comment]
This was fixed in Cold Sweat 2.2.2

**Comment by Kaiwawa** [comment]
> This was fixed in Cold Sweat 2.2.2

It's for neo forge now?
![image](https://github.com/Momo-Softworks/Cold-Sweat/assets/50468096/6de2552e-8a05-4b2f-9fe2-37a14a918e8a)
