### ISSUE TITLE
[Suggestion] Please add a config option for hiding the menu button

### ISSUE THREAD

**Issue by Foozey** [Momo-Studios/Cold-Sweat-Rework-Forge#19]
This kind of thing can be really annoying if it's not able to be disabled. I think it's good practice to assume that most people are using this mod amongst many others in a modpack. It's a little unusual when 1 mod out of 200 has a menu button for the config, whereas everything else is just settled into the config menu.

**Comment by MikulGamour** [comment]
I kind of understand what you mean, but the point of the config menu is that it's supposed to be accessible in-game to make it easier/more streamlined to use. Putting it in the config menu defeats the purpose of that.

**Comment by Foozey** [comment]
Yep that's fine :), I completely understand why you would want the button. That's why I'm saying the best option is to just add a config option to hide the button for the people that want to hide it. Quark and Create both add menu buttons, and both have a config option to hide it as well. That way everyone is happy :)

**Comment by iMikul** [comment]
Alright, you win. I'll sneak it into next update ;)

**Comment by Foozey** [comment]
Much appreciated :)
