### ISSUE TITLE
Crash report (Triyng to access a private method)

### ISSUE THREAD

**Issue by Kaiwawa** [Momo-Studios/Cold-Sweat-Rework-Forge#190]
Cold Sweat: 2.2.1 and 2.2
Forge Version: 47.2.0, 47.1.43
Minecraft Version: 1.20.1

The game crashed whilst ticking player
Error: java.lang.IllegalAccessError: class com.momosoftworks.coldsweat.common.capability.PlayerTempCap tried to access private method 'net.minecraft.world.damagesource.DamageSource net.minecraft.world.damagesource.DamageSources.m_269079_(net.minecraft.resources.ResourceKey)' (com.momosoftworks.coldsweat.common.capability.PlayerTempCap is in module cold_sweat@2.2.1 of loader 'TRANSFORMER' @e01a26b; net.minecraft.world.damagesource.DamageSources is in module minecraft@1.20.1 of loader 'TRANSFORMER' @e01a26b)

**Comment by Kaiwawa** [comment]
I was playing with Tought as nail and the frozen hearths wasn't working, so I removed and now this error happens.

**Comment by Kaiwawa** [comment]
Was fixed on 2.2.2, but on forge is showing the modloader is NeoForge, but I think that was a mistake. 

**Curse Forge app:**
> To install on CurseForge you have to search the mod and install the last patch and don't by the *Add More Content* on the modpack section.

![image](https://github.com/Momo-Softworks/Cold-Sweat/assets/50468096/4c090c2f-ab27-4f9a-9932-c09e98d31298)

**Comment by Kaiwawa** [comment]
### I will let this issue as open until the devs change the mod loader on Forge to more dumb people **(like me)** with the same issue see what they did wrong ;)



but if they close by themselfs, 🤐

**Comment by MikulDev** [comment]
Cold Sweat actually is on NeoForge, which is cross-compatible with Forge. I will explicitly add Forge as a modloader to avoid confusion in the future.

**Comment by Kaiwawa** [comment]
@MikulDev thank you 😊, I didn't know that neo and forge were compatible, I thought it was a mistake, sorry.
