### ISSUE TITLE
Compatibility with Primal Winter mod

### ISSUE THREAD

**Issue by SEDIIK** [Momo-Studios/Cold-Sweat-Rework-Forge#192]
Hello, I would like to ask you if you would like to make compatibility with the Primal Winter mod? It adds eternal winter and with your mod the temperatures are not correct. 

Thank you in advance for your reply.

**Comment by MikulDev** [comment]
You should be able to adjust the temperature of the overworld to be colder. Take a look at world-settings.toml.
