### ISSUE TITLE
Respectfully What the hell is the Thermolith?!?!?

### ISSUE THREAD

**Issue by KDFireHero** [Momo-Studios/Cold-Sweat-Rework-Forge#194]
i cannot find any explanation on the use or what the thermolith does, even to the point of no one even mentions it.

can someone please explain what it is?

**Comment by Mic1e** [comment]
Found this in the changelog for v2.2 on Curseforge:
```
- Added new block: Thermolith
       - Outputs a redstone signal based on the temperature of the nearby area (from 0 to 15 from minimum to maximum temperature set in the config)
       - Crafted with 3 chameleon molt and 4 terracotta
```

**Comment by MikulDev** [comment]
Thanks for digging through the changelog for me. I've been super busy lately. Just wanted to let you know that I made a typo on the recipe. It's actually 6 terracotta in a door-style formation, and 3 chameleon molt in the remaining 3 slots

**Comment by KDFireHero** [comment]
Thank you.
