### ISSUE TITLE
[1.16.5] Body temperature not resetting after respawning 

### ISSUE THREAD

**Issue by Mic1e** [Momo-Studios/Cold-Sweat-Rework-Forge#195]
Minecraft - 1.16.5
Forge - 36.2.39
Cold Sweat - 2.2

[debug.log](https://github.com/Momo-Softworks/Cold-Sweat/files/13404796/debug.log)

Not sure if this a bug or not but when you die the body temperature remains the same and doesn't reset back to 0. This means that if you die and respawn in an area that's too cold or hot you will get stuck in an infinite loop of dying if you have the grace period disabled or made it short. If this is supposed to happen can we get a config to make it reset to 0 since I would like to make the grace period short or disable it.

Steps to reproduce:
1. Build up your body temp to something above zero.
2. Die and respawn.
3. Body temp is the same as before you died.

Edit: This happens on both singleplayer and multiplayer with and without extra mods.

**Comment by MikulDev** [comment]
Fixed in 2.2.2
