### ISSUE TITLE
[1.20.1] Compat Request - Curios

### ISSUE THREAD

**Issue by AetheriMC** [Momo-Studios/Cold-Sweat-Rework-Forge#197]
Minecraft v1.20.1
Forge v47.2.4

The ability for curio items to provide insulation effects (controlled via the configs) would be extremely beneficial. Our server modpack contains an accessory which grants fire resistance (not the effect, just the result) but adding that item to the existing Coldsweat configs (i.e. insulating armor list) with the appropriate values does not actually provide insulation.

**Comment by MikulDev** [comment]
Great idea! I agree. I will be adding this in the next update coming very soon ;)
