### ISSUE TITLE
Issue with log spam on death

### ISSUE THREAD

**Issue by Maypul** [Momo-Studios/Cold-Sweat-Rework-Forge#199]
MC Version: 1.19.2
Forge: 43.2.21
Cold Sweat: 2.2.2

Once my character dies and stays in death screen, the log gets spammed with errors: https://pastebin.com/7icujmDE
Looks like a conflict with AppleSkin based on log errors.

**Comment by MikulDev** [comment]
I don't really understand how this is related to Cold Sweat. This looks like a Thirst Was Taken issue.

**Comment by Maypul** [comment]
Yes, i mixed the mods in my brain, sorry
