### ISSUE TITLE
Weird "Exception caught during firing event: null" Crash

### ISSUE THREAD

**Issue by Phweeeee** [Momo-Studios/Cold-Sweat-Rework-Forge#20]
This happens frequently and randomly. 

Here's a log.

https://paste.gg/p/anonymous/278f7665987b47a9a9e0d6d4672d65f1

**Comment by MikulGamour** [comment]
Thank you for reporting! We've identified the issue and will roll out a fix next update. Apologies for the crash, it seems to be very rare except in your specific case.
