### ISSUE TITLE
[1.16.5] Llamas don't seem to be regrowing their fur

### ISSUE THREAD

**Issue by Mic1e** [Momo-Studios/Cold-Sweat-Rework-Forge#200]
Minecraft - 1.16.5
Forge - 36.2.39
Cold Sweat - 2.2.2

[debug.log](https://github.com/Momo-Softworks/Cold-Sweat/files/13540130/debug.log)

I have been playing on a server for a couple of weeks now and none of my llamas seem to be regrowing their fur after I shear them. I've also tested this on a single player world with just cold sweat for about 15 minutes and seeing as it should be 20% chance every minute according to the config for them to grow their fur back I feel like something is not working.

**Comment by Mic1e** [comment]
I have also tested setting the config to [300, 0, 1.0], which from my understanding would mean the fur grows back after 15 seconds of shearing a llama but this also didn't seem to work.

**Comment by MikulDev** [comment]
This will be fixed in 2.2.3. Thanks for reporting
