### ISSUE TITLE
suggestion: add a config option to diable and enable heat and cold 

### ISSUE THREAD

**Issue by Thunderrock424242** [Momo-Studios/Cold-Sweat-Rework-Forge#202]
so if you wanted only cold biomes to be cold and not have heat at all there would be a config for that.

**Comment by MikulDev** [comment]
`/attribute <player> cold_sweat:heat_dampening base set 1` should do the trick. It will block all heat from affecting the player.

**Comment by Thunderrock424242** [comment]
> `/attribute <player> cold_sweat:heat_dampening base set 1` should do the trick. It will block all heat from affecting the player.

I am making a modpack that's why I made the suggestion

**Comment by Thunderrock424242** [comment]
Or is that possible to do in the configs?

**Comment by MikulDev** [comment]
You could also set the maximum habitable temperature to some extremely high number. This would make it so that hot biomes appear temperate, and cold biomes would still be cold.

**Comment by MikulDev** [comment]
This should be doable in a modpack with the methods I provided above. I will reopen this issue if it really isn't possible to do this already.
