### ISSUE TITLE
Particle Rendering issues when using Create Mod + Shaders

### ISSUE THREAD

**Issue by ZeroAresIV** [Momo-Studios/Cold-Sweat-Rework-Forge#203]
Particles cause issues when combined with Create Mod and Shaders. All particles render independent from the players view angle, leading to issues where particles become invisible or outright are traced where they shouldn't be. It can be replicated by using Create Mod's Placement assist while having shaders enabled with cold sweat. Removing cold sweat removes the problem, same with using versions below 2.2.3 (1.18.2, Used complementary shaders + Optifine)

**Comment by MikulDev** [comment]
Under what conditions does this occur? I can't seem to replicate this issue using the same setup (Cold Sweat 2.2.4, Optifine H9, Complimentary Unbound r5.1.1, Create 5.1f)

**Comment by ZeroAresIV** [comment]
I found the issue on my own, my gpu was overclocking and was not directly an issue with cold sweat. I apologize for the wasted time.

**Comment by MikulDev** [comment]
I see. That's alright. Glad you found a fix.
