### ISSUE TITLE
Chameleons has a black square under it.

### ISSUE THREAD

**Issue by OwenFails** [Momo-Studios/Cold-Sweat-Rework-Forge#205]
Under the chameleons. there appears to be a void under them, it's on and off and I DO have Optifine. I just wanted to let you know.
![2023-12-30_08 12 54](https://github.com/Momo-Softworks/Cold-Sweat/assets/118086049/b86fab3f-dae5-46c3-b2da-c0866a9f067b)

**Comment by MikulDev** [comment]
What is your version of Cold Sweat/Minecraft/Optifine? I can't seem to recreate this issue

**Comment by OwenFails** [comment]
Forge 1.20.1, Cold Sweat 1.20.1 v2.2.3, Optifine HD U I6

**Comment by MikulDev** [comment]
I got the problem to happen only when "Fast Graphics" was turned on. I wasn't able to verify why this occurs, but Optifine does warn that their custom renderer might conflict with mods in certain scenarios when using this setting.

**Comment by MikulDev** [comment]
I will be closing this issue because the source of the problem was found and there is no way to resolve it to my knowledge. I can reopen if anything new happens.
