### ISSUE TITLE
Heat causing kick.

### ISSUE THREAD

**Issue by Aton1x** [Momo-Studios/Cold-Sweat-Rework-Forge#206]
When on Aternos servers, it kicks me when the heat is at 100. This happens if you are hot or cold. Version 1.20.1. Mods that are used attatched.
[mods.zip](https://github.com/Momo-Softworks/Cold-Sweat/files/13834505/mods.zip)

**Comment by MikulDev** [comment]
Nothing is attached to this issue. I would also like the latest.log so I can see what errors the server is reporting

**Comment by Aton1x** [comment]
https://mclo.gs/1w0tjlQ

**Comment by MikulDev** [comment]
You're using an old version of the mod. This has been fixed in newer versions
