### ISSUE TITLE
Doors are not sealing off spaces

### ISSUE THREAD

**Issue by MockinBirdBud** [Momo-Studios/Cold-Sweat-Rework-Forge#207]
As stated above, doors and hatches don't seal off spaces leading to those spaces leaking heat

**Comment by MikulDev** [comment]
Seems to work for me
![2024-01-04_23 45 35](https://github.com/Momo-Softworks/Cold-Sweat/assets/24680934/dfbc4536-ceb2-4ea0-8b51-3a8c9adeb12b)
![2024-01-04_23 45 44](https://github.com/Momo-Softworks/Cold-Sweat/assets/24680934/3f1fa57a-630a-436a-a32c-d50135efe1bd)
