### ISSUE TITLE
Crashes in server start up

### ISSUE THREAD

**Issue by Perritadead** [Momo-Studios/Cold-Sweat-Rework-Forge#208]
Cold Sweat (cold_sweat) has failed to load correctly
?7java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER

The server just wont load
I'm using forge 47.2.19
Cold sweat 2.2.5

[crash-2024-01-07_09.40.31-fml.txt](https://github.com/Momo-Softworks/Cold-Sweat/files/13853851/crash-2024-01-07_09.40.31-fml.txt)

**Comment by MikulDev** [comment]
This issue is now fixed in 2.2.5.1
