### ISSUE TITLE
Armor Insulation UI isn't showing on armors.

### ISSUE THREAD

**Issue by zhmstr** [Momo-Studios/Cold-Sweat-Rework-Forge#209]
For some reason, Armor Insulation isn't showing on armors.
![2024-01-08_11 47 04](https://github.com/Momo-Softworks/Cold-Sweat/assets/107897693/428fe9ce-8547-4115-874a-a70f423823d5)

It shows on items like Leather, Hoglin Hide the insulation.
![2024-01-08_12 17 57](https://github.com/Momo-Softworks/Cold-Sweat/assets/107897693/8ad7d2b0-10bd-4c33-860f-4af98bd77652)

---

Here is my mod list: https://pastebin.com/vU0tMdsA

Minecraft 1.19.2
Forge 43.3.5
Eclipse Adoptium - jdk-17.0.9.9-hotspot

Setting files:
- world_settings: https://pastebin.com/FXi0wvsg
- client: https://pastebin.com/wZcat9gn
- entity_settings: https://pastebin.com/RHkV0mbK
- main: https://pastebin.com/FKFJ9G10
- item_settings: https://pastebin.com/eVUcsGNN
---

**Comment by MikulDev** [comment]
This is because of Legendary Tooltips' 3D armor rendering setting. Disabling it fixes the issue. If you'd like more info, you can see this bug report on their GitHub, which has been open for several months and remains ignored:
https://github.com/AHilyard/LegendaryTooltips/issues/107

**Comment by zhmstr** [comment]
Oh, I see, thanks for your help.

However, I have another question. Is it possible to make it render like [Quark](https://github.com/VazkiiMods/Quark/blob/master/src/main/java/vazkii/quark/content/client/tooltip/AttributeTooltips.java#L341) mod or other UI mods that add such as additions?

This is because these mods are always rendered in such a way that they are always visible, so the improved tooltips will not prevent them from rendering.

**Comment by MikulDev** [comment]
I think I've found a solution. After looking through their code, I found out how to insert the tooltip directly after the item name, rather than just always inserting it at line 2 regardless of context (which renders behind the item model if Legendary Tooltips is installed). This solution seems to work in Vanilla and Legendary Tooltips as intended.
