### ISSUE TITLE
[Compatibility Bug] Cold Sweat causes Rereskillable "You can't use this item yet" popup to not appear

### ISSUE THREAD

**Issue by Foozey** [Momo-Studios/Cold-Sweat-Rework-Forge#21]
Here is an image of the popup Cold Sweat is preventing from appearing:
https://media.forgecdn.net/attachments/363/576/overlay.png

**Comment by Foozey** [comment]
I've done some more testing, and I can confirm, this is caused by the "Custom Hotbar" setting.

**Comment by MikulDev** [comment]
This isn't something we can solve on our end. If you'd like to see this fixed, you should instead contact the mod author and forward them this message:
**In RenderGameOverlayEvent, the RenderGameOverlayEvent.ElementType.EXPERIENCE pass is reserved for the EXP bar, and is commonly cancelled without much thought when changing things on the hotbar. If you wanna keep the render from being cancelled, use ElementType.ALL instead.**
