### ISSUE TITLE
minor Hearth suggestions

### ISSUE THREAD

**Issue by asdasdasadg** [Momo-Studios/Cold-Sweat-Rework-Forge#213]
what if the hearth's grates were more consistent to blast furnaces. Like this:
![image](https://github.com/Momo-Softworks/Cold-Sweat/assets/84078980/582e4f0a-a923-475b-9d44-e7c2abaebca9)
of course some minor texture tweaks could be made to go along

and also what if the heart's item model was 3d? Like this:
![image](https://github.com/Momo-Softworks/Cold-Sweat/assets/84078980/ac30f29f-2fd6-4a0f-b8fb-858daf572584)

**Comment by MikulDev** [comment]
I understand the point for consistency, but I think I like the extruding grate more. It gives the model a little more depth while not looking too out of place. Flattening it out simplifies the model too much in my opinion. 

As for the item model, it looks decent in the GUI, but too small when scaled to actually fit in the slot. I'll consider it, though.

Luckily, these two things are pretty easy to implement as a resource pack, as you seem to have done. You have my full support if you want to distribute it. Thanks for the feedback :)

**Comment by asdasdasadg** [comment]
> I understand the point for consistency, but I think I like the extruding grate more. It gives the model a little more depth while not looking too out of place. Flattening it out simplifies the model too much in my opinion.
> 
> As for the item model, it looks decent in the GUI, but too small when scaled to actually fit in the slot. I'll consider it, though.
> 
> Luckily, these two things are pretty easy to implement as a resource pack, as you seem to have done. You have my full support if you want to distribute it. Thanks for the feedback :)

It might appear a bit off when scaled down in comparison to the other blocks, but hey, it's your choice on what you choose to do! (love the mod btw)

**Comment by MikulDev** [comment]
I will definitely consider this for next update. Thanks for the feedback (and compliments!)

**Comment by asdasdasadg** [comment]
> I will definitely consider this for next update. Thanks for the feedback (and compliments!)

<3
