### ISSUE TITLE
Suggestion: Add support for automation of the Boiler and Icebox for consistency

### ISSUE THREAD

**Issue by TraipsingShadow** [Momo-Studios/Cold-Sweat-Rework-Forge#214]
Minecraft Version: `1.20.1`
Forge Version: `47.2.6`
Cold Sweat Version: `2.2.5.1`

Hello!

I was looking through the Wiki and was pleasantly surprised to know that the Hearth supported piping in liquids like water and lava. I was about to try it on the Boiler and Icebox but to my dismay, it does not work.

May I suggest that you add the functionality of pipes/automation for the Boiler as well as the Icebox (piping in lava and water respectively)? Would be super neat!

Thank you for making this mod. Having fun with it so far.

**Comment by MikulDev** [comment]
This functionality is absolutely planned, and is actually even underway right now. It will be part of the next update
