### ISSUE TITLE
[Suggestion] Toggle visibility of HUD elements

### ISSUE THREAD

**Issue by dandalous** [Momo-Studios/Cold-Sweat-Rework-Forge#216]
Hey there! I'm suggesting an extra option to ColdSweat config UI to toggle the visibility of each or all UI elements. You can currently just set their position off screen but that feels a bit jank. Or maybe make it a keybind to quickly toggle on and off if needed? Totally not necessary, just a personal preference as I like using my common sense to gauge my surroundings and enjoy the immersion of the hot and cold vignette effects. Would pair well with something like [Auto HUD](https://modrinth.com/mod/autohud)

Incredible mod btw! Absolutely outstanding work. Have you thought about implementing ways of insulating heat sources like lava from the player if there's blocks in-between? I've noticed my heat meter spike when outside a building with lava inside. Or alternate ways of cooling down and heating up an area like hiding under a tree, or the fan blowers of [Create](https://modrinth.com/mod/create)?

(Pictures semi-related)

![2024-01-23_23 16 22](https://github.com/Momo-Softworks/Cold-Sweat/assets/125793933/3f2ba904-2bcb-4d83-9310-7a78f89ba22f)
![2024-01-23_23 10 36](https://github.com/Momo-Softworks/Cold-Sweat/assets/125793933/707330f2-ba26-412d-b990-74eb555bfd0d)
![2024-01-12_19 48 22](https://github.com/Momo-Softworks/Cold-Sweat/assets/125793933/3905e0c9-1bc7-4d92-9313-37850463c77f)
![2024-01-12_19 48 06](https://github.com/Momo-Softworks/Cold-Sweat/assets/125793933/1773206a-f5bb-48ed-8b38-a7b08efaff59)

**Comment by MikulDev** [comment]
Sure, this will be in the next update.
