### ISSUE TITLE
[Suggestion] Using datapack

### ISSUE THREAD

**Issue by acaeaeeda** [Momo-Studios/Cold-Sweat-Rework-Forge#217]
Use datapack to configure The numerical values of items in other mods. 
(like hemp_farbic in immersive engineering)(1.19.2 pls)

**Comment by MikulDev** [comment]
Are the configs not adequate for this? There is a setting very similar to what you're describing in there.

**Comment by Sandriell** [comment]
Datapacks would allow others to create and release mod compats much easier.
