### ISSUE TITLE
Insulation Not Applying to Equipment or Building up from Hearth

### ISSUE THREAD

**Issue by plmsw12** [Momo-Studios/Cold-Sweat-Rework-Forge#219]
Hello, I am playing on a server running the latest version of Cold Sweat, but am having issues with the mod. Namely insulation is not applying to clothing and the hearth is not applying the effect as described. The pack is V21.5 of the Steam Punk Modpack found on curseforge. I was directed to you to ask about this issue, any help would be appreciated.

**Comment by MikulDev** [comment]
Try updating the mod to the latest beta version that was just released and see if the issue persists.
