### ISSUE TITLE
Negative values for dampening attributes prevents tempature change.

### ISSUE THREAD

**Issue by PirateSee** [Momo-Studios/Cold-Sweat-Rework-Forge#220]
In the 2.2.2 changelogs it states that setting a negative value for cold_dampening or heat_dampening would accelerate the rate at which temperature is gained. However, this is not the case.

When applying an attribute modifier causing those attributes to become negative, the core temperature value can no longer move in the corresponding direction, instead starting to retreat back to 0 if temperature was somehow already gained.

Example:
heat_dampening = -0.5
World Temperature is too hot
Core Temperature does not increase
Expected that Core Temperature would increase 1.5x as fast as normal
Core Temperature is still capable of decreasing when exposed to cold

For Cold Sweat version 2.2.5.1 for NeoForge 47.1.79 on Minecraft 1.20.1

**Comment by MikulDev** [comment]
This will be fixed in the next beta release. Thanks for letting me know
