### ISSUE TITLE
[1.16.5] Crashed during server startup 

### ISSUE THREAD

**Issue by taoge407** [Momo-Studios/Cold-Sweat-Rework-Forge#221]
MC Version: 1.16.5
Mod Version: 2.2.5.1
Forge Version: 36.2.39

Log file: https://paste.ubuntu.com/p/zqXYDZ3qwJ/

There's only Cold-Sweat in mods folder.

**Comment by MikulDev** [comment]
I cannot recreate this crash. Testing on a 1.16.5 dedicated server with just Forge and Cold Sweat, it starts fine. Is this the entire log?

**Comment by taoge407** [comment]
I think I've found the problem. I ran the mod on CatServer, which is a third-party forge server core. I suspect there's a conflict between them.

**Comment by MikulDev** [comment]
That would make sense. A modified version of Forge could cause that if that portion of the code was changed (the part that the crash report is alluding to). Are able to confirm it works on a standard Forge server?

**Comment by taoge407** [comment]
> That would make sense. A modified version of Forge could cause that if that portion of the code was changed (the part that the crash report is alluding to). Are able to confirm it works on a standard Forge server?

Yes, it ran fine on an official Forge server with the same Forge version. Thank you.
