### ISSUE TITLE
[SUGGESTION] Thirst Was Taken Compatibility

### ISSUE THREAD

**Issue by Billnotic** [Momo-Studios/Cold-Sweat-Rework-Forge#223]
This was briefly discussed in the discord but I thought I'd leave a submission here just in case.

Thirst Was Taken is a mod that adds a purity level to water bottles as well as a thirst system. Given that the waterskins of this mod are not drinkable (interact button just throws them onto you) it'd be nice if they were made into an actual drinkable item or something similar.

In addition, here are a few ideas for additional features beyond drinkability that could make this mod work more seamlessly with TWT:
- Config for adding beverages that heat up the player, such as farmer's delight teas or fire-themed modded potions.
- Config for adding beverages that cool down the player, such as iced drinks.
- An option to make crouch+interact throw the waterskin onto the player, and the normal interact button drink like a normal beverage.
- Waterskins have a purity level like Thirst Was Taken bottled water.
- Boiling waterskins purifies them.

I understand that thirst mechanics are beyond the scope of this mod for a variety of reasons, but I do think compatibility with the largest non-TAN thirst mod would be amazing for people who want a better alternative to TAN. Plus, Thirst Was Taken has create addon stuff which makes it dope for modpacks, and I really would love if it worked seamlessly with this mod.

**Comment by MikulDev** [comment]
TWT compatibility was actually already deeply in development when this was posted, and you were pretty much right on the money about all of these features. Expect this to be released soon!
