### ISSUE TITLE
[SUGGESTION] Add support for Create's netherite diving suit

### ISSUE THREAD

**Issue by vukkax** [Momo-Studios/Cold-Sweat-Rework-Forge#226]
Making it so that you cant take heat damage when swimming in lava while wearing the full set of netherite diving armor would be nice, I tried playing with configuration values to achieve that effect but that didn't seem to work.

**Comment by MuseOfWorlds** [comment]
It'd also be nice to be able to find something that would extend the amount of time you can stay in the nether without the lamp, which requires you to have it in your offhand to work.

**Comment by MikulDev** [comment]
I can confirm this will be happening in the next update. :)
