### ISSUE TITLE
Broken Hearth Recipe [1.20.1]

### ISSUE THREAD

**Issue by Armandukx** [Momo-Studios/Cold-Sweat-Rework-Forge#227]
In forge 1.20.1 you cannot craft the Hearth because the recipe just doesnt work.
![Screenshot 2024-02-25 170948](https://github.com/Momo-Softworks/Cold-Sweat/assets/104468428/8b7e89d5-2086-4a8b-86b9-13741dcb1191)

**Comment by fuzefurry** [comment]
![image](https://github.com/Momo-Softworks/Cold-Sweat/assets/161005668/618b4e5b-9841-41e6-bb12-344d303c939b)

![image](https://github.com/Momo-Softworks/Cold-Sweat/assets/161005668/b364e7ed-e7c9-4d5f-9094-01ff1778103f)

**Comment by Armandukx** [comment]
![image](https://github.com/Momo-Softworks/Cold-Sweat/assets/104468428/659b4f06-8b5e-44bd-8b6a-ed094c40a193)
![image](https://github.com/Momo-Softworks/Cold-Sweat/assets/104468428/a259c656-8bc4-4180-ab56-93f0fd600ae6)

unable to make the hearth without the smokestack itself.

**Comment by MikulDev** [comment]
You're using an outdated version
