### ISSUE TITLE
[Bug?][Mod Compat] Character dripping wet during snow in winter (Serene Seasons)

### ISSUE THREAD

**Issue by AStrangeMouse** [Momo-Studios/Cold-Sweat-Rework-Forge#228]
**[MC]:** 1.20.1
**[NeoForge]:** 47.1.100
**[Cold Sweat]:** 2.3-b02a
**[Serene Seasons]:** 9.0.0.46

While standing outside in a biome that doesn't normally have snowy weather in base MC, but _does_ during the winter using **Serene Seasons** (for example the Taiga biome), water droplet particles fall from the character while it's snowing, as though it were raining instead. This behavior meanwhile doesn't happen during snowy weather in biomes that do have snowy weather in the base game (Snowy Taiga, etc).

I'm not sure if the reverse is true (no droplets when raining in warm months) or not, but I can check that too if needed!

**Comment by MikulDev** [comment]
Weird, they must use their own weather system. I wasn't aware of this. I'll look into it

**Comment by MikulDev** [comment]
Found a way to fix this. I'll be closing this issue and adding the fix in the next update.
