### ISSUE TITLE
Crashes when opening GUI

### ISSUE THREAD

**Issue by Belselk** [Momo-Studios/Cold-Sweat-Rework-Forge#229]
ColdSweat-2.3-b01a and 02a loads etc. fine, but when I open the GUI, the client crashes.This happens whenever I open the mod's configuration screen and the Hearth GUI. But ice box,boiler and sewing table are not.I am reporting this because the other mod`s and vanilla GUI's are working fine, and I have confirmed the same phenomenon in environments with only this mod.
... By the way your new temperature overlay looks great. I support your development.

_Environment_
- minecraft 1.19.2
- forge 43.3.0 (and 43.2.3)
- ColdSweat-2.3-b01a and b02a

_b01_
[crash-2024-02-25_23.45.42-client.txt](https://github.com/Momo-Softworks/Cold-Sweat/files/14396723/crash-2024-02-25_23.45.42-client.txt)
_b02_
[crash-2024-02-25_23.56.25-client.txt](https://github.com/Momo-Softworks/Cold-Sweat/files/14396749/crash-2024-02-25_23.56.25-client.txt)

**Comment by MikulDev** [comment]
This is a strange issue. I can't get this to trigger on my end, but I'm just going to remove the code that causes this anyway, because it frankly isn't necessary. Expect a fix in the next verison
