### ISSUE TITLE
Hearth crash

### ISSUE THREAD

**Issue by Chubzik1** [Momo-Studios/Cold-Sweat-Rework-Forge#23]
I have a crash because of Hearth (i guess at least). As soon as i leave my home and move out of render distance it crashes but not everytime. I think it happens some time after placing it, maybe a few hours
here is crash report: https://bytebin.lucko.me/fzyNNO1B3X

**Comment by MikulDev** [comment]
I believe this is the same problem as #22. It'll be addressed in an update coming very soon! Apologies for the crash.
