### ISSUE TITLE
Incompatability with two mods / issue with addleathermodifier?

### ISSUE THREAD

**Issue by kunrian** [Momo-Studios/Cold-Sweat-Rework-Forge#231]
[debug(1).log](https://github.com/Momo-Softworks/Cold-Sweat/files/14550529/debug.1.log)

Hello,
It appears that there is an issue with some sort of adding a leather modifier
https://www.curseforge.com/minecraft/mc-mods/hostile-mobs-and-girls
https://github.com/Mechalopa/Hostile-Mobs-and-Girls/issues/31

It does occur with this mod having the issue
HOWEVER
Creatures and beasts also appear to have this issue, although the issue remains with one or the other
https://github.com/bonsaistudi0s/Creatures_And_Beasts-Forge/issues/68

It doesn't like something upon server joining, or single player world loading.
Pastebin to direct join event: https://pastebin.com/K8kknvCW

Attached debug log contains all server loading information, but majority of it(around 120k lines) is enigmatic legacy's loot table debugging

**Comment by MikulDev** [comment]
Will be fixed in the next verison
