### ISSUE TITLE
[Bug][1.19.2] Items don't stack after updating to ColdSweat-2.3-b02b

### ISSUE THREAD

**Issue by kostikyanni** [Momo-Studios/Cold-Sweat-Rework-Forge#232]
Minecraft version 1.19.2
Forge version 43.3.7

After updating from ColdSweat-2.3-b02a to ColdSweat-2.3-b02b, items no longer stack. For example, when collecting gravel, separate stacks of gravel and flint are created in the player inventory.

[latest.log](https://github.com/Momo-Softworks/Cold-Sweat/files/14553301/latest.log)

**Comment by InventedReality** [comment]
Same 
Minecraft version 1.20.1
After updating from ColdSweat-2.3-b02a to ColdSweat-2.3-b02b

**Comment by MikulDev** [comment]
I've found the problem causing this issue. It'll be fixed in the next version. Thanks for the report
