### ISSUE TITLE
Beacon mod Incompatability

### ISSUE THREAD

**Issue by Exell42** [Momo-Studios/Cold-Sweat-Rework-Forge#233]
(1.19.2)
Using this mod along side [CERBON's Better Beacons](https://www.curseforge.com/minecraft/mc-mods/cerbons-better-beacons) interferes with the beacon's UI

what it should look like
![okxrCSJ](https://github.com/Momo-Softworks/Cold-Sweat/assets/32314722/125dce26-56b2-4f33-8e89-9f3b34bb7f9b)
what it looks like with both mods
![Minecraft_ 1 19 2 3_12_2024 9_04_32 PM](https://github.com/Momo-Softworks/Cold-Sweat/assets/32314722/e18a3928-9d0a-4334-9941-66db5cd3587a)

Ideally I would hope for you guys to just add a config option to disable the beacon UI changes since the aforementioned mod allows adding other beacon effects like insulation or grace thanks to its customizability.

**Comment by SiverDX** [comment]
im using both (1.19.2) and it seems fine?

![image](https://github.com/Momo-Softworks/Cold-Sweat/assets/22003703/5a21126a-b3b9-447e-a122-9e7477adffda)

**Comment by Exell42** [comment]
Your right, I don't really know what's going on with my game at this point
![Capture](https://github.com/Momo-Softworks/Cold-Sweat/assets/32314722/d9d0ca59-7ddd-43b4-aac1-a83546d455e0)
I just found that using these mods in tandem all together for some reason makes this happen, I guess I'm just cursed lol.
It's not even consistent either, when I remove a mod from that list the UI goes back to normal but when I get some other mods it just curses me with that screwed up UI. I honestly don't expect for anything at this rate, I just find it funny at this point, and yes I'm coping.

**Comment by MikulDev** [comment]
Sounds like something to do with mod load order. Some different setups can produce different results if mods clash like this. I thought I made sure this wouldn't happen, but I guess I have some more work to do

**Comment by Exell42** [comment]
Just want to come back to say thank you!
