### ISSUE TITLE
(1.20.1) Chameleon Molt unable to be used in the Sewing Table

### ISSUE THREAD

**Issue by MidnightMangled** [Momo-Studios/Cold-Sweat-Rework-Forge#238]
I would guess this is due to a incompatibility to another mod I have but I can't figure out which one.

I have armor, before I added a few mods, that was able to have chameleon molt attached on each piece and now I suddenly can't put the molt on the armor or even into the sewing table.

If I figure out which mod is causing  the issue, I will add to my post with the information on which mod.

A video to show what is happening:
https://github.com/Momo-Softworks/Cold-Sweat/assets/163694242/387de793-b4eb-433c-8b78-7ccdf0734624

**Comment by MikulDev** [comment]
If you've just updated to the latest beta, then you're going to have to add it back or reset your configs. The formatting of them has changed

**Comment by MidnightMangled** [comment]
Yep, that would be the problem.
Everything is working perfectly now.

Thank you.
