### ISSUE TITLE
Create BackTank loses insulation after being placed

### ISSUE THREAD

**Issue by ThorstenKuhn** [Momo-Studios/Cold-Sweat-Rework-Forge#239]
Hi, 
i am in 1.19.2 SteamPunk [LPS] Modpack with Cold Sweat 2.2.5.1 and Create 0.5.1.f
If you put insulation with the sewing table onto the Backtank and then place and pickup the Backtank to fill it with air, the insulation is gone from the item.
Is this an issue with Cold Sweat or Create? I will put the issue to Create if that is necessary

Greetings
TAK

**Comment by MikulDev** [comment]
This would probably be up to Create to do. It's usually up to the developer to port over the relevant data when placing a block, and Cold Sweat uses a very standard way of storing data (capabilities), which would ideally be considered when the block is placed.
