### ISSUE TITLE
Origins integration

### ISSUE THREAD

**Issue by snowinmars** [Momo-Studios/Cold-Sweat-Rework-Forge#240]
[Origins](https://www.curseforge.com/minecraft/mc-mods/origins-forge) is a mod, that adds several premanent buffs and defubs to the player. It can be minor changes - like extra inventory, - but it can be pretty big - like Blazeborn spawns in Nether. So, I'll take the Blazeborn origin as an example. It's nether creature, and it does not take fire damage in any case.

But ColdSweat does not know anything about that, so Blazobord dies in Nether because it's too hot) It does not make sence.

The suggestion is to read player's NBT in [TempEffectClient](https://github.com/Momo-Softworks/Cold-Sweat/blob/1.20.1-FG/src/main/java/com/momosoftworks/coldsweat/client/event/TempEffectsClient.java#L120). I asked for help in Origins dev chat and [got an answer](https://discord.com/channels/734127708488859831/838871885709705237/1217763572852195449), that it is possible.

Is it a good idea to add the compatibility between the mods? Does the answer in chat seems a viable solution?

**Comment by MikulDev** [comment]
Hey, just wanted to update you on this and say that I'm actually working on adding official origins integration in this way. I'm planning on releasing it soon, I've just had to iron down some of the new systems that it depends on first

**Comment by MikulDev** [comment]
Finally completed!
