### ISSUE TITLE
Create Gear Gives infinte insulatiion even when the tank is empty

### ISSUE THREAD

**Issue by gluzzie** [Momo-Studios/Cold-Sweat-Rework-Forge#241]
When u craft the create gear or nephrite leggings it shows that u get infinite heat resistance so I can just wear the netherite leggings and be safe from the nether 
![image](https://github.com/Momo-Softworks/Cold-Sweat/assets/110564511/4e7eb5b3-3c39-4449-a7e4-f49260280c26)
![image](https://github.com/Momo-Softworks/Cold-Sweat/assets/110564511/0762c31f-9aa3-414f-9478-2b34298aba03)
I am completely safe

**Comment by MikulDev** [comment]
I'm not quite sure how this is happening to you. I can't recreate this issue at all. What version of Minecraft and Cold Sweat are you on?

**Comment by gluzzie** [comment]
I'm playing on the newest beta version of the mod in 1.20 and all I did was update the mod but when u delete the old config it fixes it 

idk what going on but it's not creating the glitch anymore lol
