### ISSUE TITLE
New Insulation

### ISSUE THREAD

**Issue by MataraOkina** [Momo-Studios/Cold-Sweat-Rework-Forge#243]
Hello author.
May I ask if it is possible to add new functions of insulation materials? That is, to increase or decrease the minimum and maximum livable temperatures of the wearer, or to offset a certain value of cold or hot temperatures, rather than modifying the player's temperature change rate.
For example, my original minimum livable temperature was -5 ℃, but even if I wore leather gear and stayed in an environment of -10 ℃, my body temperature still dropped. But with this feature, leather armor reduces the minimum livable temperature by 10 ℃, allowing me to no longer experience temperature changes in an environment of -10 ℃ unless I enter an environment of -26 ℃.
I also hope that this feature can be freely turned on or off, as well as edited.
I believe this will make the mod provide a more interesting experience.

**Comment by MikulDev** [comment]
This is a good idea. I'm working on a more advanced way of adding insulation, and this would make for a great feature. I'll add it to the next update

**Comment by MataraOkina** [comment]
Thank you for your approval. Wishing you a happy life.
