### ISSUE TITLE
Client crsshes on server with sawing table

### ISSUE THREAD

**Issue by YoMo3996** [Momo-Studios/Cold-Sweat-Rework-Forge#245]
Thank you for creating this fantastic mod. 
Unfortunately, when using the sewing table during multiplayer, the client crashes. 
I will attach the error log.
The crash occurs when trying to retrieve equipment with insulation material attached by hovering the mouse over the item.

MOD
ColdSweat-2.3-b02c.jar
create-1.20.1-0.5.1.f.jar

[crash-2024-03-24_00.18.05-client.txt](https://github.com/Momo-Softworks/Cold-Sweat/files/14734876/crash-2024-03-24_00.18.05-client.txt)

**Comment by MikulDev** [comment]
Updating to the latest version should solve the issue

**Comment by YoMo3996** [comment]
thank you for quick response.
I updated to the latest version.
but same issue occured.
I attach the error log.
[crash-2024-03-25_23.17.16-client.txt](https://github.com/Momo-Softworks/Cold-Sweat/files/14744817/crash-2024-03-25_23.17.16-client.txt)

**Comment by YoMo3996** [comment]
and I attach a screen shot before crash.
![screen shot](https://github.com/Momo-Softworks/Cold-Sweat/assets/164730825/e45acacc-fc23-4be2-ae5c-6c98c2ba35dd)

**Comment by YoMo3996** [comment]
Solved with ColdSweat-2.3-b02e.jar.
Thank you so much!
