### ISSUE TITLE
Clinet crashes on a server

### ISSUE THREAD

**Issue by gluzzie** [Momo-Studios/Cold-Sweat-Rework-Forge#246]
whenever a client hovers over the create netherite gear they crash (not the server, just the client)

**Comment by MikulDev** [comment]
Same issue as #245. Updating to the latest version should solve the issue

**Comment by gluzzie** [comment]
im also on the newest version :(

**Comment by MikulDev** [comment]
This should have been fixed in the latest beta. Try that and see if it's resolved
