### ISSUE TITLE
Can't sleep even when temperature is comfortable in version 2.3-b02d

### ISSUE THREAD

**Issue by kostikyanni** [Momo-Studios/Cold-Sweat-Rework-Forge#247]
Minecraft version 1.19.2
Forge version 43.3.7
Cold Sweat version 2.3-b02d

![2024-03-25_20 19 46](https://github.com/Momo-Softworks/Cold-Sweat/assets/54391589/4e33bb5f-c57e-43ac-ae70-a9512a06c4e3)

**Comment by HockeyZman2000** [comment]
Same issue here, always either sweltering or freezing.
Minecraft 1.20.1
Forge 47.2.21
Cold Sweat 2.3-b02d

**Comment by MikulDev** [comment]
This issue was fixed in the latest update yesterday.
