### ISSUE TITLE
Crazy low tempeture

### ISSUE THREAD

**Issue by gluzzie** [Momo-Studios/Cold-Sweat-Rework-Forge#249]
Whenever i play on newest version my temperature is really low and will not move when near a heat source

![image](https://github.com/Momo-Softworks/Cold-Sweat/assets/110564511/30f451b5-28ee-4fc3-a3a7-4a84d57c889a)

**Comment by Klouver-github** [comment]
I am also having same issues 
![2024-03-29_05 29 48](https://github.com/Momo-Softworks/Cold-Sweat/assets/62172911/e61a79aa-3064-4065-9043-cfd468b288cd)

**Comment by MikulDev** [comment]
I'm aware of the issue. It seems like a mod incompatibility, so if anyone could go through their mods list and see which one it is, that would be very helpful. I can't replicate this issue myself

**Comment by gluzzie** [comment]
I FOUND THE MOD!!!
After searching through my mod pack and figured it was the "Attruibute fix" mod
https://www.curseforge.com/minecraft/mc-mods/attributefix
I'm on the latest version of 1.20.1

**Comment by MikulDev** [comment]
A true hero. I'll start looking into fixing the compatibility

**Comment by gluzzie** [comment]
TAHNK U SO MUCH!!!
i love this mod so much and the update is so nice

**Comment by SiverDX** [comment]
did you try deleting your attribute fix config?

iirc it doesn't modify modded attributes (it will just contain their default caps) but if you had an old version of cold sweat it might contain some old values which could cause issues

**Comment by MikulDev** [comment]
Some versions of the mod actually do change the values if it is an invalid number (+-infinity, NaN) to be a "rational" number instead. Cold Sweat uses NaN to mark attribute values as "unset", because when you set an attribute value it overrides the default behavior for that property (i.e. setting your world temperature to 75 will make it 75 permanently and won't change until you clear the attribute)

**Comment by gluzzie** [comment]
It fixes when i delate the config. Thank you so much!!

**Comment by MikulDev** [comment]
I'm going to mark this as fixed and close the issue, given we've found a solution. It seems like the resolution is to update the mod and delete the configs. Thanks to everyone who helped crack this case.
