### ISSUE TITLE
Armor texture

### ISSUE THREAD

**Issue by Djay-Egg** [Momo-Studios/Cold-Sweat-Rework-Forge#252]
It's weird because the armor's texture is all squished up and i look almost naked ingame

**Comment by MikulDev** [comment]
I'd bet you're using Optifine. Newer versions of Optifine are a buggy mess. I suggest moving to a different optimization mod if you can. There's a handy list of such mods here:
https://github.com/TheUsefulLists/UsefulMods/blob/main/Performance/Performance120.md#forge-120x
