### ISSUE TITLE
Chameleon randomly vanished after I walked into my base with it on my head.

### ISSUE THREAD

**Issue by Barerock** [Momo-Studios/Cold-Sweat-Rework-Forge#255]
I was just walkin around and it vanished into thin air. It doesn't appear to be anywhere, I've looked around with spectator. I also couldn't figure out how to take it off. I'm using first person model, which may affect this? And also Carry On.

**Comment by Barerock** [comment]
Bro it's in my boat over 60 blocks away wtf?

**Comment by Barerock** [comment]
Still can't take it off.

**Comment by MikulDev** [comment]
I'm not sure what could have caused this. It sound like there was a desync between the server and client, where visually it looked like you picked it up but in reality you didn't and it's still in the boat. Does this happen consistently?

**Comment by Barerock** [comment]
No, it's been stable since. And I figured out double shift, I forgot some mods use that instead of shift + right click.

**Comment by MikulDev** [comment]
Shift+Right-Click actually makes a lot more sense than double-shift. I might just make it that instead. Anyway, glad it never happened again
