### ISSUE TITLE
the icebox is not working

### ISSUE THREAD

**Issue by Vladigattio** [Momo-Studios/Cold-Sweat-Rework-Forge#256]
i'm on version 1.20.1,and the boiler is working just fine,as for the icebox?
not really,i can't put any itme inside of it,so cooling a waterskin isn't really an option,is there any way to fix this?

**Comment by Vladigattio** [comment]
> i'm on version 1.20.1,and the boiler is working just fine,as for the icebox? not really,i can't put any itme inside of it,so cooling a waterskin isn't really an option,is there any way to fix this?

i just pressed on the icebox accidentally with an oak log and,,,it's working??
i can fule the icebox with the items from the boiler,is there any way to fix this??

**Comment by Vladigattio** [comment]
![image](https://github.com/Momo-Softworks/Cold-Sweat/assets/80574145/3fd03f46-fb1b-4cd1-88fd-76762928a6dd)

**Comment by iobiarg** [comment]
Having same bug, nothing cold works but coal and logs do... (1.19.2)

**Comment by MikulDev** [comment]
Thanks for letting me know. This will be fixed for the next version
