### ISSUE TITLE
[Bug] [1.20.1]: Consumable Tooltips

### ISSUE THREAD

**Issue by Sandriell** [Momo-Studios/Cold-Sweat-Rework-Forge#258]
As shown in the screenshot, consumable items are not displaying their tooltip correctly.

![2024-04-01_19 36 54](https://github.com/Momo-Softworks/Cold-Sweat/assets/10704907/e1931a9c-f6ff-4ee1-b1ed-f7eccc821e0f)

**Forge**: 47.2.17
**Mod**: ColdSweat-2.3-b02e

**Comment by MikulDev** [comment]
Thanks for reporting this. I'll make sure it's fixed for the next release
