### ISSUE TITLE
Crash related to hearth - java.lang.NullPointerException: Ticking block entity

### ISSUE THREAD

**Issue by TheVillain-Inc** [Momo-Studios/Cold-Sweat-Rework-Forge#26]
Ahoy! 
Had a crash, mid sized mod pack. Details as follows:

Leaving home, which has a hearth, few chunks away. Have done this before, but this was on a horse.

Latest version 2.1.1 of Cold Sweat 

MC 1.16.5
Forge 36.2.2
Magnesium 1.5

[crash-2022-01-26_04.04.14-client.txt](https://github.com/Momo-Studios/Cold-Sweat-Rework-Forge/files/7939346/crash-2022-01-26_04.04.14-client.txt)

Edit - managed to forget to add crash report. 90% sure this is the right one.

**Comment by TheVillain-Inc** [comment]
Happened again when re-approaching hearth. Unfortunately taken the save file down with it as unable to load back in.

Cannot reproduce in a creative environment just placing
 it down, zooming off, zooming back. 


[crash-2022-01-26_06.17.30-client.txt](https://github.com/Momo-Studios/Cold-Sweat-Rework-Forge/files/7939338/crash-2022-01-26_06.17.30-client.txt)

**Comment by MikulDev** [comment]
An update addressing this problem will be coming out tomorrow. Apologies for the crash!

**Comment by TheVillain-Inc** [comment]
Aaaall good, its an amazing mod, so happy to 'help' QA it 
:)
