### ISSUE TITLE
[1.19.2] Sewing Table Not Working

### ISSUE THREAD

**Issue by kostikyanni** [Momo-Studios/Cold-Sweat-Rework-Forge#261]
Minecraft version 1.19.2
Forge version 43.3.7
ColdSweat veresion 2.3-b02e

Armor slot won't accept armor. Insulation slot takes armor.

![2024-04-05_22 27 31](https://github.com/Momo-Softworks/Cold-Sweat/assets/54391589/715f81fb-f416-4b81-969f-b713d32992bc)

**Comment by MikulDev** [comment]
I'm pretty sure this is working as intended. Leather chestplate is classified as an insulation item, so it goes in the insulation slot, and furthermore, insulation items can't themselves be insulated. Hopefully this clears up the confusion.

**Comment by kostikyanni** [comment]
Ah ok. I think I was recalling how it worked in a prior version and thought it was a bug.
