### ISSUE TITLE
(1.20.1) Client crashing on server with JEI + Cold Sweat when adding insulation to armor & viewing armors with insulation in JEI menu

### ISSUE THREAD

**Issue by madd4punk** [Momo-Studios/Cold-Sweat-Rework-Forge#263]
I'm currently hosting a server for a group of friends and we encountered an issue pretty much immediately where we couldn't see the graphic for insulation on armor pieces, and we had to rely on NBT data to tell if it was insulated or not. Attempting to apply insulation to armor using the Sewing Table will cause the client to crash. Similarly, viewing an armor piece that already has built-in insulation in [JEI](https://github.com/mezz/JustEnoughItems)'s menu, such as [Create](https://github.com/Creators-of-Create/Create)'s Netherite Diving Helmet, will also crash the client. 

Neither of these issues were able to be replicated in singleplayer with all of the same mods enabled; they effect the user exclusively in multiplayer.

Crash Log 1 (After applying Chameleon Molt to an armor piece): 
[crash-2024-04-08_18.40.07-client.txt](https://github.com/Momo-Softworks/Cold-Sweat/files/14912232/crash-2024-04-08_18.40.07-client.txt)

Crash Log 2 (After viewing Netherite Diving Helmet in the JEI menu): 
[crash-2024-04-08_20.07.09-client.txt](https://github.com/Momo-Softworks/Cold-Sweat/files/14912242/crash-2024-04-08_20.07.09-client.txt)

**Comment by MikulDev** [comment]
Updating to the latest version will fix this

**Comment by madd4punk** [comment]
It does in fact no longer crash, thank you so much! It's worth noting that the insulation UI does still disappear when the armor is equipped, but can be viewed just fine when its not. This isn't an issue that impedes gameplay, though, it's all visual. Just figured I'd let you know!
