### ISSUE TITLE
(1.20.1)The soul lamp won't recharge

### ISSUE THREAD

**Issue by Vladigattio** [Momo-Studios/Cold-Sweat-Rework-Forge#264]
the soul laps works just fine,untile it gets to 0/64
then it becomes useless,if you feed it soul sprouts it eats them up but doesn't recharge power.

![2024-04-12_17 59 37](https://github.com/Momo-Softworks/Cold-Sweat/assets/80574145/1a08de0e-97a6-499d-b41d-68dbe89b9a9d)
![2024-04-12_17 59 40](https://github.com/Momo-Softworks/Cold-Sweat/assets/80574145/436560dd-e07f-4c90-acfe-952664040fd4)
![2024-04-12_17 59 43](https://github.com/Momo-Softworks/Cold-Sweat/assets/80574145/f73fb189-04d0-401f-85e6-7e33e690bd30)
![2024-04-12_17 59 45](https://github.com/Momo-Softworks/Cold-Sweat/assets/80574145/eced1e14-7113-429d-9296-2f69eb010db4)

**Comment by MikulDev** [comment]
This was already fixed in the latest version

**Comment by Vladigattio** [comment]
i see,thanks i'll install it

**Comment by MikulDev** [comment]
No problem
