### ISSUE TITLE
(1.20.1) the new coldsweat version seems to be incompatible with "kiwi" 

### ISSUE THREAD

**Issue by Vladigattio** [Momo-Studios/Cold-Sweat-Rework-Forge#265]
i can load into a world just fine,but whenever i open my inventory,the game crashes

it works just fine in a server tough

the crash-reports tell me that coldsweat is at fault but idk,si i'm just gonna leve the post here,if you need me to show you anything then i'm always free

here's the latest crash report: 
[crash-2024-04-14_08.50.11-client.txt](https://github.com/Momo-Softworks/Cold-Sweat/files/14969748/crash-2024-04-14_08.50.11-client.txt)

**Comment by MikulDev** [comment]
This issue will be fixed in the next release
