### ISSUE TITLE
[Feature Request] Auto Hud integration

### ISSUE THREAD

**Issue by ClockworkCorvus** [Momo-Studios/Cold-Sweat-Rework-Forge#266]
Simply making it so the hud elements will slide out of view along with the rest of the hud when [Auto Hud](https://modrinth.com/mod/autohud) is installed.

**Comment by MikulDev** [comment]
I'm not really sure how to add integration for their mod. They don't really have anything that lets you add your own HUD elements to their system. I'd probably be forced to make custom mixins or make my own system for HUD element fading. 

The developer should probably work on making their system more extensible so 3rd party developers can add their stuff to it more easily. For now, I can't really see myself putting in the effort to do this, unfortunately
