### ISSUE TITLE
NBT Data crashing

### ISSUE THREAD

**Issue by DillyTheDillster** [Momo-Studios/Cold-Sweat-Rework-Forge#267]
[
[crash-2024-04-15_04.10.18-client.txt](https://github.com/Momo-Softworks/Cold-Sweat/files/14976224/crash-2024-04-15_04.10.18-client.txt)
](url)

NBT data from F3 + H crashes clients in the latest version of cold sweat, this did not happen in the previous version although the previous version did not allow for insulation to work to begin with

**Comment by MikulDev** [comment]
This will be fixed in the latest version. Thanks for the info
