### ISSUE TITLE
Chameleon ???

### ISSUE THREAD

**Issue by Boogy-Mobster** [Momo-Studios/Cold-Sweat-Rework-Forge#268]
I am playing this mod tied into the Deceased craft Mod pack through Curseforge. I am heavily struggling because I cannot find a chameleon or goats within this mod. There is almost no information on chameleons out there nor in the game achievements / quests / GUI. Can someone see if there is an issue with it inside the Deceased craft Mod pack or some specific biomes that they can be found in?

**Comment by DillyTheDillster** [comment]
Hello, not the creator here but ive found them in jungle biomes in the pack im playing, we dont have the deceased mod pack but id recommend checking there!

**Comment by MikulDev** [comment]
There is plenty of information about them on the dedicated wiki that's right here on the GitHub page:
https://github.com/Momo-Softworks/Cold-Sweat/wiki/Chameleon
