### ISSUE TITLE
Accidental Hatting.

### ISSUE THREAD

**Issue by McKitten** [Momo-Studios/Cold-Sweat-Rework-Forge#271]
So I accidentally picked the chameleon up but cant get it down now.
Is there a key bind I am not seeing in control?
It isn't showing up as a curio either.

Please help and maybe make the answer more obvious on the wiki.

**Comment by MikulDev** [comment]
It's in the Taming section in the chameleon's wiki page. It's the bolded text
![Screenshot_20240424-083603](https://github.com/Momo-Softworks/Cold-Sweat/assets/24680934/a8484881-cac5-4020-b10d-ed3203987382)
