### ISSUE TITLE
[Suggestion] Nerf cooling armor in hot environment and vice versa

### ISSUE THREAD

**Issue by The-Goat-HUN** [Momo-Studios/Cold-Sweat-Rework-Forge#272]
Good day/evening!
Basically, when standing in a desert, you won't get any hotter than you already are if you wear armor that protects against cold. This should probably change, to encourage players to switch up their armors more often than just letting them wear the fur armor, for example, in an arid and hot environment.
This could be a config option too.

**Comment by MikulDev** [comment]
I'm not sure what setup you're using, but I can't recreate this issue in 1.20 on the latest version. What are you doing to make this happen?

**Comment by The-Goat-HUN** [comment]
Sorry, but I don't really understand what you are trying to say.
This isn't an issue, but a suggestion.
Is my suggested feature already in the mod and doesn't work for me, but does for you?

**Comment by MikulDev** [comment]
I'm saying that cold insulation does not protect you against the heat of the desert. If it does, then that would be a bug. I can't replicate this behavior in my own testing, which is why I asked if there is something specific you have to do to make fur armor have this effect.

**Comment by The-Goat-HUN** [comment]
Oh, there's no bug. It doesn't have this effect,
I was suggesting that cold insulation, in a hot area, should make the player even hotter.
And heat insulation, in a cold area, even colder.

**Comment by MikulDev** [comment]
Ok, I get it now. I misunderstood what you meant by
> when standing in a desert, you won't get any hotter than you already are.

I thought you meant your body temperature was not increasing.

If you want this effect, you can configure the armor (and cold insulation items) to have negative heat insulation, which would make you heat up faster in hot environments

**Comment by The-Goat-HUN** [comment]
Oh, I didn't know that was a thing. Sorry.
Thank you very much!

**Comment by MikulDev** [comment]
No problem :)
