### ISSUE TITLE
[1.20.1] Crash ColdSweat-2.3-b03a.jar 

### ISSUE THREAD

**Issue by Stiles52** [Momo-Studios/Cold-Sweat-Rework-Forge#274]
[crash-2024-04-26_02.30.21-client.txt](https://github.com/Momo-Softworks/Cold-Sweat/files/15123605/crash-2024-04-26_02.30.21-client.txt)

**Comment by sharlin073** [comment]
Similar issue occured for 1.19.2

**Comment by sharlin073** [comment]
similar issue happening for 1.19.2

**Comment by MikulDev** [comment]
This will be fixed in 2.3-b03b
