### ISSUE TITLE
[bug] Special Minecart Behaviour 1.20.1

### ISSUE THREAD

**Issue by miragliotta** [Momo-Studios/Cold-Sweat-Rework-Forge#278]
Special minecarts do not stay as one item when breaking by hand, or by breaking through other means, such as cactus or lava cauldron.

To recreate: In 1.20.1 have Cold Sweat enabled. Run special (hopper, chest, furnace, etc.) minecart into block to break it or break by hand.
Expected behaviour: minecart breaks and drops one item, staying as a special minecart.
Actual behaviour: minecart breaks and drops itself along with special minecart item (hopper, chest, etc.)

imgur gif of the bug

https://imgur.com/a/Zqx8ghY

**Comment by MikulDev** [comment]
I didn't realize that the dropping behavior of minecarts has changed since 1.18. I'll fix how the mod modifies minecarts so it doesn't interfere with this as much
