### ISSUE TITLE
[Crash] - [2.3-b03b] - Changing units to celsius in GUI and pressing 'Done' crashes the game

### ISSUE THREAD

**Issue by mortuusars** [Momo-Studios/Cold-Sweat-Rework-Forge#279]
[crash-2024-05-04_21.36.19-client.txt](https://github.com/Momo-Softworks/Cold-Sweat/files/15210630/crash-2024-05-04_21.36.19-client.txt)

Setting celsius trought config file seem to work fine.

**Comment by MikulDev** [comment]
From my testing, this actually happens when you edit any setting in the config menu. It's an oversight in how the config settings are saved. This will be fixed in the next version
