### ISSUE TITLE
Multiplayer Sync issues / General concerns

### ISSUE THREAD

**Issue by Inari-Whitebear** [Momo-Studios/Cold-Sweat-Rework-Forge#28]
I was playing MP and the bars on the Hearth seem odd. What is the left bar supposed to be? It always seemed to stay at the same height (and different heights between the person I play with and me). Even when the hearth was already off.

Further, there seemed to be an odd thing where for some reason my body temperature seemed oddly linked to theirs. When they were in an odd area I would heat up too, but the other way around for some reason.

The balancing of temperature also feels a little off. Some things that feel like they should be super harmful don't appear to be. We are in a snowy biome, it gets very cold at night. Despite that, swimming in the icey water didn't freeze you all that much more.

**Comment by MikulDev** [comment]
These are some very strange bugs that we've never seen before. Are you using any other mods? The things you're talking about have been in place for quite some time, and we've neither seen it in our extensive multiplayer testing, nor heard of it from anyone else.

The left bar in the Hearth is its hot fuel. It needs hot fuel in cold places or cold fuel in hot places in order for it to insulate the area.

We're working on rebalancing water to have a more dynamic effect on the player, instead of just subtracting a static 10 F/6 C from the ambient temperature. Thanks for the suggestion.

**Comment by Inari-Whitebear** [comment]
Yeah, I have zero idea what would cause the weird temperature linking haha. Especially since I didn't run the server via LAN or such, it runs dedicated.

Yeah, was using other mods too. I basically stuck it into the "Create: Above and Beyond" modpack

Oh, another thing I had noticed: water skins would only heat up to 27 C in the boiler? (which is 100 F when turned to F, so thought maybe that's an odd oversight, but no idea)

**Comment by MikulDev** [comment]
I fixed the Waterskin thing. They were just using the wrong formula to convert to Celsius so their measurements were off.

**Comment by Sgale952** [comment]
I have also encountered this problem.
My friend and I have a house on the plain. It's never cold there. But one day, when I went on an expedition and stayed at night in AFK in the tundra, I froze to death and my friend (who was in the house on the plain) also died of cold.

I also often dig mines while my friend is busy cooking at home. At the moment when I approach the lava, my friend and I have a fever (as if it is synchronized between us).

There was a case when a third person came to the server, but for some reason the temperature was not synchronized with him  (when I was near the lava, only a friend, the cook, suffered).

[Mods](https://disk.yandex.ru/d/NXF8y5Srnd2Pkg)
_The server is on the LoliServer core
ColdSweat - r2.1.2
Forge-1.16.5-36.2.26
Java - jdk-11.0.10_

**Comment by MikulDev** [comment]
In an unreleased build, we've confirmed that this issue has been resolved. Look forward to seeing it fixed in 2.1.3!

**Comment by MikulDev** [comment]
After some more testing, we've found that Better Weather can cause this issue. If you have it in your modpack, I'd suggest testing to see if removing it solves the issue (if you're still having it)

**Comment by chubbymomo** [comment]
We have fixed the incompatibility, the player syncing issue should no longer happen.
