### ISSUE TITLE
temperature bug

### ISSUE THREAD

**Issue by DnsGnmm** [Momo-Studios/Cold-Sweat-Rework-Forge#280]
1.19.2 2.3-b03b
The bug is happening on my server. The negative temperature accumulates endlessly, 
after I updated the mod to the latest version.
![image2](https://github.com/Momo-Softworks/Cold-Sweat/assets/123404778/fe3d7bf7-7c1b-4a01-aa37-b48578f1125a)
![image](https://github.com/Momo-Softworks/Cold-Sweat/assets/123404778/5366a906-8f2f-4d7c-aae2-a3de7fa87aef)

**Comment by Zanklev** [comment]
The dev found the source of the issue and is working on a fix, they said it'll be out in the next version. (Hopefully asap lol)

**Comment by MikulDev** [comment]
Yup, this will be fixed very soon
