### ISSUE TITLE
Issue with Create mod attributes filter UI opening and closing instantly.

### ISSUE THREAD

**Issue by lolachilada** [Momo-Studios/Cold-Sweat-Rework-Forge#281]
Hi,
I've recently added Cold Sweat mod and I've also noticed that the Attribute filter UI from the Create mod has stopped working (the regular filter UI still works fine).  Some people been having the same problem with Creates' Attribute filter, however searching for what is causing the conflict has been inconclusive.  The only reason I'm inquiring with you about it is because the coincidence of adding Cold Sweat to our server and the following link to the issue describing it. 

https://github.com/Creators-of-Create/Create/issues/6444

Thanks for looking into it.

**Comment by Zanklev** [comment]
Not a dev, but this was fixed in ColdSweat-2.3-b03b. What version are you on?

**Comment by lolachilada** [comment]
Hi,
I just updated from 2.3-b03a and noticed it works fine now.  Thanks for quick reply.

(it is always a pain when you are trying to keep convincing ppl on private server to update some mods, but it is crucial in most cases)

**Comment by Zanklev** [comment]
Nice, you can probably just close this issue page since it's no longer a problem. (Again, not a dev so I can't)
