### ISSUE TITLE
The game crashes when I go to inventory or configure something in the config 

### ISSUE THREAD

**Issue by FilipKompaniets3** [Momo-Studios/Cold-Sweat-Rework-Forge#283]
In the latest mod version, minecraft still crashes for me, if I configure something in the config, when I play on the mod assembly, when I enter the inventory, minecraft crashes and the mod not enough crashes blames cold sweat for this.

Here is the crash report: https://bytebin.lucko.me/sXtUxDAGvo

**Comment by MikulDev** [comment]
I see, I'll get this fixed by next version. Thanks for the info

**Comment by FilipKompaniets3** [comment]
> Я бачу, я виправлю це до наступної версії. Дякую за інформацію

okey:)
