### ISSUE TITLE
Temperatura en estructuras no concuerda con el bioma en el que se encuentra.

### ISSUE THREAD

**Issue by d-rick** [Momo-Studios/Cold-Sweat-Rework-Forge#284]
Versión del mod:  **ColdSweat-2.3-b03c**
Versión minecraft: **1.20.1**
Versión Forge: **47.2.0**

Por ejemplo en el bioma de sabana es cálido de manera normal [IMAGEN 1], pero al entrar en la aldea de sabana la temperatura baja muy rápido y puede matarte por frio. [IMAGEN 2]

Esto ocurre en cualquier bioma las estructuras tienen su propia temperatura independiente del bioma he independiente de la estructura que sea.

1. **IMAGEN 1**

![2024-05-08_23 37 12](https://github.com/Momo-Softworks/Cold-Sweat/assets/83624925/ba7aa08e-857a-432e-9b33-d7026400d280)

2. **IMAGEN 2**

![2024-05-08_23 41 42](https://github.com/Momo-Softworks/Cold-Sweat/assets/83624925/edf83acf-32f4-41f9-bc61-10d9e6247d07)

**Comment by MikulDev** [comment]
Thanks for the report; I was able to fix the issue. This will be fixed in the next update
