### ISSUE TITLE
Body temperature does not work after death on multiplayer.

### ISSUE THREAD

**Issue by Rupla3130** [Momo-Studios/Cold-Sweat-Rework-Forge#29]
Im sorry for my poor English. Because Im japanese.
I use this mod on my mohist server. But once the player die, the player's temperature does not change. Can i fix this problem?

**Comment by MikulDev** [comment]
There is a grace period after death that prevents temperature-related damage for a short time. It still allows temperature to change, though, so I don't fully understand why you're having this issue. What version of Cold Sweat are you using?

**Comment by Rupla3130** [comment]
Im using "ColdSweat-r2.1.2.jar".
When i relogin, the temperature will change. 

https://user-images.githubusercontent.com/98983677/153368778-44390d3d-bef0-49d1-9d87-d6e7b8dbcfba.mp4
![mods1](https://user-images.githubusercontent.com/98983677/153368835-d82ea2fd-f7e8-41db-83b7-66d5601a787f.png)
![mods2](https://user-images.githubusercontent.com/98983677/153368839-83265063-c6c3-481e-860e-6c1d7a103b25.png)


I attached video and using mods.

**Comment by MikulDev** [comment]
This is a very strange issue. I'm not sure what's causing it, and I can't seem to recreate it with the mods you listed. The backend for temperature is being improved in the next update, so I suspect this will be fixed after 2.1.3

**Comment by Rupla3130** [comment]
I see.  I wish the issue will be fixed.
