### ISSUE TITLE
hearth bug 

### ISSUE THREAD

**Issue by Me4eHbN1314** [Momo-Studios/Cold-Sweat-Rework-Forge#291]
so i craft the hearth and place it when i tried tu used my game crash 
why is happening? pls help

**Comment by Me4eHbN1314** [comment]
im playing on 1.20.1

**Comment by MikulDev** [comment]
A crash report would be helpful in solving this

**Comment by Me4eHbN1314** [comment]
it only gime -1 error crash and nothing else

**Comment by MikulDev** [comment]
So it does not generate any crash log at all in your Minecraft directory?

**Comment by Me4eHbN1314** [comment]
nope

**Comment by MikulDev** [comment]
What about latest.log?

**Comment by Me4eHbN1314** [comment]
nothing

**Comment by MikulDev** [comment]
Dude, you need to help me out here. You're saying your latest.log is absolutely _**empty**_, and there's _**no**_ crash report, error, log, or anything _**anywhere**_? Are you using a mod launcher? Does anything display when you crash?

**Comment by Me4eHbN1314** [comment]
oh i found it i was searching in a wrong folder sorry
[Uploading crash-2024-05-13_23.13.11-server.txt…]()

**Comment by MikulDev** [comment]
Thanks, but it doesn't look like the file uploaded correctly. It's stuck uploading despite being sent an hour ago. Could you try re-uploading it?

**Comment by Me4eHbN1314** [comment]
yes it was hour ago becosu i recreate the bug that hapend and i notice that the game crash non when i use it but when i place it

**Comment by Me4eHbN1314** [comment]
[Uploading crash-2024-05-13_23.13.11-server.txt…]()

**Comment by Me4eHbN1314** [comment]
so now i tried to recreate the bug but in creative and nothing change (this is crash report)
[crash-2024-05-14_08.01.25-server.txt](https://github.com/Momo-Softworks/Cold-Sweat/files/15303478/crash-2024-05-14_08.01.25-server.txt)

**Comment by MikulDev** [comment]
I don't know for sure, but this seems to be due to a mod conflict. The crash report references code that doesn't exist in Cold Sweat or Vanilla, so my only guess is that it was injected by a mixin from another mod. If this issue is reproducible with just Cold Sweat installed, I can look into it more

**Comment by Me4eHbN1314** [comment]
So i tried with only cold sweat and it didnt crash
