### ISSUE TITLE
Hearth problem

### ISSUE THREAD

**Issue by Jagrus** [Momo-Studios/Cold-Sweat-Rework-Forge#292]
Hi there!
I'm using the hearth to warm up a house in a cold biome and it works perfectly, but when I do the same in the desert it does not work. In the cold biome I've filled it with lava, but when I fill it with water or packed ice in the warm biome it does nothing. 

Am I missing something? 

Thank you in advance!

**Comment by MikulDev** [comment]
Thanks for pointing this out; this is indeed a bug. I'll have this fixed for the next version.
