### ISSUE TITLE
World Temperature UI Gauge is missing

### ISSUE THREAD

**Issue by TheSuperCheese** [Momo-Studios/Cold-Sweat-Rework-Forge#294]
In the newest version of the mod ColdSweat-2.3-b03.c for 1.19.2. The world temperature UI gauge is missing, even though it's set to true in the config file

**Comment by MikulDev** [comment]
Are you sure it's not just because of the new layout? Keep in mind that the diamond-shaped thing by your hotbar has been replaced by a new graphic that surrounds the body temperature icon in the center.

**Comment by trizmark** [comment]
Change either the difficulty to 'easy' or set the 'Require Thermometer' to false to see the temperature. I just updated my Steampunk modpack, which updated the Cold Sweat to v4.0.1 and I couldn't see the temperature (unless I created a thermometer and equipped it in a charm slot)
