### ISSUE TITLE
Ticking Entity Icebox Crash with Freeze it and Heat it [Mod Incompat]

### ISSUE THREAD

**Issue by ConqAra** [Momo-Studios/Cold-Sweat-Rework-Forge#295]
[crash-2024-05-16_12.05.37-server.txt](https://github.com/Momo-Softworks/Cold-Sweat/files/15338344/crash-2024-05-16_12.05.37-server.txt)
I'm playing with a modpack with b01a version. When I open the icebox and put water bucket in it the icebox ticked and crashed. Found out it was a mod incompat with the add-on [Freeze It and Heat It](https://modrinth.com/mod/freeze-it-and-heat-it/version/2.2.4)

**Comment by MikulDev** [comment]
The addon was most likely built for the latest stable version, which is 2.2.5.1. I doubt it has been updated to support beta vereions
