### ISSUE TITLE
1.20.1 Enabling advancedItemTooltips in options.txt will make cold sweat crash

### ISSUE THREAD

**Issue by DeshiDesu** [Momo-Studios/Cold-Sweat-Rework-Forge#296]
Forge 47.2.32
ColdSweat-2.3-b03d.jar
souls_like_universe_mod_20.1.450.jar
WeaponsOfMiracles-20.1.7.40.jar
EpicFight-20.7.4.jar

Context:
When you have a mod that adds shift for more tooltips info and have advancedItemTooltips enabled it crashes the game. It is not limited to just souls like universe, any mod that has this feature and has cold sweat installed will crash the game. This bug does not exist when cold sweat is uninstalled or have advancedItemTooltips disabled.

Instructions:
- Enable advancedItemTooltips
- Install any mod that adds shift for more tooltips info
- Press shift over the item
- Crash

Crash Log:
[crash-2024-05-17_04.41.08-client.txt](https://github.com/Momo-Softworks/Cold-Sweat/files/15346179/crash-2024-05-17_04.41.08-client.txt)

Here's a video for further details:
https://github.com/Momo-Softworks/Cold-Sweat/assets/120287925/4f41bc67-ee6c-4655-a82f-27c7942e19ee

This gave me a very huge headache since 1. the crash logs did not help at all 2. I had over 300 mods installed so I had to single out every mod to find the issue, turns out it was just cold sweat incompatibility with Minecraft.

**Comment by MikulDev** [comment]
This will be fixed in the next version. I'm not sure what the exact cause is, but basically the tooltip is supposedly empty, which I didn't account for.
