### ISSUE TITLE
Crash while mods loading

### ISSUE THREAD

**Issue by Atench** [Momo-Studios/Cold-Sweat-Rework-Forge#297]
[minecraft-exported-crash-info-2024-05-19T04-01-55.zip](https://github.com/Momo-Softworks/Cold-Sweat/files/15366707/minecraft-exported-crash-info-2024-05-19T04-01-55.zip)

**Comment by MikulDev** [comment]
Firstly, I would update the mod, and second, I don't see any mention of Cold Sweat being the cause of the crash. What led you to believe that Cold Sweat is the issue?
