### ISSUE TITLE
1.19.2 crash in the sewing table

### ISSUE THREAD

**Issue by DnsGnmm** [Momo-Studios/Cold-Sweat-Rework-Forge#298]
I used chameleon skin on aquamirae armor 2 times, after which the game crashed
I used ColdSweat-2.3-b03d.jar

[crash-2024-05-18_23.41.06-client.txt](https://github.com/Momo-Softworks/Cold-Sweat/files/15368830/crash-2024-05-18_23.41.06-client.txt)

[crash-2024-05-19_14.07.26-server.txt](https://github.com/Momo-Softworks/Cold-Sweat/files/15368831/crash-2024-05-19_14.07.26-server.txt)

**Comment by MikulDev** [comment]
I believe this should be fixed in the next version. I'll leave this open until it's confirmed

**Comment by carbonatek** [comment]
I'm using 2.3-b03e on 1.20.1 and it crashes even now; I could put one chameleon skin on a Refined Obsidian Chestplate from Mekanism Tools before it crashed. The rest of the armor pieces are fine.
Edit: here's the crash log [crashlog.txt](https://github.com/Momo-Softworks/Cold-Sweat/files/15467155/crashlog.txt)

**Comment by MikulDev** [comment]
Alright, well in that case, I have one more fix that should avoid this issue happening altogether. It'll be out very soon.

**Comment by carbonatek** [comment]
Fixed in 2.3-b03f :)

**Comment by MikulDev** [comment]
Awesome! I'll be closing this issue, then.
