### ISSUE TITLE
The game crashes on 1.20.1

### ISSUE THREAD

**Issue by FilipKompaniets3** [Momo-Studios/Cold-Sweat-Rework-Forge#301]
Crash report: https://bytebin.lucko.me/9NyidHhrW3

I was playing on my mod pack and after I broke the gravel block I had a crash and the "Not Enough Crashes" mod started blaming the "Cold Sweat" mod.

**Comment by MikulDev** [comment]
Duplicate of #299, #290, #286, and #283. This will be fixed in the next beta version

**Comment by FilipKompaniets3** [comment]
Ок
