### ISSUE TITLE
Another crash on 1.20.1 :) 

### ISSUE THREAD

**Issue by FilipKompaniets3** [Momo-Studios/Cold-Sweat-Rework-Forge#302]
While playing on my mod pack, going to the inventory in creative mode and scrolling down I get a crash

**Comment by FilipKompaniets3** [comment]
[crash-2024-05-25_22.02.22-client.txt](https://github.com/Momo-Softworks/Cold-Sweat/files/15444708/crash-2024-05-25_22.02.22-client.txt)

**Comment by MikulDev** [comment]
Duplicate of #301, #299, #290, #286, #283, and #274. This will be fixed in the next beta version
