### ISSUE TITLE
1.20.1 Crash then inventory open

### ISSUE THREAD

**Issue by PermskyKit** [Momo-Studios/Cold-Sweat-Rework-Forge#303]
I'm putting together a really big modpack with a lot of crutches, but judging by the crash reports, it's this mod that's causing the problem. I checked all the configuration values, but could not find any values ​​that might fall outside the arrays. Perhaps you can help.

Has been tested in mod versions 2.3-b03c and 2.3-b03d.

[crash-2024-05-27_01.50.27-client.txt](https://github.com/Momo-Softworks/Cold-Sweat/files/15449307/crash-2024-05-27_01.50.27-client.txt)

**Comment by PermskyKit** [comment]
I also add that neither MixinHelper nor NotEnoughCrashes were able to show the source of the problem..

**Comment by MikulDev** [comment]
Duplicate of #302, #301, #299, #290, #286, #283, and #274. This will be fixed in the next beta version

**Comment by PermskyKit** [comment]
> Duplicate of #302, #301, #299, #290, #286, #283, and #274. This will be fixed in the next beta version

Same in 2.3-b03e, sorry, maybe in "This will be fixed in the next beta version" you mean later versions..

[crash-2024-05-29_21.48.17-client.txt](https://github.com/Momo-Softworks/Cold-Sweat/files/15489518/crash-2024-05-29_21.48.17-client.txt)

**Comment by MikulDev** [comment]
Try this and see if it solves your issue. This is a modified version that should be more resilient against other mods messing with the tooltip lines:
[ColdSweat-2.3-b03f.zip](https://github.com/Momo-Softworks/Cold-Sweat/files/15493270/ColdSweat-2.3-b03f.zip)

**Comment by PermskyKit** [comment]
> Try this and see if it solves your issue. This is a modified version that should be more resilient against other mods messing with the tooltip lines: [ColdSweat-2.3-b03f.zip](https://github.com/Momo-Softworks/Cold-Sweat/files/15493270/ColdSweat-2.3-b03f.zip)

I tried this in the same world and it really works without problems, thanks! Do you need logs or anything else?

**Comment by MikulDev** [comment]
Nope, that's it. This fix will be included in the next public release.
