### ISSUE TITLE
1.19.2, Forge, game crashes when a hearth is placed down

### ISSUE THREAD

**Issue by ghost** [Momo-Studios/Cold-Sweat-Rework-Forge#304]
[crash-2024-05-28_20.06.47-server.txt](https://github.com/Momo-Softworks/Cold-Sweat/files/15477096/crash-2024-05-28_20.06.47-server.txt)

My game freezes up for a few seconds then crashes when I place down a hearth.

**Comment by ghost** [comment]
So, I went ahead and double-checked the report since I got intimidated by it at first but wanted to check again, and the mod Labelling Containers was the one the was causing this crash to happen. I'm not sure if I should go ahead and close this issue down or leave it up since it's a bug. Sorry for the bother!

**Comment by MikulDev** [comment]
Alright, then. If this is due to another mod, then I'll be closing this issue. I might suggest raising this issue with the authors of Labelling Containers. Thanks for submitting the report :)

**Comment by MikulDev** [comment]
This is a shot in the dark, but you might have some luck with updating to the latest beta version. There have been a lot of changes between 2.2.5.1 and 2.3-b03e.

**Comment by ghost** [comment]
I can most certainly try that around! Thank you very much for your help and time!

**Comment by ghost** [comment]
Interesting quick news: no crash with the hearth!
