### ISSUE TITLE
crash when entering/creating a world

### ISSUE THREAD

**Issue by Smoker120900** [Momo-Studios/Cold-Sweat-Rework-Forge#306]
[crash-2024-05-31_19.09.05-client.txt](https://github.com/user-attachments/files/15519127/crash-2024-05-31_19.09.05-client.txt)

**Comment by MikulDev** [comment]
Seems like Enhanced Visuals's new compat for Cold Sweat only works for pre-2.3 versions. The only options right now are to remove Enhanced Visuals or downgrade Cold Sweat. 

You should raise this issue with the mod author, as they really should be developing with the latesr version in mind.

**Comment by Smoker120900** [comment]
thanks, i'll contact EV's dev abut this

**Comment by MikulDev** [comment]
For now, I'll be closing this issue. If it's revealed that this is an issue with Cold Sweat itself, then I'll reopen it.
