### ISSUE TITLE
1.20.1 Create Backtank loses insulation

### ISSUE THREAD

**Issue by theMegaTech** [Momo-Studios/Cold-Sweat-Rework-Forge#307]
If backtank is placed in-world (necessary for recharging it) - it loses any insulation it had from sewing table. Would be nice to have it saved somehow if possible cuz otherwise you lose quite a huge part of insulation or forced to constantly change backtank to chestplate or something like that.

**Comment by MikulDev** [comment]
This is a duplicate of #239. It was determined that it is up to the authors of Create to ensure that item data is properly preserved upon placing it as a block.
