### ISSUE TITLE
There is no curios slot for thermometer 

### ISSUE THREAD

**Issue by FilipKompaniets3** [Momo-Studios/Cold-Sweat-Rework-Forge#308]
![20240608_203349](https://github.com/Momo-Softworks/Cold-Sweat/assets/169136387/4f2a57f9-8eef-4dc3-9e2a-f7fae8333ece)

https://github.com/Momo-Softworks/Cold-Sweat/assets/169136387/5a105259-fc0f-4f75-bc26-11805cada6ae

**Comment by MikulDev** [comment]
What version of the mod/Minecraft are you using?

**Comment by FilipKompaniets3** [comment]
> Яку версію мода/Minecraft ви використовуєте?

1.20.1 forge 47.3.0, cold sweat-2.3-b04a

Sorry, I forgot to write this then

**Comment by MikulDev** [comment]
Alright, I was able to replicate this issue. Thanks for letting me know. This will be fixed in the next version.

**Comment by FilipKompaniets3** [comment]
Okey
