### ISSUE TITLE
The World Bug I brought up in the Comments

### ISSUE THREAD

**Issue by MidnightMangled** [Momo-Studios/Cold-Sweat-Rework-Forge#312]
The Video Explains it all. Sorry for the somewhat crappy editing.
P.S. This was all done on one modpack.
https://youtu.be/rU20rNGwO3g

**Comment by MikulDev** [comment]
So if you go somewhere extreme, like next to a pool of lava, the nether, a frozen biome, etc, it stays the same? The examples in the first world are generally pretty temperate. If that still doesn't work, and reloading the game also doesn't work, then you might need to try killing the player and respawning. I'm not sure how it got into such a state, but that usually fixes it

**Comment by MidnightMangled** [comment]
Dying and respawning ended up fixing it. I can't believe I never even thought about trying that.

**Comment by MikulDev** [comment]
Glad it's fixed. Sorry that had to be the solution, though, lol.
