### ISSUE TITLE
Minecraft crashing when trying to render goats

### ISSUE THREAD

**Issue by isoextension** [Momo-Studios/Cold-Sweat-Rework-Forge#313]
Hello, i have an issue when playing with other mods: Minecraft crashing when trying to render goats.

Crash report:
[mclo.gs/9KrRUYQ](https://mclo.gs/9KrRUYQ)

Can anyone help me?

**Comment by MikulDev** [comment]
This should be resolved in the next version

**Comment by isoextension** [comment]
Thanks! :D
