### ISSUE TITLE
Crash || ColdSweat-2.3-b04b ||

### ISSUE THREAD

**Issue by Stiles52** [Momo-Studios/Cold-Sweat-Rework-Forge#314]
Hello,
I am experiencing a crash when updating to "2.3-b04b". I deleted the configs in order to redo them if necessary. But the crash is persistent and I don't understand it. 

Thank you for your help,
Stiles

[crash-2024-06-15_18.03.23-fml.txt](https://github.com/user-attachments/files/15848493/crash-2024-06-15_18.03.23-fml.txt)

**Comment by MikulDev** [comment]
It appears ModernFix and Cold Sweat have conflicting mixins. For now, this means the two mods are incompatible, but I will try to fix this for the next version.
