### ISSUE TITLE
game crashes when trying to change the dimension temperature offset 

### ISSUE THREAD

**Issue by egeme0nozhan** [Momo-Studios/Cold-Sweat-Rework-Forge#316]
when I try to change the dimension temperature offset game crashes same as the biomes  

![resim_2024-06-18_191449087](https://github.com/Momo-Softworks/Cold-Sweat/assets/78966508/1ba4bf63-6446-4131-9eb6-eddb5e4e8455)

![resim_2024-06-18_191537239](https://github.com/Momo-Softworks/Cold-Sweat/assets/78966508/f633f3ae-efa7-4462-999d-dbd2f2b4563c)

**Comment by MikulDev** [comment]
Please don't use Configured to edit Cold Sweat stuff. This mod's settings are too complex for Configured to handle properly and it crashes.
