### ISSUE TITLE
Loading with REI may cause the game to freeze

### ISSUE THREAD

**Issue by Hanwei233** [Momo-Studios/Cold-Sweat-Rework-Forge#318]
I'm trying to update the version of the Cold Sweat mod in my modpack, After the update was completed, I noticed that as soon as I opened the backpack, the game would freeze. After troubleshooting, I found that cold sweat and REI were causing the problem, I've tested it a lot and found that mods from version 2.3-b02d and above cause the game to freeze

There are a few cases where it doesn't get stuck, but REI is always in the "search results" state
![2024-06-26_23 34 14](https://github.com/Momo-Softworks/Cold-Sweat/assets/121529662/97599374-50b7-4108-bd7d-c0508dc6b9b1)
In this video, I used the latest cold sweat and REI versions, and the game freezes the moment I open the backpack

https://github.com/Momo-Softworks/Cold-Sweat/assets/121529662/d029a29f-27db-4b70-b39e-4b7d2b311ad0

Debug log: https://pastebin.com/KsFeF5WN
Latest log: https://pastebin.com/XXcq7zhD

Sorry, I used a translator!

**Comment by MikulDev** [comment]
I don't see any errors in the log, which is strange. Does the game crash after this, or is it permanently frozen?

**Comment by Hanwei233** [comment]
frozen

**Comment by MikulDev** [comment]
I know the mods have mixin compatibility issues, but the fact that it doesn't provide any information on the conflict means there's very little I can do in the way of solving it. Unfortunately, the best option that I know of is to use an alternative like JEI

**Comment by Hanwei233** [comment]
> 我知道这些模组存在 mixin 兼容性问题，但它没有提供有关冲突的任何信息这一事实意味着我在解决它方面无能为力。不幸的是，我所知道的最好的选择是使用像 JEI 这样的替代方案

Well, thank you
