### ISSUE TITLE
Received invalid discriminator byte 12 on channel cold_sweat:main

### ISSUE THREAD

**Issue by sh-syl** [Momo-Studios/Cold-Sweat-Rework-Forge#319]
I have received the same problem as #275 , and the game launcher has also crashed. The message comes as byte 12 not 13 but I think it is probably the same problem. 
The lastest.log is placed below.

**Comment by sh-syl** [comment]
[Uploading latest (1).log…]()

**Comment by sh-syl** [comment]
[latest (1).log](https://github.com/user-attachments/files/16093779/latest.1.log)

**Comment by MikulDev** [comment]
I have never been able to get this issue to occur in my testing. Would you be able to send the modpack you are using?
