### ISSUE TITLE
Cold Sweat Mod Error

### ISSUE THREAD

**Issue by reallesslm** [Momo-Studios/Cold-Sweat-Rework-Forge#320]
[latestlog.txt](https://github.com/user-attachments/files/16147820/latestlog.txt)
[crash-2024-07-09_17.17.26-fml.txt](https://github.com/user-attachments/files/16147821/crash-2024-07-09_17.17.26-fml.txt)

**Comment by MikulDev** [comment]
This issue has been reported on the Discord server as well. It will be fixed in the next version coming out soon.
