### ISSUE TITLE
crashes when changing difficulty

### ISSUE THREAD

**Issue by idk607** [Momo-Studios/Cold-Sweat-Rework-Forge#321]
- Minecraft Version: 1.19.2
- Forge Version: 43.4.2
- Mod Version: ColdSweat-2.3-b04e

[crash-2024-07-10_20.12.55-client.txt](https://github.com/user-attachments/files/16161871/crash-2024-07-10_20.12.55-client.txt)

It crashes when changing difficulty in the newest version of cold sweat

https://github.com/Momo-Softworks/Cold-Sweat/assets/174937605/2c4d5a9c-840a-4b4c-8c26-c0f63a236540

**Comment by idk607** [comment]
also crashes when creating new world
[crash-2024-07-10_20.53.15-server.txt](https://github.com/user-attachments/files/16162336/crash-2024-07-10_20.53.15-server.txt)

**Comment by MikulDev** [comment]
Does this happen when you are in-game (the config menu crash)? Due to many of the configs requiring the world to be loaded, I will probably end up having to disable the config menu on the title screen.

I will have to look into the other thing.

**Comment by idk607** [comment]
nvm, after testing out the newest version (ColdSweat-2.3-b04f) it works now and does not crashes after changing configs (only in-game though since it is disabled in the menu).
