### ISSUE TITLE
Tooltip bug with Iceberg

### ISSUE THREAD

**Issue by TheKuwagata** [Momo-Studios/Cold-Sweat-Rework-Forge#322]
![image](https://github.com/Momo-Softworks/Cold-Sweat/assets/96778859/dc918cf0-e279-4206-ad51-4cdedaf24c6e)

When cold sweat and iceberg are installed simultaneously, the insulation moves above the item name

https://legacy.curseforge.com/minecraft/mc-mods/iceberg
Minecraft version: 1.20.1

**Comment by MikulDev** [comment]
Which version of the mod are you using?

**Comment by TheKuwagata** [comment]
2.3-b04f

**Comment by MikulDev** [comment]
That's interesting. I thought I fixed that issue a while ago. I'll double-check

**Comment by MikulDev** [comment]
Hello again, apologies for the wait. I've been out of town for a while. This does seem to be an issue, specifically with items that have only one line in their tooltips. I will have this fixed for the next version.
