### ISSUE TITLE
[1.21] Neoforge and mod lasted version crash

### ISSUE THREAD

**Issue by Periam** [Momo-Studios/Cold-Sweat-Rework-Forge#323]
After installing the below combination of mods the game crash before completing the loading screen

NeoForge 21.0.95
ColdSweat-2.3-a04f.1.jar
curios-neoforge-9.0.4+1.21.jar
jei-1.21-neoforge-19.5.0.33.jar

[debug.log](https://github.com/user-attachments/files/16239227/debug.log)
[latest.log](https://github.com/user-attachments/files/16239229/latest.log)
[crash-2024-07-15_16.21.15-fml.txt](https://github.com/user-attachments/files/16239247/crash-2024-07-15_16.21.15-fml.txt)

![Screenshot 2024-07-15 161549](https://github.com/user-attachments/assets/5cb02fa4-4ad8-43f8-906b-f3e1df7d79e1)

**Comment by MikulDev** [comment]
This will likely go away when a newer version of the mod releases. NeoForge updates so often that it's already had over 30 releases since I uploaded the version you're using. There are bound to be breaking changes, as it's still in beta
