### ISSUE TITLE
[Forge 2.3-b04g] Armor Insulation has no effect

### ISSUE THREAD

**Issue by Urias0** [Momo-Studios/Cold-Sweat-Rework-Forge#325]
I tested it , i can worn a full hoglin armor or even another armor with hoglin hide fully insulated it doesn't have any impact on my armor (especially in the nether, but even right now in my world it's the start of summer and same shit i'm stuck at 37-39 degree 

Edit : I had a full chameleon molt armor the whole time and it did the same , didn't reduce the heat in any way , nether is not survivable for more than 5 minute if you're not anywhere near a soul sand valley

**Comment by MikulDev** [comment]
So, just to clear up any possible confusion, insulation simply slows down the rate at which you overheat/freeze. It doesn't do anything to the world's temperature itself.

Armor insulation alone is not enough to survive the Nether for an extended period of time. I'd suggest looking around in the wiki at the additional options available to you

**Comment by Urias0** [comment]
Alright i see , i'll do some test tomorrow because honestly the difference it make seems VERY low

**Comment by Urias0** [comment]
Nevermind yeah i was wrong and i misunderstood it , figured out the soulspring lamp , i'll delete this now and sorry for the fake report
