### ISSUE TITLE
[1.20.1]Season change did not change the temperature in other dimensions

### ISSUE THREAD

**Issue by moguang2004** [Momo-Studios/Cold-Sweat-Rework-Forge#326]
There are serene season and the coldsweat in my modpack. After i changed the config of serene season to allow season cycle in the nether and adjust the temperature offset with coldsweat config, I found that there is no influence on the temperature as the season changed in the nether
![image](https://github.com/user-attachments/assets/5e5938b1-434c-436f-8dbd-f111402cdd84)
![image](https://github.com/user-attachments/assets/4407751c-ebbd-482b-a9f7-719f815ecc7b)

**Comment by moguang2004** [comment]
mod version:
cold sweat 2.3-b04g
serene season 9.0.0.46

**Comment by MikulDev** [comment]
I didn't even know what was a thing. I prevented Serene Seasons from working in the Nether, not realizing they had a setting to enable it. I will add a check that enables this behavior of the setting you're talking about is turned on

**Comment by moguang2004** [comment]
> I didn't even know what was a thing. I prevented Serene Seasons from working in the Nether, not realizing they had a setting to enable it. I will add a check that enables this behavior of the setting you're talking about is turned on

Thanks, I really like the reality temperature system of this mod, so I just want to make people more comfortable in the nether in winter. Looking forward to the next version!

**Comment by MikulDev** [comment]
Fixed for the next version
