### ISSUE TITLE
Ice Resistance has no brewing recipe

### ISSUE THREAD

**Issue by theLeaxx** [Momo-Studios/Cold-Sweat-Rework-Forge#327]
I'm playing on a modded server that has Cold Sweat. I tried looking in JEI for the recipe for Ice Resistance potions, however it just doesn't show up at all. The only recipes that show up are the ones for the Splash and Lingering Ice Resistance potions (since they just involve adding extra ingredients to a normal potion).

If needed, I can send logs and the mod list

**Comment by MikulDev** [comment]
I've found the source of the issue. Thanks for reporting
