### ISSUE TITLE
Upgrading a diamond armor to netherite lose armor insulation

### ISSUE THREAD

**Issue by Urias0** [Momo-Studios/Cold-Sweat-Rework-Forge#328]
As title said , i upgraded from diamond to netherite and the insulation disapeared , didn't really notice before i went in the nether 

EDIT: It does the same when i put an enchanted book on my armor , and only performance mod i have is embeddium if that helps

**Comment by MikulDev** [comment]
I couldn't replicate this issue when using enchanted books in an anvil, but it does happen in the smithing table. I'll have this fixed for the next version.
