### ISSUE TITLE
Going to the end and taking the portal to go back in the overworld reset the Hearth "Show Air Particles" to ON

### ISSUE THREAD

**Issue by Urias0** [Momo-Studios/Cold-Sweat-Rework-Forge#329]
So i'm farming the dragon for a drop and i've noticed that whenever i got back to my base after taking the portal it reset the particles , i usually turn them off and it's the 3rd time they turned by themselves ,

**Comment by MikulDev** [comment]
Thanks for letting me know. I think I've found a solution to this problem, which will be in the next release.
