### ISSUE TITLE
Internal server error when connecting to server.

### ISSUE THREAD

**Issue by AStrangeMouse** [Momo-Studios/Cold-Sweat-Rework-Forge#33]
Cold Sweat version r2.1.8 - Removing the mod from both the server + client allows connection.
**Log:** [https://pastebin.com/Xw1MMU4Q](https://pastebin.com/Xw1MMU4Q)
**Mod list:** [https://pastebin.com/8mqRHxtp](https://pastebin.com/8mqRHxtp)

This is my first time ever submitting a bug report, so let me know if more information is required.

**Comment by MikulDev** [comment]
It says in the mod list that you're using r2.1.**7**. Are you sure it's updated?

**Comment by AStrangeMouse** [comment]
No, you're absolute right - I got my versions mixed up somewhere along the way in the modding process. My apologies!

**Comment by MikulDev** [comment]
No problem. Glad it was an easy fix, at least ;)
