### ISSUE TITLE
Prevent Aquamirae Ice Maze freezing when installed?

### ISSUE THREAD

**Issue by mycroftjr** [Momo-Studios/Cold-Sweat-Rework-Forge#330]
I have basically full cold and heat immunity via item configs on my Ad Astra Jet Suit, but I still freeze in water in the Ice Maze from Aquamirae. In Aquamirae alone, you're meant to wear the full Three-Bolt armor set to prevent this, but with Cold Sweat handling cold temperatures on its own, Aquamirae shouldn't be able to make you freeze if you aren't freezing in Cold Sweat, y'know?

(Also ps: it'd be neat if you gained full cold immunity in Cold Sweat terms from the full-set ability of said Three-Bolt armor.)

MC version: 1.19.2
Forge version: 43.3.5
Cold Sweat version: 2.3-b03d
Aquamirae version: 6.API15

(Additional armors you might want to add compatibility with are mentioned in https://github.com/LunaPixelStudios/SteamPunk/issues/301)

**Comment by MikulDev** [comment]
The latest version will have support for the three-bolt set. I think the rest of these features can be implemented my modpack devs at their discretion

**Comment by mycroftjr** [comment]
> The latest version will have support for the three-bolt set. I think the rest of these features can be implemented my modpack devs at their discretion

Wait, so will I no longer freeze when having cold insulation in the Ice Maze?

**Comment by MikulDev** [comment]
It will provide significant cold resistance, on top of whatever insulation you're wearing. Nothing in Cold Sweat is ever 100% by design, but it's very close

**Comment by mycroftjr** [comment]
> It will provide significant cold resistance, on top of whatever insulation you're wearing. Nothing in Cold Sweat is ever 100% by design, but it's very close

Sure, but will cold insulation prevent the Aquamirae freezing mechanic (specific to water in an Ice Maze) from occuring, as it probably should?

**Comment by MikulDev** [comment]
The armor itself prevents Aquamirae's freezing mechanic from happening. The addition buffs I'm giving it further increase your resistance to cold temperatures. I'm also making some changes to how ice and insulation work that should make it better as well.

**Comment by mycroftjr** [comment]
> The armor itself prevents Aquamirae's freezing mechanic from happening. The addition buffs I'm giving it further increase your resistance to cold temperatures. I'm also making some changes to how ice and insulation work that should make it better as well.

I'm asking whether we'll still be able to Aquamirae-freeze in non-three-bolt armor with very high cold insulation. Bcuz imo, we shouldn't.

**Comment by MikulDev** [comment]
No, you will not Aquamirae-freeze. As I said before, the armor already prevents that from happening; Cold Sweat doesn't change that. The addition Cold Sweat makes is to prevent you from "Cold-Sweat-freezing" too quickly

**Comment by mycroftjr** [comment]
I know the Three-Bolt armor set prevents you from Aquamirae-freezing. I'm asking that OTHER armor (from outside the mod, etc) ALSO prevent you from Aquamirae-freezing IF it has enough cold insulation in Cold Sweat. Because the Aquamirae-freezing isn't magical - Aquamirae just assumes that temperature wasn't a thing in the game yet.

But I suppose that should be a change from Aquamirae's side.

**Comment by MikulDev** [comment]
OH, ok. I understand what you're saying now. I'm sorry for the confusion. I've been really scatterbrained after the influx of new submissions and attention since 2.3. It looks like Aquamirae hard-codes the freezing mechanic to exclusively check for three-bolt armor, otherwise you just freeze no matter what. 

So yes, they would have to change this to add Cold Sweat support, or at least add a hook for other mods to change how this freezing mechanic works

**Comment by mycroftjr** [comment]
> So yes, they would have to change this to add Cold Sweat support, or at least add a hook for other mods to change how this freezing mechanic works

Submitted as a suggestion on their discord: https://discord.com/channels/899742852681191444/1275708526785728533
