### ISSUE TITLE
Heracles crash

### ISSUE THREAD

**Issue by GogUwU** [Momo-Studios/Cold-Sweat-Rework-Forge#331]
neoforge 1.20.1 

game crashes then you press on a check box or link

[Cold Sweat version](https://modrinth.com/mod/cold-sweat/version/2.2.5.1)
[Heracles version](https://modrinth.com/mod/heracles/version/1.1.13)

**Comment by MikulDev** [comment]
I would need the crash report to know why it crashed

**Comment by GogUwU** [comment]
[crash-2024-08-06_14.33.33-client.txt](https://github.com/user-attachments/files/16509604/crash-2024-08-06_14.33.33-client.txt)
[latest.log](https://github.com/user-attachments/files/16509605/latest.log)

can't upload debug log it's too big 😭

**Comment by GogUwU** [comment]
any updates?

**Comment by MikulDev** [comment]
Thanks for the input. Apologies for getting to this late, but this will be fixed in the next version
