### ISSUE TITLE
Netherite boots, pants + Create backtank and diving helmet doesn't use insulation

### ISSUE THREAD

**Issue by MomaDuck** [Momo-Studios/Cold-Sweat-Rework-Forge#333]
We ran some tests on how each individual insulated piece worked in the nether and we noticed that netherite pants, boots and create backtank + diving helmet did not provide any more heating insulation than no armor at all.
I hope that is ok that i posted this issue here. Thank you for a fun and cool mod!

**Comment by MomaDuck** [comment]
This is on a server that has been restarted and the armor insulation is consistent between players (it is the same way for all of the players wearing armor).
The modpack is: https://www.curseforge.com/minecraft/modpacks/steam-punk

The insulation type is rabbit hide
same result with leather as well

**Comment by MomaDuck** [comment]
the set of armor described above would last me 17 seconds. a full iron armor set would last about 3.5- 4 minutes

**Comment by MikulDev** [comment]
This armor set is actually supposed to have a set bonus that basically negates heat. The bug that prevented this from being the case was just fixed in the version released a few minutes ago, actually.

**Comment by MomaDuck** [comment]
New bug.... Now when you have a full set of anything with the backtank it jumps the temperature to 75 in the nether. 
It alone on does nothing, but any full set with backtank jumps the temperature.

the 75 is irrelevant of the location, as the place is cooled for people without armor.

We have Celsius, and the backtank is draining air little by little.
My best guess is that it forces the temperature to 75 degrees fahrenheit and it puts the same number in Celsius

**Comment by MomaDuck** [comment]
![2024-08-07_15 16 24](https://github.com/user-attachments/assets/4e52a370-fd07-4c4e-9561-cfa66646b7ea)
![2024-08-07_15 16 31](https://github.com/user-attachments/assets/82057a22-cd0f-4c43-b42d-5b2acb0bbc64)
![2024-08-07_15 16 50](https://github.com/user-attachments/assets/7faa124d-ed56-4415-aa57-5318cd802ea2)
![2024-08-07_15 16 55](https://github.com/user-attachments/assets/2f741128-cdf2-4788-87c7-2599a2bcc58c)
Apparently it does protect from lava heat in the overworld and the issue is only in the nether.

It also protects me from the cold without using any of the air in the tank. Keeps me at a steady 15. As soon as i take the tank off i drop down to 4

**Comment by MikulDev** [comment]
These are very strange effects to be having. I'm not able to replicate any of this behavior on 1.20. Is this able to be replicated with just Cold Sweat installed?

**Comment by MikulDev** [comment]
Following up on this issue. Are you able to replicate this in an environment with just Cold Sweat?
