### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by davethemodderguy** [Momo-Studios/Cold-Sweat-Rework-Forge#335]
The new issue is that the hazmat suit from mekanism and any type of modded armor cannot apply insulation

**Comment by MikulDev** [comment]
What version of Cold Sweat and Minecraft are you using? I haven't experienced this to be the case. I can insulate modded armors just fine

**Comment by davethemodderguy** [comment]
2.3-404g maybe?

Vào Th 6, 16 thg 8, 2024 vào lúc 01:45 MikulDev ***@***.***>
đã viết:

**Comment by MikulDev** [comment]
Try updating to the newest version, then. Is has some changes that might help

**Comment by SecretSeptus** [comment]
forge 47.3.1
minecraft 1.20.1

Boiler+smokestack fail to isulate a room

![image](https://github.com/user-attachments/assets/af8d973e-66f4-4be1-b7fa-45dad99fdfe8)


I am playing with origins mod, and I have a race with increased burning point (reason why 39C is cold)

**Comment by MikulDev** [comment]
I would have preferred you make a new issue for this, but sure.
The reason why is because the boiler is not powered. It requires a redstone input in order to turn on its insulation features.
