### ISSUE TITLE
Season change in the nether still doesn't work

### ISSUE THREAD

**Issue by moguang2004** [Momo-Studios/Cold-Sweat-Rework-Forge#336]
[[1.20.1]Season change did not change the temperature in other dimensions](https://github.com/Momo-Softworks/Cold-Sweat/issues/326#top)
#326 
Same to this issue, i don't know why the mechanism didn't work in the nether only in the latest version

**Comment by MikulDev** [comment]
Thanks for the feedback. I found the source of the issue
