### ISSUE TITLE
Sewing Table Not Functioning

### ISSUE THREAD

**Issue by Fooshcookie** [Momo-Studios/Cold-Sweat-Rework-Forge#337]
Recently started up a 1.21.1 server with my friends and decided to introduce them to ColdSweat. While preparing for Nether exploration, we ran into a very large, problematic issue. As it stands, in the latest version of the mod for 1.21, the sewing table is not functioning as intended. This issue is on both 1.21 and 1.21.1, meaning it doesn't seem to be a problem with the update. I specifically have provided a screenshot of the 1.21 version, with no other mods, as a quick show of what I mean.

I am worried there is no effect at all, happening, as I haven't noticed myself freezing slower after lining my armor with leather. As it stands, the sewing table will consume and take the material, but will result in no visible change. A picture is provided, this effect is exactly the same in both versions, with or without other mods. As it stands, this is quite literally making us unable to properly progress both the Nether and the Eternal Starlight.

![Screenshot_301](https://github.com/user-attachments/assets/d0e51449-5708-448e-a7a8-829027588f06)

I do not believe logs are needed, but if they are, please do let me know.

**Comment by MikulDev** [comment]
You're right, thanks for the report. Luckily, it was a very easy fix! This will be addressed in the next release
