### ISSUE TITLE
Crash on Cold-Sweat Version 2.3 (Forge 1,20,1-47.2.17)

### ISSUE THREAD

**Issue by squeamishgeek** [Momo-Studios/Cold-Sweat-Rework-Forge#340]
I updated it and this warning occurred before the game crashed. After downgrading the mod to the older version, it ran without issue.

[pool-4-thread-1/WARN] [mixin/]: Error loading class: com/momosoftworks/coldsweat/api/util/Temperature$Type (java.lang.ClassNotFoundException: com.momosoftworks.coldsweat.api.util.Temperature$Type)

**Comment by MikulDev** [comment]
Please send the full crash report. This isn't enough information to go on

**Comment by squeamishgeek** [comment]
Here is the full crash report:
[crashreport.txt](https://github.com/user-attachments/files/16651443/crashreport.txt)

**Comment by MikulDev** [comment]
This seems like a mod conflict. Another mod is attempting to reference a part of the code in Cold Sweat that doesn't exist anymore

**Comment by squeamishgeek** [comment]
Thanks for your help. I will look into the mods that may be causing the issue.
