### ISSUE TITLE
Cant add water to the hearth

### ISSUE THREAD

**Issue by PeskyBird2** [Momo-Studios/Cold-Sweat-Rework-Forge#343]
im playing with friends on a server and we cant add water to the hearth to make it work. we are playing in 1.19.2 with version ColdSweat-2.3.1.jar

**Comment by MikulDev** [comment]
As of 2.3, water is no longer a valid fuel source for the icebox or hearth. You will now need to collect ice, which is now obtainable with a non-enchanted stone pickaxe or better. Ice also now forms naturally in locations that are below freezing temperature (32 °F, 0 °C).
