### ISSUE TITLE
placing down boiler crashes game (1.20.1, v2.3.1)

### ISSUE THREAD

**Issue by speedonium** [Momo-Studios/Cold-Sweat-Rework-Forge#344]
Currently playing a modpack w some friends and decided to add cold sweat. placed down a boiler to heat up some waterskins and the game crashed. PLS HELP!!!
[crash-2024-08-21_20.24.34-server.txt](https://github.com/user-attachments/files/16703002/crash-2024-08-21_20.24.34-server.txt)

**Comment by MikulDev** [comment]
Thanks for the report. This will be fixed in the next version.
