### ISSUE TITLE
1.20.1 NeoForge Crash with Memory Leak Fix + Cold Sweat + Ambient Sounds

### ISSUE THREAD

**Issue by Astral-Haze** [Momo-Studios/Cold-Sweat-Rework-Forge#345]
After updating this mod and ambient sounds, the combination of mods causes a crash on entering/creating a world
https://modrinth.com/mod/memoryleakfix
https://modrinth.com/mod/ambientsounds

**Comment by MikulDev** [comment]
Please send the crash report so I can see the issue

**Comment by Astral-Haze** [comment]
[crash-2024-08-21_21.34.06-client.txt](https://github.com/user-attachments/files/16703291/crash-2024-08-21_21.34.06-client.txt)

**Comment by Astral-Haze** [comment]
have sent issue to all three as I'm not sure which is responsible

**Comment by MikulDev** [comment]
I might be doing something wrong which is causing their mixin to conflict with mine, but [this mixin](https://github.com/FxMorin/MemoryLeakFix/blob/19ee4b0ac7a8f7a5331029896ff7caa7e864257b/common/src/main/java/ca/fxco/memoryleakfix/mixin/biomeTemperatureLeak/Biome_threadLocalMixin.java#L4) from Memory Leak Fix appears to be the direct culprit. It is conflicting with [my mixin](https://github.com/Momo-Softworks/Cold-Sweat/blob/1.20.1-FG/src/main/java/com/momosoftworks/coldsweat/mixin/MixinFreezingWater.java) for changing how ice freezes

**Comment by Astral-Haze** [comment]
can add that to my issue on their side (and/or ambient sounds?) if you think i should although it seems memory leak fix may be abandoned judging from a comment on another issue there so i guess i may just leave said mod out

**Comment by MikulDev** [comment]
That would be a shame, but does seem to be the case given the last updated date on CurseForge. That mod provides a pretty large amount of great fixes. I might try to find a way around this on my side, to preserve compatibility.
