### ISSUE TITLE
Crash/Hearth not working - MC1.19.2 - Forge 43.4.2

### ISSUE THREAD

**Issue by Dalioxy** [Momo-Studios/Cold-Sweat-Rework-Forge#346]
Hello,

Im seeking 2 problems. Before starting, Im facing those 2 on 2 different modpack : one having 200+ mods and one having only those "Biomes o' plenty, Cold sweat, Serene seasons & Terra blender" (both custom modpacks).

First one is that when I go to config the mod in game, putting temperature to celcius for exemple, once I do validate options, my games crash : "The game crashed whilst mouseclicked event handler
Error: com.momosoftworks.coldswea
t.util.exceptions.SerializationException: Failed to save DynamicHolder for type HashMap"
[Plantage 1.txt](https://github.com/user-attachments/files/16711238/Plantage.1.txt)
It does the same when I do change the difficulty (error I did link into the upper .txt).

Also, the hearth seems not working. When I do fuel it with corresponding stuff (coals, lava buckets or snowballs), temperature isnt affected. Same for items upgraded with fur. Also, hearth does not even get "smoke" animation. Also, boiler has no trouble.
Instead, standing near lava, fire camp, ... does affect temperature.

![Animation](https://github.com/user-attachments/assets/c79ab1ca-6527-4673-9494-14f97c466a4a)

Did I understand or do something wrong ? Dunno.

If you have any idea of whats going wrong, I would be very thankfull for ure help :)

**Comment by Dalioxy** [comment]
I am using Coldsweat-2.3.1.jar version :) Forgot to notice that, sorry.

**Comment by MikulDev** [comment]
For the hearth, is it being powered by redstone? The sides of the hearth now have redstone inputs that need to be powered in order for it to emit particles and temperature.

As for the config menu, this is a genuine issue. I will address this in the next version.

**Comment by Dalioxy** [comment]
Well, when I do fill redstone, I can have the "chill" buff for the frost. But I do not have any buff for the warm, normal ?

Also, I get an error when I put redstone with my bigger modpack, I will try it back to get the log file to find where it is coming from :) Thank you for ure return.

**Comment by MikulDev** [comment]
To get the chill effect, power the hearth from the sides. To get the warmth effect, power it from the back.

**Comment by Dalioxy** [comment]
It seems working now on my modpack. And I didnt notice I had to try all those stuff inside a house (I was trying outside).

Forgive my mistakes and your time wasting. Thanks for your work :)

**Comment by MikulDev** [comment]
You're welcome! No problem
