### ISSUE TITLE
[Suggestion] Stackable Carried Item Temperatures Should Count as One

### ISSUE THREAD

**Issue by dandalous** [Momo-Studios/Cold-Sweat-Rework-Forge#348]
I've added torches, lanterns and lava buckets as portable heat sources, the first two intended to be very early game means of survival in a pinch before one can collect flint and steel, leather and deepslate.

Here's what I have in `item_settings.toml`:
```toml
"Carried Item Temperatures" = [["minecraft:torch", 0.01, "hand", "world"], ["minecraft:lantern", 0.01, "hand", "world"], ["minecraft:lava_bucket", 0.5, "inventory", "world"]]
```

Ideally I'd have the torch and lantern match their placed counterpart values of `0.15` but because they stack and the temperatures are cumulative, 64 torches in-hand would be an easy way to cheese and circumvent the use of heated waterskin. I have it set to `0.01` so that a stack of torches in-hand caps out at `0.64`. Instead I'd want an option to either have stackable items count as one item (the logic being that you only lit one torch in hand) or to have a max temperature that items can influence (for the torches and lanterns I'd just have the values equal).

Stack count once proposal format:
```toml
#Format: [["item_id", temperature, strict_type, trait, count once = false, *nbt], ...etc]
"Carried Item Temperatures" = [["minecraft:torch", 0.15, "hand", "world", true], ["..."]]
```

Max temperature proposal format:
```toml
#Format: [["item_id", temperature, max temperature, strict_type, trait,  *nbt], ...etc]
"Carried Item Temperatures" = [["minecraft:torch", 0.15, 0.15, "hand", "world"], ["..."]]
```

Hope that makes sense. Thanks again and amazing work on the mod!

**Comment by MikulDev** [comment]
I see. I could definitely make these options available in the config. I would probably just roll them both into a "max temperature" argument, since it would accomplish both things.

**Comment by dandalous** [comment]
I agree. Could probably make it an array so it doesn't break existing configurations. It being uncapped by default if the temperature value is only one item in the array. Or just append it as an optional value. Whichever works best for you.

```toml
#Format: [["item_id", [temperature range], strict_type, trait,  *nbt], ...etc]
"Carried Item Temperatures" = [["minecraft:torch", [0.15, 0.15], "hand", "world"], ["..."]]
```

**Comment by MikulDev** [comment]
If it becomes an array, then it would break existing configs because it would be expecting an array, and finding a decimal. Putting an optional sixth element would be better for backward compatibility.

**Comment by dandalous** [comment]
Gotchya. Works great, thank you!
