### ISSUE TITLE
WATER

### ISSUE THREAD

**Issue by GogUwU** [Momo-Studios/Cold-Sweat-Rework-Forge#349]
neoforge 47.1.106
 minecraft1.20.1

mods installed only coldsweat

place any block on top of any liquid and then break block and you will get water

https://github.com/user-attachments/assets/2d83958d-42da-4ba2-b356-5e28d28fbdb3

**Comment by MikulDev** [comment]
Thanks for the report. This will be fixed in the next version.

**Comment by GogUwU** [comment]
thx, also how did this even happend? XD

**Comment by MikulDev** [comment]
When you break ice, it drops water; but basically, some faulty logic in my code made it so that every block drops water.
