### ISSUE TITLE
Hearth Crash V2.3.1

### ISSUE THREAD

**Issue by TreyR9** [Momo-Studios/Cold-Sweat-Rework-Forge#350]
When placing redstone dust behind and one block down from a hearth (as displayed), the game immediately crashes. 

![2024-08-23_03 21 52](https://github.com/user-attachments/assets/c3b987de-477d-4b2a-bd7b-2a103a45ebd1)

Fresh instance, no mods other than Cold Sweat. Crash report below:
[crash-2024-08-22_22.29.26-client.txt](https://github.com/user-attachments/files/16721621/crash-2024-08-22_22.29.26-client.txt)
Minecraft Version: 1.18.2
Forge Version: 40.2.0
Mod version: 2.3.1

**Comment by MikulDev** [comment]
Gotcha. This will be fixed in the next version
