### ISSUE TITLE
Crash adding hoglin hide to modded leggings

### ISSUE THREAD

**Issue by Vertex02** [Momo-Studios/Cold-Sweat-Rework-Forge#351]
I'm currently playing the Steampunk [LPS] modpack on curseforge. It has Cold and sweat version 2.3-b03d. If I put hoglin hide into a sewing table with these Grave Metal Leggings, My game completely crashes. Siting exit code -805306369. It works just fine with the other pieces of Grave metal armour. I also was clearly able to put at least two insulation on the leggings before the issue started happening. However, I am unable to put more on now. 

I also tried with some chain mail leggings and that crashed my game too. It seems to crash on other armour occasionally, but every time with the gravemetal leggings.  
![image](https://github.com/user-attachments/assets/1f8b30e2-d387-4a87-9388-f92ac28fb5fa)

**Comment by Vertex02** [comment]
I also just tested with a new pair of gravemetal leggings and it works just fine. I wonder whether the first one's data got corrupted somehow.

**Comment by Vertex02** [comment]
And now I've crashed just opening the sewing table ¯\_(ツ)_/¯
[crash-2024-08-23_13.28.38-server.txt](https://github.com/user-attachments/files/16723062/crash-2024-08-23_13.28.38-server.txt)

**Comment by MikulDev** [comment]
Try updating the mod and see if it still crashes. The version Steampunk has is a bit outdated
