### ISSUE TITLE
Game crashes when I change difficulty

### ISSUE THREAD

**Issue by FinnArt** [Momo-Studios/Cold-Sweat-Rework-Forge#355]
[crash-2024-08-25_16.49.13-client.txt](https://github.com/user-attachments/files/16741930/crash-2024-08-25_16.49.13-client.txt)
I've been trying to change the difficulty in one of my worlds, but when I try it saves and the game crashes. I attached the crash lo, hopefully it helps

**Comment by MikulDev** [comment]
This bug was fixed in 2.3.2- however there is an additional fix coming out shortly that addresses some other issues with the mod.
