### ISSUE TITLE
魂火灯不消耗燃料。（Soulspring Lamp consumes no fuel.）

### ISSUE THREAD

**Issue by 7yudinglaopin8** [Momo-Studios/Cold-Sweat-Rework-Forge#358]
在下界使用魂火灯时，燃料保持64/64，不会消耗。
When using the Soulspring lamp, the fuel remains 64/64 and will not be consumed.

**Comment by MikulDev** [comment]
Thank you for reporting this. This issue will be fixed in the next version.
