### ISSUE TITLE
[1.18][ColdSweat-2.1.9.jar] Weird Nether and Mod questions.

### ISSUE THREAD

**Issue by ffuentesm** [Momo-Studios/Cold-Sweat-Rework-Forge#36]
Ok so I am using this mod for the first time, and I feel the biome temperature is kind of weird.
I am using Insulated armor, and I am currently in the nether, not using the hellfire lamp, but for some reason is VERY cold there. 
![image](https://user-images.githubusercontent.com/44974827/160008626-95e8f769-bfa3-4c05-b162-6d0adfb1cef2.png)

Also, when I am in the overworld, in a forest biome, around 70 in the Y level, during the day, for some reason the temperature drops very fast. Even with the insulated armor. 
And lighting a fire or being next to a campfire does nothing to that. 

I just feel we could get a clearer mod explanation. 
I read the wiki but I am still confused.

**Comment by MikulDev** [comment]
I've heard reports of the world being extremely cold from other people as well. Trust me, it's not supposed to be like that (the Nether should be about 130 °F / 54 °C). I'm looking into it right now.

**Comment by MikulDev** [comment]
I've found the problem. It will be fixed in 2.1.9.2 later today
