### ISSUE TITLE
转载WIKI上的内容到"www.mcmod.cn"

### ISSUE THREAD

**Issue by Minecraft0122** [Momo-Studios/Cold-Sweat-Rework-Forge#360]
我希望将冷汗WIKI上的内容转载到中国的MC百科（www.mcmod.cn），以便让更多中国玩家知道模组的用法和玩法。为了遵循版权规定和MC百科的编辑政策，我需要获得冷汗的正式许可。由于中国对访问外网的限制，我无法合法的连接到discord，同时在中国访问GitHub也非常不稳定，有的地区无法连接或连接的非常缓慢。因此，能否使用别的方法询问是否可以允许我转载WIKI上的内容

**Comment by MikulDev** [comment]
Of course! You have my written consent to publish information about Cold Sweat to the wiki. I would even appreciate it if you did so!

**Comment by Minecraft0122** [comment]
> 答案是肯定的！您已获得我的书面同意，可以在 wiki 上发布有关 Cold Sweat 的信息。如果您这样做，我将不胜感激！

感谢您的支持，还有一个问题就是，新加入的物品"Smokestack"我是否可以翻译成“烟囱”（因“译名需来自官方或大型社区汉化团队，不可擅自随意添加”）

**Comment by MikulDev** [comment]
Yes, that would be alright. Here are the full translation files for Simplified Chinese and Traditional Chinese, in case you need any more information about translation. 
[zh_cn.json](https://github.com/user-attachments/files/16839324/zh_cn.json)
[zh_tw.json](https://github.com/user-attachments/files/16839325/zh_tw.json)
