### ISSUE TITLE
在尝试调整游戏难度时发生了错误

### ISSUE THREAD

**Issue by Minecraft0122** [Momo-Studios/Cold-Sweat-Rework-Forge#362]
[错误报告-2024-9-4_22.35.44.zip](https://github.com/user-attachments/files/16872639/-2024-9-4_22.35.44.zip)
在游戏界面内调整游戏难度时发生了错误

**Comment by MikulDev** [comment]
This issue is the same as #357. Another program is trying to use the config file, so Cold Sweat fails to save data to it.
