### ISSUE TITLE
[1.18.2 / CRASH] Cold Sweat crashes AttributeFix during FML loading

### ISSUE THREAD

**Issue by ghost** [Momo-Studios/Cold-Sweat-Rework-Forge#363]
Game crashes on startup with latest version of Cold Sweat. The crash log blames CodeChicken Lib for being the cause.
Linked here https://gist.github.com/CatzRule81/8dca68fd611d5bafecf104f0cd7cdaa9

Hoping for a response soon. Thanks for any help in advance.

**Comment by MikulDev** [comment]
What mod(s) are you using that depend on CodeChicken? I can't reproduce this with just Cold Sweat and CodeChicken installed.

**Comment by ghost** [comment]
- Draconic Evolution
- Brandon's Core (DE dependency)
- Thermal Expansion

It's most likely to be DE since it has its own shaders for the 1.16/1.18 shields.

**Comment by ghost** [comment]
@MikulDev hello?

**Comment by MikulDev** [comment]
I cannot recreate this issue with any of the provided mods. Are you sure this is a conflict caused by Cold Sweat in particular?

**Comment by ghost** [comment]
The crash only started occurring when Cold Sweat was added to my modpack. If it's not CodeChicken, it's something else. But it is Cold Sweat.

I did search around the issues page to see if anyone else had similar issues and I found some other topics covering non-1.18 versions though, do Embeddium or Create have known incompatibilities with Cold Sweat at this time?

**Comment by MikulDev** [comment]
Embeddium I'm not sure about, but I've taken special care that it's compatible with Create.
If it's possibly not CodeChicken, then I will need more information on what the true culprit is before I can help debug this issue.

**Comment by ghost** [comment]
I'll start checking around on my end in an hour or so

**Comment by ghost** [comment]
@MikulDev Crash persists in Cold Sweat v2.3.4.
However, disabling Embeddium changes the cause of the crash from a JVM-level crash while loading resource packs. (via EXCEPTION_ACCESS_VIOLATION) This crash **doesn't occur when both Embeddium and Cold Sweat are disabled,** so I think we found our culprit.

**Comment by ghost** [comment]
I've uploaded my debug.log of the crash in question here:
https://gist.github.com/CatzRule81/e2d194c745232aa2fef2119ea013556f

The JVM/JRE crash notification in the log:
![image](https://github.com/user-attachments/assets/77c9d661-363c-42f8-a154-34015a4ee08c)

And finally, here's the Java error report file uploaded to Gist as well:
https://gist.github.com/CatzRule81/23ff7c6e2a3fd3036a1d42503428d40a

**Comment by MikulDev** [comment]
According to the log. I actually found that Adventure Clothes was throwing an error that might have a domino effect on the mod loading process. It relies on a very old version of Cold Sweat, and the current version doesn't have the code it's looking for. Try removing it and see what happens

**Comment by ghost** [comment]
Will try that later today. If it works I'll reach out to the authors of that mod to see if changes can be made.

**Comment by ghost** [comment]
The JRE no longer crashes, however Cold Sweat still crashes even without Embeddium being enabled. Crash log of test with Cold Sweat w/o Embeddium attached. Forge is still blaming CodeChicken Lib for causing the crash despite your previous findings pointing toward this not being the case.
https://gist.github.com/CatzRule81/e0c966dadcdbcb3d3657a7d6eb5e5479

I'm going to test a few other mods which may be the culprit, will let you know if I find anything.
_EDIT: Not going to update the issue title this time. Waiting until the actual source of the problem is identified._

**Comment by ghost** [comment]
I decided to disable a few mods that alter Minecraft's loading process (Better Loading Screen and Smooth Boot Reloaded) and uhh...**oh dear god this is worse than I at first thought.**
![image](https://github.com/user-attachments/assets/74e93121-7ed3-45b9-ab8a-4f7a6b426fa3)

Somehow Cold Sweat's attributes are causing AttributeFix to crash on trying to load. I tried deleting AttributeFix's configuration to see if it fixes the problem, and I got this error instead.
![image](https://github.com/user-attachments/assets/3c85cdac-631b-48a8-afbe-445df39b9ea4)

Looking at AttributeFix's **regenerated** configuration, the problem quickly becomes evident in that it's unable to properly complete generating its configuration file, stalling out at line 82 when attempting to process Cold Sweat's attributes.
![image](https://github.com/user-attachments/assets/92c4c6d6-db79-4e52-ae2b-ed99ad1e9b5a)

I'm sure you already know what AttributeFix is, but in case you don't, AttributeFix is a Forge mod that removes or significantly increases the maximum caps on many Vanilla attributes, allowing armor points to exceed 30, entities' max health to exceed 2000 (1000 hearts), and more. Since it's so widely used, especially by modpack creators **and the authors of larger mods such as Draconic Evolution, Twilight Forest, and more,** Cold Sweat is essentially incompatible with **everything** until this is fixed.

Deleting AttributeFix's config and relaunching without Cold Sweat enabled stops the crash from occurring.

**Please make this your team's top priority to fix as soon as possible. Incompatibility with AttributeFix goes much further than incompatibility with a single mod.**

**Comment by ghost** [comment]
For those who came in late, me and Mikul talked about this on Discord. I've opened a thread regarding this on AttributeFix's GitHub page here.
https://github.com/Darkhax-Minecraft/AttributeFix/issues/57
