### ISSUE TITLE
ad astra support

### ISSUE THREAD

**Issue by Foxsik193** [Momo-Studios/Cold-Sweat-Rework-Forge#364]
T-69 says -173 degrees Celsius on the moon. And Cold Sweet 10.

**Comment by MikulDev** [comment]
I'm not sure what this means...

**Comment by Foxsik193** [comment]
![Снимок экрана 2024-09-08 142947](https://github.com/user-attachments/assets/13b3a85e-2d01-4c0c-94a3-53ea20b57b0c)

**Comment by Foxsik193** [comment]
in the lower left corner is the temperature from your mod, and in your hand is the device from the ad astra mod

**Comment by MikulDev** [comment]
Ok, I see. In world_settings.toml, you can add this dimension and set its temperature to something that is more accurate.

I believe there is a community member working on Ad Astra support that makes the temperatures of the planets more realistic, among other things.
