### ISSUE TITLE
[1.19.2 - Crash] Incompatibility between ColdSweat and Curios

### ISSUE THREAD

**Issue by Ingotine** [Momo-Studios/Cold-Sweat-Rework-Forge#366]
Tried this with backpacks, not sure if its backpack specific or any curio compatible item. 

Sophisticated backpacks vs traveler's backpacks:
[crash-2024-09-08_14.34.31-client.txt](https://github.com/user-attachments/files/16923293/crash-2024-09-08_14.34.31-client.txt)
[crash-2024-09-08_14.12.13-client.txt](https://github.com/user-attachments/files/16923294/crash-2024-09-08_14.12.13-client.txt)

**Comment by MikulDev** [comment]
This is between Cold Sweat and Legendary Tooltips; not Curios. You also appear to be using an outdated version of that mod. If you update, the issue should be resolved.
