### ISSUE TITLE
Crash while Loading 1.16.5

### ISSUE THREAD

**Issue by Roboowe** [Momo-Studios/Cold-Sweat-Rework-Forge#367]
Tested using curseforge launcher with no other mods on 1.16.5, always get error: "Cold_Sweat (cold_sweat) encountered an error during the load_registries event phase".

Seems to only affect cold sweat versions 2.3.3 and 2.3.2. Just switching to earlier version for now, not sure if it is a issue relating to just my system or the mod.

[crash-2024-09-09_22.29.40-fml.txt](https://github.com/user-attachments/files/16930474/crash-2024-09-09_22.29.40-fml.txt)

**Comment by MikulDev** [comment]
This issue has been fixed internally, and will be addressed in the next version
