### ISSUE TITLE
Issue when entering worlds

### ISSUE THREAD

**Issue by nosivaste** [Momo-Studios/Cold-Sweat-Rework-Forge#368]
every time i log into a world it adds another point of insulation to all the insulator, when it goes high enough the worlds crash when trying to load, this happens with only Cold Sweat installed and no other mods, this is using the latest version of the mod for 1.20.1 at the time of writing this issue

**Comment by MikulDev** [comment]
Thanks for the report. I've found the source of the issue and it will be fixed in the next version.
