### ISSUE TITLE
insulation probble 

### ISSUE THREAD

**Issue by sharpshooter1944** [Momo-Studios/Cold-Sweat-Rework-Forge#369]
i found some troble like in cave deep down it freezing or hot deppen on the biom weather  normaly cave will insulate like stable at 25 c  can u solve it ?

**Comment by MikulDev** [comment]
This is definitely strange. Cold Sweat does have a new system of calculating this in the most recent versions, but I haven't had any problems with it so far. Can you run `/temp debug @s world` and take a screenshot? This will give me some more information on how your temperature is being affected and where it might be going wrong.

**Comment by sharpshooter1944** [comment]
![2022-07-14_17 15 16](https://github.com/user-attachments/assets/5ca7222a-4885-4a8a-a738-c7301810b746)
like this ?

**Comment by sharpshooter1944** [comment]
![2024-09-17_18 36 28](https://github.com/user-attachments/assets/5b056f2d-4c79-4b30-b984-3814720effe2)
like this one ?

**Comment by MikulDev** [comment]
Yes, that's it. I did some more testing and was finally able to recreate the issue. Turns out it's because the "insulation" underground simply isn't applying because it doesn't think the player is in a valid dimension. This was a pretty easy fix.

**Comment by sharpshooter1944** [comment]
oh okay that good to hear that and thank for attention and ur work i wait till it next update
