### ISSUE TITLE
Cold-Sweat config crash in modpack

### ISSUE THREAD

**Issue by Dreassil** [Momo-Studios/Cold-Sweat-Rework-Forge#37]
Hi! So my game crashes anytime I try to edit items or biomes in this mod ingame.

Here are the crashes (mod list is inside):
[crash-2022-03-24_18.40.44-client.txt](https://github.com/Momo-Studios/Cold-Sweat/files/8345838/crash-2022-03-24_18.40.44-client.txt)
[crash-2022-03-24_19.21.09-client.txt](https://github.com/Momo-Studios/Cold-Sweat/files/8345839/crash-2022-03-24_19.21.09-client.txt)

Here are the config (I just converted them to txt):
[world_temperatures.txt](https://github.com/Momo-Studios/Cold-Sweat/files/8345844/world_temperatures.txt)
[item_settings.txt](https://github.com/Momo-Studios/Cold-Sweat/files/8345845/item_settings.txt)

Hope you can help guys ^^

**Comment by MikulDev** [comment]
I think that the MrCrayfish mod that you are using to edit configs is conflicting with Cold Sweat. I will implement a failsafe for this issue, but for now I'd suggest not using that mod to edit Cold Sweat configs.

**Comment by MikulDev** [comment]
I've hopefully addressed the issue in the latest update for Cold Sweat. If the problem persists, please show me the crash report again so I can diagnose further
