### ISSUE TITLE
Beautiful Campfires Compatibility

### ISSUE THREAD

**Issue by ThisOneMadow** [Momo-Studios/Cold-Sweat-Rework-Forge#371]
Hello!
I noticed that the Soul Campfires from the [Beautiful Campfires Mod](https://www.curseforge.com/minecraft/mc-mods/beautiful-campfires) aren’t working like the vanilla ones with Cold Sweat (they produce heat instead of cold.)

I’ve tried adjusting the world_settings config under the "Blocks" sub-category to make them produce cold, but no success.

Here’s an example of what I did for each soul campfire:
["bc:spruce_soul_campfire", -0.15, 7, 0.6, "lit=true", " ", 8], ["bc:bamboo_soul_campfire", -0.15, 7, 0.6, "lit=true", " ", 8] etc.
(Yes, I copied the temperature from the ice block to test it, lmao)

I suspect the setting for #minecraft:campfires might be overriding all the campfires I added. 

Any help would be appreciated! Thanks :D

_(Oh and the Cave Insulation might... not.. be working properly... in the newest update)_

**Comment by MikulDev** [comment]
If you put these settings in after the `#minecraft:campfires` setting, then you are probably correct in that they are being overridden. If you want to prevent this, put your custom settings before `#minecraft:campfires`, and they should take precedence. Cold Sweat now has a specific load order, and the first matching config is used to determine the temperature of a block.

**Comment by ThisOneMadow** [comment]
Alright, ty sm!
It works now. Can't believe I didn't thought about that.
Ty again!

**Comment by MikulDev** [comment]
Nice! No problem
