### ISSUE TITLE
Compatibility issue between Cold Sweat and Spoiled

### ISSUE THREAD

**Issue by pasavec008** [Momo-Studios/Cold-Sweat-Rework-Forge#372]
I've encountered a compatibility issue between the Spoiled mod and Cold Sweat. Specifically, custom Spoiled config rules for different containers don't seem to function correctly while Cold Sweat is installed. From my testing, it appears that the presence of Cold Sweat overrides or disrupts the custom spoilage rules set in Spoiled. Cold Sweat should have built-in support for Spoiled and I love both mods so it would be great if it could be fixed! :)
How to reproduce:
1. Have both mods installed (Spoiled + Cold Sweat)
2. Put vanilla food into both normal chest and shulker box (as default Spoiled configuration should ensure that food is not spoiling in shulker boxes)
3. Food is still spoiling in shulker boxes (if we remove Cold Sweat, everything works fine)

**Comment by MikulDev** [comment]
You're right. The currently implemented compat that Cold Sweat has for Spoiled has to hook into this spoiling mechanic to work properly, and it's having this unintended side-effect on other containers. This will be fixed in the next update.
