### ISSUE TITLE
Insulation on armour impossible in latest version?

### ISSUE THREAD

**Issue by BRUHHHa** [Momo-Studios/Cold-Sweat-Rework-Forge#373]
![Cold sweat github issue](https://github.com/user-attachments/assets/a701facd-0ef6-432a-8816-715948bffa54)

I don't understand what's happening here, none of the mods I am using are interfering with cold sweat.

**Comment by MikulDev** [comment]
Make sure your configs are set correctly. Does the leather helmet have a tooltip showing that it gives insulation?

**Comment by BRUHHHa** [comment]
I have no idea how I fixed it, but it seems to work now, the leather helmet, and the other armours with built-in insulation, were showing on the tooltip, however now it seems as though it must have been the wrong tooltip, as I remember it, it was showing +20 something on the leather insulation. Any way, I solved it somehow.
