### ISSUE TITLE
Place the mouse over an item in some other mod,the game not responding.

### ISSUE THREAD

**Issue by 7yudinglaopin8** [Momo-Studios/Cold-Sweat-Rework-Forge#374]
Place the mouse over an item in some other mod like Re:Avaritia,DivineRPG and so on,the game not responding.
Then I can't do anything.
[crash-2024-09-15_21.12.05-client.txt](https://github.com/user-attachments/files/17078291/crash-2024-09-15_21.12.05-client.txt)

**Comment by MikulDev** [comment]
Does this happen in a smaller setup with just a couple mods installed? I think another mod might be the culprit here.

**Comment by 7yudinglaopin8** [comment]
> Does this happen in a smaller setup with just a couple mods installed? I think another mod might be the culprit here.



> Does this happen in a smaller setup with just a couple mods installed? I think another mod might be the culprit here.

What does "Does this happen in smaller Settings" specifically mean?

And I installed about 250 mods.

**Comment by MikulDev** [comment]
I mean you should try making a pack with just a few mods and see if the issue persists.

**Comment by 7yudinglaopin8** [comment]
> I mean you should try making a pack with just a few mods and see if the issue persists.

OK

**Comment by 7yudinglaopin8** [comment]
[crash-2024-09-26_19.21.23-client.txt](https://github.com/user-attachments/files/17147419/crash-2024-09-26_19.21.23-client.txt)
Only 2 mods installed.......................divineRPG and ColdSweet...

**Comment by 7yudinglaopin8** [comment]
The problem still exist.

**Comment by MikulDev** [comment]
I can't get this to happen with DivineRPG installed, but I will see what I can do to try to prevent the issue.
