### ISSUE TITLE
Added a stack of coal into the boiler, and now my world crashes when i join.

### ISSUE THREAD

**Issue by Destroyanad** [Momo-Studios/Cold-Sweat-Rework-Forge#375]
I shift-clicked a stack of coal into the boiler, my game froze, then minecraft saved then crashed. Anytime i boot up my world, it instantly crashes my game and gives these logs. Singleplayer, Minecraft Version 1.19.2, Forge Version 1.257.1

Server:
[crash-2024-09-21_14.58.47-server.txt](https://github.com/user-attachments/files/17085572/crash-2024-09-21_14.58.47-server.txt)
Client:
[crash-2024-09-21_14.49.15-client.txt](https://github.com/user-attachments/files/17085575/crash-2024-09-21_14.49.15-client.txt)

**Comment by MikulDev** [comment]
Thanks for letting me know. This will be fixed in the next version. For now, you can prevent this by setting the temperature rate to anything above 0.
