### ISSUE TITLE
Hearth Uncraftable 2.3.4 Neoforge

### ISSUE THREAD

**Issue by Visperus** [Momo-Studios/Cold-Sweat-Rework-Forge#377]
The Hearth is uncraftable apparently due to some Empty Tags as seen via EMI- forge:ingots/iron and c:ingots/nether_brick 
![123](https://github.com/user-attachments/assets/bc9b546c-4197-45b1-a23c-350e1ed3ec85)
![1234](https://github.com/user-attachments/assets/1f291501-3baa-4b22-ba26-fe935d96da6c)

**Comment by MikulDev** [comment]
This is a confirmed issue. It will be fixed in 2.3.5
