### ISSUE TITLE
Cave insulation isn't work (?)

### ISSUE THREAD

**Issue by tr1kright** [Momo-Studios/Cold-Sweat-Rework-Forge#379]
![image](https://github.com/user-attachments/assets/3c1e018d-9904-466a-81f6-cd462c45ce80)

This is the latest version of the mod and since I don't know what information to give you, I'll throw in what I find (sry, my english is so bad)
[latest.log & debug.log](https://gist.github.com/tr1kright/0cec76d68e739751ea26a50b4d3ab695)

**Comment by MikulDev** [comment]
This is a confirmed issue. It will be fixed in 2.3.5

**Comment by pasavec008** [comment]
Hello, was this fixed? as on local world it works fine for me, but on server there is no underground insulation (it is even the same map) .. both have cave insulation config value on 1.0
(forge, 1.20.1, mod version 2.3.5)
![image](https://github.com/user-attachments/assets/74a5252e-616e-48ec-977c-767d0f980ecd)
![image](https://github.com/user-attachments/assets/85f05d36-fcdb-474f-bd8a-c119567b1817)
