### ISSUE TITLE
It doesnt show the temperature

### ISSUE THREAD

**Issue by noquw** [Momo-Studios/Cold-Sweat-Rework-Forge#382]
for some reason it doesnt show the temperature if im getting cold or hot
![image](https://github.com/user-attachments/assets/687bb169-e643-4117-9626-739d824a791c)
![image](https://github.com/user-attachments/assets/eb6bc925-858b-442c-a84d-5d9b90facb5e)

**Comment by ThisOneMadow** [comment]
The temperature display only appears when you have a Thermometer from the mod in your **main hotbar, offhand**, or in a Curios slot _(if the Curios API mod is installed)_.
