### ISSUE TITLE
Crashing when insulating armor

### ISSUE THREAD

**Issue by SamuraiSal1224** [Momo-Studios/Cold-Sweat-Rework-Forge#386]
So, I was playing on my custom modpack with Coldsweat and a few other mods installed. Everything worked as normal, nothing out of the ordinary. Until, I insulate my clothing. I insulate it, and everything again, works fine. Until I hit escape, which saves autosaves the game. At that point, immediately my entire game crashes, back to desktop, with the following error: 

The game crashed whilst saving entity nbt
Error: java.lang.IllegalStateException: some keys are not strings: [{data:{components:{},items:["minecraft:leather_boots"]},insulation:{cold:4.0d,heat:4.0d},slot:"item"}]

[Crash File Cold Sweat.txt](https://github.com/user-attachments/files/17304578/Crash.File.Cold.Sweat.txt)

I removed any mods I had thought were conflicting, like Vic's Point Blank firearms, but the issue has still occured. I am stuck. Help would be appreciated.

**Comment by MikulDev** [comment]
Duplicated by #389. This will be fixed in the next update
