### ISSUE TITLE
Configuration Issue

### ISSUE THREAD

**Issue by P4YN-Ki** [Momo-Studios/Cold-Sweat-Rework-Forge#387]
Hey I have a server and client issue that seems to be similar.

Client - Even though I've disabled the water running down the face option, it's still happening. Like water is dripping off the character  when they are wet and I'm not sure why this is happening and it's infuriating.

Server - Temp Icons don't load their location from the Configs. The icons have been moved on the Client-Side and those same configs were put on the server. But the Icons return to their default position every time a client reconnects to the server.

Minecraft 1.20.1 - Server issue is also present on 1.21.1
NeoForge 47.1.106

I can provide any and all files you require, just let me know what you need. The server icons I can sort of live with, though irritating, but the water running down the face has got to go. Any help would be greatly appreciated.

**Comment by MikulDev** [comment]
Client - The setting you're talking about disables the screen animation; not the particles. I didn't think those would be so annoying. 

Server - Just to be sure of a couple things: client configs don't do anything on servers, they must be changed on the client. Also, this issue sounds similar to a bug that was already patched, so make sure you're on the latest version. If those two things aren't an issue. I'll look into testing it out

**Comment by P4YN-Ki** [comment]
Hey, thanks for hte quick reply.

I'm on the latest version for the version of MC I'm playing (Cold Sweat 2.3.5) which is 1.20.1. Is there anyway for me to go into the mod and disable the particles? I don't want to lose the mod or have to update the MC version since I've just gotten all the mods to work nicely together.

**Comment by MikulDev** [comment]
There currently isn't a way to disable the particles themselves, as they would be the only indicator that the player is wet. If you have something like OptiFine installed, you could disable that particle specifically
