### ISSUE TITLE
Unable to save once the player creates Insulated Armor (Minecraft Version 1.21 & 1.21.1) (Mod Version 2.3.5)

### ISSUE THREAD

**Issue by MEKNOWKNOOB** [Momo-Studios/Cold-Sweat-Rework-Forge#389]
### Installed Mods (1)

- ColdSweat Version (2.3.5)

### Summary of Issues

- When saving the game with insulated armor currently in inventory or equipment, Minecraft crashes.
- When storing armor in storage/containers such as chests, Minecraft will lose the entire storage data and make storage invisible. However, this does not result in a crash nor a crash-log.
- As long the escape menu is not pressed, the game technically runs continuously
- Multiplayer servers will also encounter the same problem, however instead of crashing, the server will fetch the most recent save state where the player has no insulated armor in inventory when logging back in

### Crash Log Breakdown

- Unable to save components related to ColdSweat leading to a crash, such as: 
````
cold_sweat:armor_insulation=>ItemInsulationCap[insulation=[(1 minecraft:light_gray_wool, [Insulator[insulation=Insulation{cold=1.5, heat=0.0}, slot=ITEM, data=ItemRequirement{minecraft:light_gray_wool, NBT: ItemComponentsRequirement[components={}], }, predicate=EntityRequirement{}, attributes=com.momosoftworks.coldsweat.data.codec.util.AttributeModifierMap@635d9eca, immuneTempModifiers={}]=[Insulation{cold=1.5, heat=0.0}]])]
````

### Crash Logs

[crash-2024-10-13_23.12.07-server.txt](https://github.com/user-attachments/files/17359007/crash-2024-10-13_23.12.07-server.txt)

**Comment by MikulDev** [comment]
This is a known issue with 1.21. It will be fixed in the next update soon
