### ISSUE TITLE
cold-sweat crashing modpack

### ISSUE THREAD

**Issue by nagaisa** [Momo-Studios/Cold-Sweat-Rework-Forge#39]
[latest.log](https://github.com/Momo-Studios/Cold-Sweat/files/8367395/latest.log)
this is my log. everything seams to work without it on (tho some mods where not working but i fixed them)

**Comment by MikulDev** [comment]
I think this might be a mod incompatibility, but the log isn't saying what it is. I can try to fix this in 2.1.9 for 1.16.5.
