### ISSUE TITLE
[Suggestion] Ability to revert ice/packed ice block breaking behaviour to vanilla

### ISSUE THREAD

**Issue by rafaelkai** [Momo-Studios/Cold-Sweat-Rework-Forge#392]
As the title says, it would be nice to have the option. Other mods add mechanics to get ice blocks in other ways, like dropping ice shards when broken without silk touch.

**Comment by MikulDev** [comment]
I agree this should be a setting. I wasn't able to find a way to do it before, because it relied heavily on mixins which can't be disabled, but I managed to modify the system so that it is now possible to disable. Expect to see this setting in 2.3.6!
