### ISSUE TITLE
[Suggestion] Create New Age heat systems compatibility

### ISSUE THREAD

**Issue by rafaelkai** [Momo-Studios/Cold-Sweat-Rework-Forge#393]
Create New Age adds some systems that allow to spread heat like heat pumps, heat pipes and solar plates. It would be nice if Cold Sweat could support this system and dectected when the system is generating heat.

**Comment by MikulDev** [comment]
It would be a lot easier if the compat was added the other way around, I think. Cold Sweat's code is extensively documented, which would make it much easier for them, but I would have to dig through their code and figure out how the mod works in order to add compat on my side.

**Comment by rafaelkai** [comment]
Fair point, I'll forward the request to them.
