### ISSUE TITLE
Cave insulation is working only locally, not on server

### ISSUE THREAD

**Issue by pasavec008** [Momo-Studios/Cold-Sweat-Rework-Forge#395]
Hello, cave insulation is not working on my server .. which is weird, because it works locally (it is even the same map) .. both world have in config Cave Insulation Strength value set to 1.0 .. any ideas what could be the problem?
EDIT: Maybe it can be issue with world settings config file as I copied whole map?
Server:
![image](https://github.com/user-attachments/assets/feec657a-a83e-4b24-b920-10928ff627bc)

Local:
![image](https://github.com/user-attachments/assets/578c764e-8754-4176-9584-87ce1e9bb32b)

**Comment by MikulDev** [comment]
I tested this and can confirm it's an issue. It's because Cold Sweat's custom tags don't load properly on servers. I will have this fixed in 2.3.6
