### ISSUE TITLE
[Compat] Incompatibility with Mindful Darkness

### ISSUE THREAD

**Issue by rafaelkai** [Momo-Studios/Cold-Sweat-Rework-Forge#396]
As the title says, Cold Sweat's GUIs don't turn into dark mode when using Mindful Darkness.

**Comment by MikulDev** [comment]
Did you add Cold Sweat's GUIs to their config? According to the mod page:
> Mindful Darkness does not automatically darken every gui texture in the game, instead you have to manually specify in the config which textures are affected. Resources can be specified using '*' as wildcard char, can affect all or just a single namespace and you can use '!' to exclude resources.

**Comment by rafaelkai** [comment]
Which texture paths should I add to support Cold Sweat GUIs?

**Comment by MikulDev** [comment]
This directory contains all GUI elements in Cold Sweat:
[assets/cold_sweat/textures/gui](https://github.com/Momo-Softworks/Cold-Sweat/tree/1.20.1-FG/src/main/resources/assets/cold_sweat/textures/gui)

**Comment by rafaelkai** [comment]
Thanks for the tooltip, it worked!

**Comment by MikulDev** [comment]
You'll need to ask for support from their end, then. I don't know how the mod works

**Comment by rafaelkai** [comment]
It works now, the issue can be closed
