### ISSUE TITLE
[Suggestion] Allow other season mods to provide season registration procedures or support related configuration.

### ISSUE THREAD

**Issue by joe-vettek** [Momo-Studios/Cold-Sweat-Rework-Forge#397]
Cold Sweat is a great and immersive mod, but unfortunately it only supports Serene Seasons and is a bit coupled.

Not sure if it will be possible to add other seasons.

**Comment by MikulDev** [comment]
Adding support for mods wouldn't be as simple as a config, if that's what you're implying. Every mod has its own systems, and Cold Sweat needs to directly reference their code to know the current season and other info. 

Cold Sweat has a very open and well-documented API, so adding support for mods with Java would be relatively simple as far as modding goes. The SereneSeasonsTempModifier class provides a good blueprint for this as well.

**Comment by joe-vettek** [comment]
oh i see, thank you. The reason I had doubts was that I had seen a mod before that created a dedicated item for this, which led to my misunderstanding.

**Comment by joe-vettek** [comment]
This blueprint is a bit confusing to me, I'm not sure when the TempModifier was added. 
Should I add the missing modifiers myself? Although I have completed the registration.
But getModifiers(Trait.WORLD) I will find that I can't get the modifiers I registered.

**Comment by MikulDev** [comment]
Did you add them to the player? TempModifiers aren't automatically applied by default. If you want your TempModifier to be added as soon as the player spawns, look into GatherDefaultTempModifiersEvent

**Comment by joe-vettek** [comment]
I had not found this code before, I did so by searching for code references to Serene Seasons, which led me to nowhere.

**Comment by joe-vettek** [comment]
Now it should work, btw Cold Sweat handling whether it is raining in the area well so I don't have to add more Mixins.
