### ISSUE TITLE
[Forge 1.20.1] Causes player ticking error on server when player enters water.

### ISSUE THREAD

**Issue by OozyLucy** [Momo-Studios/Cold-Sweat-Rework-Forge#398]
When a player enters water when playing on a dedicated server with the mod installed it causes a player ticking error and kicks them, it does this every time they join.

![image](https://github.com/user-attachments/assets/22802c58-45de-414b-ac62-e70e35188a96)

https://mclo.gs/fy2ZT8j

**Comment by rafaelkai** [comment]
Same issue here.

**Comment by MikulDev** [comment]
This issue will be fixed in the next version. Thanks for reporting.
