### ISSUE TITLE
Incompatibility with "Sanity: Descent in to Madness" [1.19.2]

### ISSUE THREAD

**Issue by Allomere** [Momo-Studios/Cold-Sweat-Rework-Forge#399]
If you have Sanity's high contrast from lower sanity values while also affected by the overheat's blur/fog the screen goes black:
![2024-10-24_16 55 43](https://github.com/user-attachments/assets/e2f4f7dc-f8de-4e21-af16-39b0ab3c8b46)

If you switch perspectives the issue goes away and the fog is applyed correctly on first person:
![2024-10-24_16 56 02](https://github.com/user-attachments/assets/5cfc11b2-fb24-41c4-890e-ac9010e5631d)

Video Example:
https://github.com/user-attachments/assets/25f4c23c-67bf-4ad4-9154-3e9b1e9e9044

**Comment by MikulDev** [comment]
I have now re-written Cold Sweat's shader system for 2.3.7, since this is nowhere near the first issue related to shader interaction between mods. I tested it myself and this issue does not appear to happen with the new system in place. Hope it works for you

**Comment by Allomere** [comment]
Will this version come to 1.19.2 ?

**Comment by MikulDev** [comment]
Yes. I'm pretty busy at the moment but I'll port it to the other versions when I can
