### ISSUE TITLE
Compatibility with Regions Unexplored biomes

### ISSUE THREAD

**Issue by TheButterbrotMan** [Momo-Studios/Cold-Sweat-Rework-Forge#404]
It would be great if Cold Sweat could add compatibility for the biomes added by the Regions Unexplored mod. Regions Unexplored adds over 70 new biomes to Minecraft, significantly expanding world generation. Adding temperature profiles for these new biomes would allow Cold Sweat's temperature system to work seamlessly in Regions Unexplored worlds.

Ideally, each new biome would have appropriate temperature ranges and effects defined to match its climate and characteristics. This would enhance immersion and survival gameplay when using both mods together.

**Comment by MikulDev** [comment]
Biomes from other mods will still technically work with Cold Sweat, their temperatures just might be a bit off if the mod developer didn't take the time to consider the temperature for each biome. They'll still be generally correct most of the time.

**Comment by MikulDev** [comment]
Closing this issue. If any of the temperatures of the biomes don't make sense, they are configurable. You could also ask the dev(s) of the mod to add Cold Sweat support.
