### ISSUE TITLE
Lava drop causes crash

### ISSUE THREAD

**Issue by TheBeginSunlight** [Momo-Studios/Cold-Sweat-Rework-Forge#405]
When lava flows down (like 1 bucket), game crushing (console says that this is ColdSweat).
Playing on latest (from 30.10.2024) version
.
By the way thanks for water fix :)

**Comment by MikulDev** [comment]
Can you send the crash report as an attachment?

**Comment by TheBeginSunlight** [comment]
[crash-2024-10-31_02.01.37-client.txt](https://github.com/user-attachments/files/17587033/crash-2024-10-31_02.01.37-client.txt)

**Comment by MikulDev** [comment]
This is the same as #407, so I will be closing this as well.
