### ISSUE TITLE
High Temperature CRASH minecraft

### ISSUE THREAD

**Issue by TheBeginSunlight** [Momo-Studios/Cold-Sweat-Rework-Forge#407]
When temperature rises in Nether or near at lava, game crush (above ~130 Celsius)
Using latest version 

Crash report:
[crash-2024-10-31_22.11.58-client.txt](https://github.com/user-attachments/files/17591005/crash-2024-10-31_22.11.58-client.txt)
)

**Comment by MikulDev** [comment]
This will be fixed in 2.3.8. For now, you can disable Distortion Effects in `client.toml` or backport to 2.3.6 or 2.3.5
