### ISSUE TITLE
Icebox bug on forge server [1.16.5]

### ISSUE THREAD

**Issue by TheNicePlayer** [Momo-Studios/Cold-Sweat-Rework-Forge#408]
Putting any cooler into the icebox using shiftclick on the server creates ghostitem or sometimes duplicates the stack.

Version of the mod: ColdSweat-2.3.7 (i noticed it on 2.3.6 too)

Forge version (both server and client): forge-1.16.5-36.2.42

**Comment by MikulDev** [comment]
What do you mean by "cooler"? Because in my testing, neither fuel nor waterskins duplicate when shift-clicking them into the icebox. Shift-clicking normal items around the inventory doesn't do anything abnormal either

**Comment by TheNicePlayer** [comment]
I mean fuel (snow, ice etc.). I tested it on a stable localhost server with no lag and only this mod installed. Everytime it creates a ghostitem like in a video.

https://github.com/user-attachments/assets/89a62575-96cc-4a72-9006-befaad818ffc

Normally it's not a problem, because the ghostitem ussually disapears but I'm planning on using it on heavy modded server where those ghostitems sometimes turn into regular items.

**Comment by MikulDev** [comment]
There must be some kind of external factor affecting this somehow, because I still can't replicate this issue. Using Forge 36.2.42 and only Cold Sweat 2.3.7, items shift-click just fine. 

https://github.com/user-attachments/assets/0fbab9cb-b188-4a0a-8624-25dfb9ccb7f9

**Comment by TheNicePlayer** [comment]
I have no idea what might be causing such a bug externaly, but i guess I'll try to find out. Thanks for help tho.
