### ISSUE TITLE
Weather, Storms & Tornadoes compatibility?

### ISSUE THREAD

**Issue by santacapra** [Momo-Studios/Cold-Sweat-Rework-Forge#409]
I saw this mod was compatible with Better Weather, although that mod is now discontinued, is or will this mod be compatible with Weather, Storms & Tornadoes? I think it would be really cool if it was :] thanks!

**Comment by MikulDev** [comment]
It has compat with that mod, yes. Rainstorms will make you damp, wind will cool you down, sandstorms heat you up, etc.

**Comment by santacapra** [comment]
Thank you! I was wondering since it didnt say it was compatible on the website. Might have to update that :p
