### ISSUE TITLE
Mixin errors when building as dependency (1.16.5-r2.1.3)

### ISSUE THREAD

**Issue by Asecave** [Momo-Studios/Cold-Sweat-Rework-Forge#41]
When I create a mod and add cold sweat as a dependency in the build.gradle I get Mixin errors. The first version where this issue starts occurring is r2.1.3. Every version prior to that works fine.
Log file (from r2.1.3) : [latest.log](https://github.com/Momo-Studios/Cold-Sweat/files/8484439/latest.log)

I like the concept of the mod and want to make an add-on which adds some items for the lategame.
I don't have a good feeling about starting development in an older version ._.

**Comment by MikulDev** [comment]
Thank you for pointing this out. We've been trying to make Cold Sweat as easy to work with as possible, so I'll make it a top-priority to fix this ASAP.

**Comment by MikulDev** [comment]
Update: I've imported your project (Cold Sweat Energized) from GitHub into a new IntelliJ project, and it builds, compiles, and runs with CS 2.1.8 without any modifications. 

I think this might have something to do with your IDE or setup in general. This is just a shot in the dark, but I found that including these two lines in the `runs` section of `build.gradle` (line 39-ish) fixes this kind of issue:
```
property 'mixin.env.remapRefMap', 'true'
property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
```

**Comment by Asecave** [comment]
That sadly didn't work (in eclipse). It's weird that it works with 2.1.2. But the mixin error isn't very helpful either. I think I have to tweak stuff till it works.

**Comment by MikulDev** [comment]
In regards to why it works in 2.1.2, in 2.1.3 I added the mixin that is causing the error in this case, but it unfortunately doesn't explain why it works for me and not for you. Very hard to diagnose that way. I'd remove it if I could, but it's important for detecting if players are underground. I'll try to find a workaround in the meantime as well

**Comment by MikulDev** [comment]
Update to the mixin situation: I am testing out some ways to mitigate the need for this particular mixin. A beta version will be up shortly (less than a day) that experiments with this idea. If you still have this issue, try importing that into your workspace when it releases and see what happens

**Comment by MikulDev** [comment]
I'm going to close this issue to further discussion and consider the problem fixed. If it still persists in the latest beta version, I'll reopen this issue and we can diagnose further.
