### ISSUE TITLE
Custom Hotbar shifts entire ui downward (1.20.1)

### ISSUE THREAD

**Issue by GoldeRuby** [Momo-Studios/Cold-Sweat-Rework-Forge#411]
i want to get this clear first: switching off the [Custom Hotbar] setting in the built-in config fixes this issue, but it took me a good while to figure out what exactly was the problem was to begin with

as the title says, having the Custom Hotbar enabled shifts the _entire_ ui downward by a few pixels
![image](https://github.com/user-attachments/assets/3cd287b8-7928-4efe-854a-9285d0fed664)
on its own, its not that serious of an issue, but it only _visually_ shifts down the ui, the actual buttons are where they normally are

however, the ui being moved seems to **significantly** disagree with REI
![image](https://github.com/user-attachments/assets/912b0f42-ac6b-470f-a8e6-332d898afad1)
again, the actual ui visuals are disconnected from the actual button locations

**Comment by MikulDev** [comment]
What mods are you using? This doesn't happen for me on a "Vanilla" instance, so it might be a conflict. I have an idea of what the issue is and how to solve it, but I don't know for sure.

**Comment by GoldeRuby** [comment]
> What mods are you using?

it very well could be a conflict, and wouldnt shock me if it is
unfortunately, the pack i made is 95 mods (counting dependencies)
could you maybe say what your idea is?
i think that would be easier than me dissecting through my folder to discern content from libraries to make a list

**Comment by MikulDev** [comment]
I would need all of your mods to do a proper test anyway, dependencies and all. I can try to explain it to you, but it's a bit technical. 

Basically, UI elements and menus are positioned using a PoseStack, which holds a series of relative transformations. This is used as a "reference point" that tells the game where things should be rendered on-screen. There is only one PoseStack that everything shares, meaning that when a UI element is rendered, it manipulates the stack as needed, then passes it along to the next UI element.

 You're _supposed_ to "pop" the stack, which resets the transformations you just performed so they aren't carried over to the next thing being rendered. I assumed this was already being done, but it might not be. The result is that when the XP level graphic is shifted down, everything rendered after that point is shifted down as well, which could cause what you're seeing here.

**Comment by GoldeRuby** [comment]
that makes sense, i think i have a drive link from when i sent it over to a friend
(somehow the pack export exceeded Discord's limit so i resorted to Drive)

here it is: [link](https://drive.google.com/file/d/1r4rkP8bJ8CjuWTHXlu0fZ4DMXTreDtmv/view?usp=sharing)
it _should_ be set so it just needs the link to share

**Comment by MikulDev** [comment]
Thanks for sending the pack. I was able to test my solution and it worked, so expect this to be solved in 2.3.9
