### ISSUE TITLE
Failed to load world due to config sync packet size

### ISSUE THREAD

**Issue by ExpensiveKoala** [Momo-Studios/Cold-Sweat-Rework-Forge#413]
Getting this error when attempting to join singleplayer world. Only mods installed are Cold Sweat (2.3.9 on 1.21), and an addon mod I'm working on. The addon mod doesn't modify your configs, only accessing them (for min temp, max temp, etc..).

[disconnect-2024-11-29_22.19.25-client.txt](https://github.com/user-attachments/files/17964070/disconnect-2024-11-29_22.19.25-client.txt)

**Comment by ExpensiveKoala** [comment]
I may have figured out the culprit. Inside the item.toml config, "Insulation Ingredients" array contains 255 entries of this:

```toml
["minecraft:white_wool,minecraft:orange_wool,minecraft:magenta_wool,minecraft:light_blue_wool,minecraft:yellow_wool,minecraft:lime_wool,minecraft:pink_wool,minecraft:gray_wool,minecraft:light_gray_wool,minecraft:cyan_wool,minecraft:purple_wool,minecraft:blue_wool,minecraft:brown_wool,minecraft:green_wool,minecraft:red_wool,minecraft:black_wool", 1.5, 0.0, "static", "{}"]
```

I am unsure how this happened, but I'm assuming this is the cause for the NBT serialization of the configs being synced being too big.

**Comment by ExpensiveKoala** [comment]
Having it generate a brand new config and joining the world shows 16 entries of the wool colors. 
Having it generate a brand new config and immediately exiting the game shows `["#minecraft:wool", 1.5, 0]` as an entry without the wool array.

I am assuming you're breaking down the item tag into a list of items and then overwriting the config with the broken down list during config sync. Somehow this list is causing it to save as a new entry multiple times causing the config file to balloon in size.
This eventually leads to the config file becoming too large to send in a packet to sync with the integrated server's config.

**Comment by ExpensiveKoala** [comment]
Is there a reason why you're not using NeoForge's built-in config sync? Common configs don't sync, but Server configs sync from server to client. Client configs are purely client configs as well.

**Comment by MikulDev** [comment]
This issue will be solved in the next version. Thank you for your report
