### ISSUE TITLE
Insulation system is bugged in 1.20.1-2.3.9

### ISSUE THREAD

**Issue by Purple-Towel** [Momo-Studios/Cold-Sweat-Rework-Forge#414]
I noticed a few bugs with the insulation system in this new update, chest pieces cannot be insulated at all, and if you place an initially valid insulation recipe (ie any helmet with goat fur) and replace either the insulation item or target item, the output will still be the original valid recipe but consume the new ingredients. Example picture:
![image](https://github.com/user-attachments/assets/cb5642f4-a26b-4e2c-bf88-8a2e79e47f40)

**Comment by Crabford** [comment]
Getting same issue in 1.19.2-2.3.9

**Comment by MikulDev** [comment]
This is a known issue with 2.3.9. I would suggest either reverting to 2.3.8 or trying the experimental 2.3.10 version on the Discord server
