### ISSUE TITLE
World doesn't load with cold sweat

### ISSUE THREAD

**Issue by Aerhtjiz** [Momo-Studios/Cold-Sweat-Rework-Forge#415]
https://www.dropbox.com/scl/fi/46d18fp97ov1rikjgf186/crash-2024-11-30_12.14.35-server.txt?rlkey=lg6xjwfb1kjffus08hyjep9fa&st=6q7b1z5c&dl=0

**Comment by ionutsoran** [comment]
I have the same issue with cold_sweat2.3.9 for 1.20.1 minecraft and forge 47.3.0 only with my server

**Comment by rsteelman** [comment]
Thanks for letting me know. This is indeed a bug. I will have this fixed in the next version

**Comment by MikulDev** [comment]
Thanks for letting me know. This is indeed a bug. I will have this fixed in the next version
