### ISSUE TITLE
Respawning crashes the world 

### ISSUE THREAD

**Issue by ILoveCompatibility** [Momo-Studios/Cold-Sweat-Rework-Forge#416]
World crashes after death, Bcs there’s an error whilst ticking player. So could you please optimize respawning? I’ve lost a lot of progress in multiple worlds, due to my items getting deleted. Please fix? (I don’t know how to add tags, but this is a bug)

**Comment by MikulDev** [comment]
Can I see the crash report? This isn't enough information
