### ISSUE TITLE
This get spam on my server

### ISSUE THREAD

**Issue by Degureshadow** [Momo-Studios/Cold-Sweat-Rework-Forge#417]
[22:54:32] [Netty Epoll Server IO #0/ERROR] [ne.mi.ne.si.IndexedMessageCodec/SIMPLENET]: Received invalid discriminator byte 15 on channel cold_sweat:main
Just spam and we thinks this is making lag (idk) dont make crash and nothing, but is weird
![image](https://github.com/user-attachments/assets/803fa790-d648-4773-8a73-03d944933099)

**Comment by MikulDev** [comment]
This is a known issue with 2.3.9. I would suggest either reverting to 2.3.8 or trying the experimental 2.3.10 version on the Discord server
