### ISSUE TITLE
Magma Blocks No Longer Increase Temperature (Null Error in Log)

### ISSUE THREAD

**Issue by Scarlet-Fury** [Momo-Studios/Cold-Sweat-Rework-Forge#418]
Alrighty, so I recently encountered an issue in the new Beta 2.3.9 version of Cold Sweat

The Magma Blocks seem to be unable to increase the player's temperature AT ALL. Adding them as an item that increases temperature when in a player's inventory in the item.toml config also doesn't work.

Looking over the log to my modpack, it seems to provide a better understanding as to why, as it's throwing this error:

![image_2024-12-04_044527158](https://github.com/user-attachments/assets/580bd32e-9ff6-4d3e-9153-30f4fc525c6a)

This issue persists even when ONLY Cold Sweat 2.3.9 Beta is installed without ANYTHING else in Forge 47.3.12, so I know it's this mod and not my pack, and it's actually kinda nice that my pack seemed to catch the reason why, normally that's not the case XD

**Comment by MikulDev** [comment]
This is a known issue with 2.3.9. I would suggest either reverting to 2.3.8 or trying the experimental 2.3.10 version on the Discord server

**Comment by Scarlet-Fury** [comment]
Okie dokie
