### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by kontrola111** [Momo-Studios/Cold-Sweat-Rework-Forge#419]
Hi, I created a mod pack with the cold sweat mod, when I started the server everything worked at first; Today at some point when I was standing next to the icebox with this "chimney" the server crashed. Below I attach the server logs : ). I checked all the time installing the mods if minecraft starts and generates a world. Everything was fine. And on the multi player I also discovered that I couldn't open the cold sweat menu. Thank you for reading! I really like your mod, very immersive : )

[crash-2024-12-04_13.28.35-server.txt](https://github.com/user-attachments/files/18010666/crash-2024-12-04_13.28.35-server.txt)
[crash-2024-12-04_13.29.36-server.txt](https://github.com/user-attachments/files/18010668/crash-2024-12-04_13.29.36-server.txt)

**Comment by MikulDev** [comment]
This is a known issue with 2.3.9. I would suggest either reverting to 2.3.8 or trying the experimental 2.3.10 version on the Discord server

**Comment by kontrola111** [comment]
Thanks for reply!
What modloader and version minecraft for 2.3.10 form discord?

**Comment by MikulDev** [comment]
It's for Forge 1.20.1, if that's what you're asking

**Comment by Astral-Haze** [comment]
I'm not sure if this is the same bug or another, but I had a crash "Could not deserialize Insulator" when opening chests containing armor; downdating fixed that as well

**Comment by MikulDev** [comment]
Do you get the same issue in [2.3.10](https://www.curseforge.com/minecraft/mc-mods/cold-sweat/files/5974382)? You're describing a different issue that was also fixed in this version
