### ISSUE TITLE
Special Minecarts Dupe Contents

### ISSUE THREAD

**Issue by wendall911** [Momo-Studios/Cold-Sweat-Rework-Forge#42]
https://github.com/Momo-Studios/Cold-Sweat/blob/90bff4cd12fb20415b9526ea0eda45df513a8df6/src/main/java/dev/momostudios/coldsweat/mixin/MixinMinecart.java#L23

If you drop a tnt_minecart, chest_minecart, hopper_minecart, etc. This code dupes the item that the cart contains. This also happens for any mods that extend vanilla minecarts. 

Let me know if you want a PR to fix this.

**Comment by wendall911** [comment]
This will fix the issue.
[MixinMinecart.java.diff.txt](https://github.com/Momo-Studios/Cold-Sweat/files/8498038/MixinMinecart.java.diff.txt)

**Comment by MikulDev** [comment]
Alright, I'll deal with this (thank you for the diff, by the way). Minecarts in vanilla do not drop their DisplayState if it isn't one of the hard-coded minecart types (hopper, command block, tnt, etc), so I was trying to fix that quirk as well.
