### ISSUE TITLE
Compatibility Issues

### ISSUE THREAD

**Issue by hipposarecool** [Momo-Studios/Cold-Sweat-Rework-Forge#420]
from my testing, using Cold Sweat and Primal Winter together works perfectly fine, but pairing that combination with a mod like Tectonic or WWOO makes the game refuse to load a world. I tested Primal Winter and Tectonic and it works, and I tested Cold Sweat and Tectonic and it works, but for some reason combining them makes worlds refuse to generate.

**Comment by MikulDev** [comment]
Can you send your latest.log? That will make diagnosing easier.

**Comment by hipposarecool** [comment]
here
[latest.log](https://github.com/user-attachments/files/18089090/latest.log)

**Comment by MikulDev** [comment]
Does this happen with 2.3.8? I believe this is a known issue

**Comment by hipposarecool** [comment]
It does indeed work in 2.3.8!! ty

**Comment by MikulDev** [comment]
Awesome, you're welcome. I believe this is also fixed in 2.3.10, but that isn't for 1.21 yet.
