### ISSUE TITLE
How should I write the config in "item_settings"?

### ISSUE THREAD

**Issue by sevsn** [Momo-Studios/Cold-Sweat-Rework-Forge#421]
How should I write the config in "item_settings"? I tried to write it like this ["minecraft:lava_bucket", 15, "hand", "core", "{}", 15], but it disappears after starting the game

**Comment by MikulDev** [comment]
This config works for me. Verify that the whole setting looks like this:
```"Carried Item Temperatures" = [["minecraft:lava_bucket", 15, "hand", "core", "{}", 15]]```

Keep in mind that for core temperature, this is applied every tick, meaning your temperature will almost instantly hit 100.

**Comment by sevsn** [comment]
It's working, thank you
