### ISSUE TITLE
I don't even know what's going on.

### ISSUE THREAD

**Issue by 7yudinglaopin8** [Momo-Studios/Cold-Sweat-Rework-Forge#422]
[crash-2024-12-14_12.34.21-client.txt](https://github.com/user-attachments/files/18134209/crash-2024-12-14_12.34.21-client.txt)
I don't even know what's going on. Suddenly there was a crash.

**Comment by 7yudinglaopin8** [comment]
Crashes when opening inventory.

**Comment by 7yudinglaopin8** [comment]
The game will crash when opening the inventory.

**Comment by 7yudinglaopin8** [comment]
2.3.10

**Comment by MikulDev** [comment]
Does this reliably happen when you open the inventory? I can't reproduce this issue myself, so it might be a mod conflict.

**Comment by Accidey** [comment]
I have the same issue, and it is 100% reproducible, but this problem only occurs in Creative Mode.
[crash-2024-12-17_15.14.25-client.txt](https://github.com/user-attachments/files/18161905/crash-2024-12-17_15.14.25-client.txt)

**Comment by MikulDev** [comment]
Should be fixed in the next update that's coming out soon. I was able to reproduce the issue if there are insulator configs with invalid/missing IDs. There are now more checks for that.
