### ISSUE TITLE
Negative values on armor do not change the player's temperature

### ISSUE THREAD

**Issue by The-Goat-HUN** [Momo-Studios/Cold-Sweat-Rework-Forge#426]
The armor in the video has negative values for heat. In a hot environment, my temperature does not go up further.
https://github.com/user-attachments/assets/650cd7d9-2f99-4cb1-9b73-500c12f0422a

Minecraft 1.21.1
Neoforge 21.1.90
Cold Sweat 2.3.8

**Comment by MikulDev** [comment]
That's not how it works. Insulation doesn't increase/decrease the environment temperature. It changes the rate at which you overheat/freeze. That means negative heat insulation makes you heat up faster if you're in a hot environment (100 °F or more)

**Comment by The-Goat-HUN** [comment]
Ahh, I see, thank you. Is there some kind of formula for this?

**Comment by MikulDev** [comment]
```
insulation = player's insulation
temp = current world temperature in MC units
1 MC unit = 25 Celsius or 45 Fahrenheit (also add 32 for Fahrenheit)

if insulation >= 0, formula = temp * 0.1^(insulation / 40)

otherwise, formula = temp * (-insulation / 20 + 1);
```
