### ISSUE TITLE
client crash with sereneseasons

### ISSUE THREAD

**Issue by unknown-gd** [Momo-Studios/Cold-Sweat-Rework-Forge#428]
Crash report: https://mclo.gs/7fI8FlE#L8

**Comment by dandalous** [comment]
I wasn't having this crash in the previous version, but set `mixin.perf.remove_biome_temperature_cache` to `false` in the ModernFix settings as a workaround

**Comment by unknown-gd** [comment]
> I wasn't having this crash in the previous version, but set `mixin.perf.remove_biome_temperature_cache` to `false` in the ModernFix settings as a workaround

Yes, I already did that, same error, just modern-fix is gone from the stack.

**Comment by dandalous** [comment]
Strange, that worked for me. I'm also running SereneSeasons with ModernFix

**Comment by unknown-gd** [comment]
the error occurs spontaneously, usually when moving between dimensions

**Comment by MikulDev** [comment]
In the future, please don't paste the entire crash report into the text box. It's much easier to read if you attach the file.

Anyway, what version of Cold Sweat are you using? The error that's happening here looks like you might be using an outdated version.

**Comment by dandalous** [comment]
You can also use https://mclo.gs/ (Prism launcher lets you upload directly from the launcher) to get a link to your log, that automatically obfuscates things like usernames

**Comment by unknown-gd** [comment]
> In the future, please don't paste the entire crash report into the text box. It's much easier to read if you attach the file.
> 
> Anyway, what version of Cold Sweat are you using? The error that's happening here looks like you might be using an outdated version.

Yeah, I already thought it was a bad idea to put the whole crash stack in the description, I'll try not to do that again.

Cold Sweat 2.3.9 - Minecraft 1.20.1

**Comment by MikulDev** [comment]
Just as I thought. This is a known issue with 2.3.9, and was fixed in 2.3.10

**Comment by dandalous** [comment]
Ah that's listed as Beta on Curseforge and 2.3.9 is the latest on Modrinth

**Comment by MikulDev** [comment]
I see. It will be posted to Modrinth soon, before the new year. 2.3.9 has quite a few issues. I will mark it as unstable on Modrinth to prevent this confusion in the future.

**Comment by dandalous** [comment]
No worries. 2.3.10d resolves my other issue as well so I'll go ahead and close it. Cheers and Happy New Years to y'all!

**Comment by MikulDev** [comment]
Thanks! You too.
