### ISSUE TITLE
On ColdSweat-r2.1.10-b01.jar Text in [Options] -> [Cold Sweat] duplicates with each window resize

### ISSUE THREAD

**Issue by ImNotThatBrave** [Momo-Studios/Cold-Sweat-Rework-Forge#46]
On ColdSweat-r2.1.10-b01.jar for 1.16.5 the Text in [Options] -> [Cold Sweat] creates duplicates on each window resize

This resets if you swap pages so it's rather minor.
The bug is present whether accessing the menu in game or from main menu (only tested this for completeness sake).

 specific fields that do this are as follows
menu pg. 1:
 - temp offset, max temperature, min temperature, rate modifier
menu pg. 2:
 - Grace Length, *Temp. Icon Offset, *Temp. Number Offset, *World Temp. Offset

Images:
![image](https://user-images.githubusercontent.com/40413120/164577589-548c5523-c14a-4e04-a56d-46e043551adb.png)
![image](https://user-images.githubusercontent.com/40413120/164577628-4d0668f8-ed0d-46c3-9530-24295d4da1f7.png)

I love your mod by the way!
It's hands down the most professional implementation I've seen of temperature both mechanics-wise and graphically.
I look forward to messing with the configs to see what's possible and I can't wait to see what add-ons people come up with!

**Comment by MikulDev** [comment]
Thank you for the kind words. I've been tussling with this issue from time to time, but as you said, it's rather minor so it hasn't been high on my to-do list. Maybe it's time to change that!
