### ISSUE TITLE
HUD Texture Mapping Issue in 1.18.2

### ISSUE THREAD

**Issue by rtxyd** [Momo-Studios/Cold-Sweat-Rework-Forge#47]
Just like the title says, loading scaling health and coldsweat togerther, there is a health icons rendering issue.

**Comment by MikulDev** [comment]
You might be able to fix this by disabling "Custom Hotbar" in Cold Sweat's config menu. Let me know if it works

**Comment by rtxyd** [comment]
![QQ图片20220424111135](https://user-images.githubusercontent.com/65117312/164954672-da170ab8-2032-4811-9687-0f10ba4813a8.png)

@iMikul not work, no. I've restart the game by the time

**Comment by MikulDev** [comment]
I think I might've found the source of this issue. A possible fix should be making its way into the next beta.
