### ISSUE TITLE
Server Crash(Mod Loading has failed)

### ISSUE THREAD

**Issue by OcrSu** [Momo-Studios/Cold-Sweat-Rework-Forge#48]
[crash-2022-04-24_12.17.32-fml.txt](https://github.com/Momo-Studios/Cold-Sweat/files/8549027/crash-2022-04-24_12.17.32-fml.txt)
Java11

**Comment by MikulDev** [comment]
2.1.10-b02 has been released since this issue was created. Please try with the latest version and see if this problem has already been resolved.

**Comment by MikulDev** [comment]
possible duplicate: #51

**Comment by OcrSu** [comment]
this problem has already been resolved
