### ISSUE TITLE
FPS has dropped [1.18.2] [v2.1.9~]

### ISSUE THREAD

**Issue by Ayahane** [Momo-Studios/Cold-Sweat-Rework-Forge#50]
![1](https://user-images.githubusercontent.com/30454536/164967334-7dc5e67f-0e59-41a3-832b-e433ffb4a105.png)
![2](https://user-images.githubusercontent.com/30454536/164967339-5e8f6e07-d16b-4399-81ca-33ebcd7c4099.png)
![3](https://user-images.githubusercontent.com/30454536/164967340-abc9444f-60a4-42b6-8f45-48f7ddcf01e1.png)
![4](https://user-images.githubusercontent.com/30454536/164967342-5e4978b4-57a8-47bc-8248-734d11f7f09f.png)

I don't know if it's just my computer problem.
This probably doesn't affect usage too much. 
But the more mods are used...The more the FPS drops..

Thank you for your work.

**Comment by MikulDev** [comment]
I'm looking into potential causes for this issue. Unfortunately, low framerate isn't a lot of information to work with.

**Comment by Ayahane** [comment]
> I'm looking into potential causes for this issue. Unfortunately, low framerate isn't a lot of information to work with.

Oh ok, It's not a particularly important issue. Hope to find out why. <3

**Comment by kuroneko1996** [comment]
Can confirm. Getting massive fps drops when using _2.1.9.2_. FPS seems to raise by two times when I hide HUD(F1) or switch to creative mode(which hides the mod's icons and stuff)

**Comment by MikulDev** [comment]
The latest beta version should not have this issue anymore, since the system for rendering GUI elements has been completely reworked.
