### ISSUE TITLE
 ColdSweat-r2.1.10-b01 crash server

### ISSUE THREAD

**Issue by LLjo** [Momo-Studios/Cold-Sweat-Rework-Forge#51]
Using latest beta version for 1.16.5 of the mod causes server crash on startup. 
ColdSweat-r2.1.10-b01
forge-1.16.5-36.2.34
+ more mods.

[latest.log](https://github.com/Momo-Studios/Cold-Sweat/files/8584100/latest.log)
[crash-2022-04-28_17.12.46-fml.txt](https://github.com/Momo-Studios/Cold-Sweat/files/8584116/crash-2022-04-28_17.12.46-fml.txt)

**Comment by iMikul** [comment]
2.1.10-b02 has been released since this issue was created. Please try with the latest version and see if this problem has already been resolved.
