### ISSUE TITLE
[Suggestion] Compatibility between some mods and other enhancements/mechanics

### ISSUE THREAD

**Issue by Catomax262** [Momo-Studios/Cold-Sweat-Rework-Forge#52]
Remember that if i mentioned something already present on the mod, please remind me of it as soon as possible!

### _**Mechanics**_
- ~Add dynamic insulation values, so all armors have a unique insulation value.~
- Add Heatstims and Ice Bags, these might be a better or worse (depending on the situation) version of the waterskins, but they could only protect from low/high temperatures at a very low value unlike their water counterparts, that can protect up to really specific values. They would work by keeping the player temperature level at bay by some few degrees up and down, but they could work well as a way to control your temperature a bit without getting wet and to keep it stable during the trip. However, these would have very low durability, so it would be better to carry as much as you need, or to opt out and keep using the waterskin.
- ~Speaking of wetness, being wet can also contribute in good/bad ways. While being wet in the cold, cold temperature would take longer to return to normal, so if you're freezing and you are wet at the same time, taking too long to dry off would cause you to be slowed down, and die from hypotermia quicker than before. As an addition to the challenge, staying wet in the cold for too long would often cause you to catch flu, so you'll get weaker and eventually end up very vulnerable to the world. Being wet in the heat would help more rather than harm, while drying off would be quicker, staying wet in there would help you resist more the heat and help with burning. However, after drying out in the heat, you'll return with higher temperature as a result. So, towels can be a really quick method to dry out.~
- ~Dynamic heat sources could be great, like campfires, torches and lanterns. Staying in soft blocks like wool, carpets and beds could help with the coldness a bit. Sleeping on beds could warm you up for the night. There are many possibilities to warm you up at cold times! Staying on tight spaces with few air entrances can also add a little to the heat multiplier.~

### **_Compatibility (revolves around armor insulation values)_**
- ~Sewing Kit: add insulation values to the Wool Armor, no defense at all but good heat provider. Also add the option so you can sew insulators into armor using the Sewing Table from this mod. Also add a combination between leather and wool that can insulate armor even further.~
- ~Environmental: Add insulation values to the Yak Pants, exceptional for keeping your thighs warm and cozy.~
- Artifacts: The Bunny and Kitty slippers protect your feet from the cold, and the Lucky and Invisibility scarf protect from cold on your chest. (Plz Add Curios insulation values too)~
- ~Tough as nails: In a pinch, you could drink water straight from waterskins, but they would fill low thirst values and may burn or freeze the player. Too much heat will cause the thirst meter to go down faster.~
- ~Serene Seasons: The time of the year can severely impact temperature.~
- ~Farmer's Delight: Drinking soup type meals can warm you up a bit.~
- ~Comforts: Bedrolls can work the same as beds, warming you up for the night. Hammocks, on the other side, can be used to take a nap without caring about heating up.~

**Comment by Catomax262** [comment]
Also, a new mechanic i forgot to add: When you're too hot, you start having blackouts (short blindness effect)

**Comment by MikulDev** [comment]
**Mechanics:**
1. Already possible to some extent via configs. Insulation improvements are coming in the future to differentiate between hot/cold.
2. Waterskins can be kept in the hotbar to regulate your body temperature. 
3. Water already does a similar thing to this by lowering the "perceived" world temperature. In hot climates, this is good, but in cold climates, this is bad. We won't be adding any kind of sickness mechanic because I don't really think it fits with the scope of Cold Sweat or Minecraft in general.
4. Many blocks already produce heat, which is configurable. Sleeping in a bed also helps equalize your temperature if you sleep through the night.

**Compatibility:**
1. Custom insulators or insulating armor can be defined in the configs. Future versions of Cold Sweat will have an expanded insulation system, so combining insulators might be possible then.
2. Answered in 1.
3. Curios/Baubles support is something we plan on adding, but it isn't high on our to-do list. It will happen eventually, though.
4. How would you drink from a waterskin? They already have a right-click action.
5. Already a feature.
6. Possible via configs.
7. If they truly act like a bed, then they should have the same mechanic of sleeping through the night equalizing your temperature.

Extra comment: Additional effects for extreme temperatures are already planned. This is actually one of the features we were discussing.

**Comment by Catomax262** [comment]
Yeah, i knew many of these were already in the game, but having to refill a waterskin when they all run out of water is kinda tedious so why not a cheap substitute that instead just slows down the temperature change? For example a Heatstim could make the counter count down slower, and an Ice bag could do the same, however, heatstims wear out and ice bags melt into the world.

**Comment by Catomax262** [comment]
Also, how can i make the counter go down from 100? Am i done in when it reaches 100?

**Comment by MikulDev** [comment]
> Yeah, i knew many of these were already in the game, but having to refill a waterskin when they all run out of water is kinda tedious so why not a cheap substitute that instead just slows down the temperature change? For example a Heatstim could make the counter count down slower, and an Ice bag could do the same, however, heatstims wear out and ice bags melt into the world.

I'm saying that waterskins already do this. If you have them in your hotbar, they will slowly change your temperature and not 
consume the water. And what substitute would be cheaper than leather and string?

> Also, how can i make the counter go down from 100? Am i done in when it reaches 100?

You still have a chance to help yourself. If you quickly get somewhere that's not deadly, your temperature will start normalizing after a brief delay (the delay gets longer the more time you spend in a dangerous area while your temperature is 100)

**Comment by Catomax262** [comment]
I didn't knew Waterskins had an effect in the hotbar. Guess all these suggestions are things that are already in the game.

**Comment by XLB120** [comment]
Hello，Dear author，Please forgive me，In fact, my English is not well, just some simple communication.May I induige in a IittIe advice?
This is a good mod，I hope it can add the temperature change in the time interval to "config"。
For instance,When entering the game time: 0-24000 a day,temperature，Use default settings;time:24000-48000，
Temperature rise 0.2;time:48000-72000,Temperature drop 0.2。Keep repeating，It's the same all year round。
I wonder if you can understand，Sorry, my English is not very good. 
I hope you can take my advice。

**Comment by XLB120** [comment]
My favorite game version is 1.16.5. I hope you can see your update in 1.16.5.

**Comment by MikulDev** [comment]
@XLB9363 
Please do not hijack other people's issues, especially ones that are **already closed.** This is an unrelated topic. I've created a new issue for you to use instead of this one.

**Comment by BigMartin58** [comment]
> 3. Curios/Baubles support is something we plan on adding, but it isn't high on our to-do list. It will happen eventually, though.

Sorry to gravedig, but has this been implemented yet?

**Comment by MikulDev** [comment]
Yes, this was implemented about a year ago. I'd suggest looking through the config files & changelog
