### ISSUE TITLE
[1.18.2] Hearth Dupe

### ISSUE THREAD

**Issue by BookerCatch** [Momo-Studios/Cold-Sweat-Rework-Forge#57]
Placing Ice Blocks in the Hearth will cause the stack to increase indefinitely every few ticks. Removing the stack from the Hearth results in more items than what was initially placed.

**Comment by MikulDev** [comment]
This issue has already been solved internally, but thank you for documenting this issue. I'll leave this open until I release an update that officially fixes this.
