### ISSUE TITLE
Set the temperature for the block

### ISSUE THREAD

**Issue by XLB9363** [Momo-Studios/Cold-Sweat-Rework-Forge#58]
#(the effect of the example below (torch) is so low that it does barely anything. It's purely for demonstration)
	BlockEffects = [["minecraft:snow,minecraft:snow_block", -0.1, 3, true, -0.1]]

Dear author，Is this format right。

**Comment by MikulDev** [comment]
It should be correct. If it's having problems, please post the entire `latest.log` from when you tried this configuration.
