### ISSUE TITLE
1.18.2 Crash 

### ISSUE THREAD

**Issue by Tyrius1** [Momo-Studios/Cold-Sweat-Rework-Forge#59]
Got a one off crash after creating a new world. World got to 99% loaded then crashed,
https://pastebin.com/2QHQckkZ over 100 new worlds during testing my project and this is the first i've seen of this.

ColdSweat-2.1.10-b03
forge - 40.1.19

**Comment by MikulDev** [comment]
Thank you for this; I'll work on a fix soon.
