### ISSUE TITLE
[bug] temp value incorrect

### ISSUE THREAD

**Issue by AlienXtream** [Momo-Studios/Cold-Sweat-Rework-Forge#6]
applies to F and C temps. 400+ mods so compatibility is a possible issue though it appears to be only affecting the number itself, not the value.

![image](https://user-images.githubusercontent.com/12606809/137831054-694bde19-e4f1-4908-aa77-a3bcc79765be.png)

**Comment by AlienXtream** [comment]
on an unrelated note. can confirm that #4 is resolved :)

**Comment by MikulGamour** [comment]
I have never seen something like this reported before. What are your config options? A list of mods would be helpful as well, just in case. (If it's too much effort, I can try to look at the problem on my end but I do suspect a misconfigured config or mod incompatibility)
