### ISSUE TITLE
(1.18) Suggestion

### ISSUE THREAD

**Issue by BumbleCrashes** [Momo-Studios/Cold-Sweat-Rework-Forge#63]
This mod changes the behavior of soul fire to deal frost damage instead of regular fire damage. this is a nice feature but it makes soul fire not burn items which messes with mods that require to burn items in soul fire like spirit which requires you to burn amethyst in soul fire to make soul crystals. since amethyst no longer burns in it, the crystal isn't created. so i would suggest to make a config to disable it. or just make that items do burn in soul fire.

**Comment by MikulDev** [comment]
That's a good point. I'll make that a config option.
