### ISSUE TITLE
Multiplayer Temperature Syncing

### ISSUE THREAD

**Issue by EleazarHouston** [Momo-Studios/Cold-Sweat-Rework-Forge#64]
In version ColdSweat-2.1.10-b04 (and b03) 1.16.5, players will affect the temperature of other players. My friend went caving and walked near lava, causing me to die of heatstroke, despite my being on the surface in a snowing Taiga. 

Seems inconsistent with 3+ players, with certain players linking but not others.

**Comment by MikulDev** [comment]
Thank you for reporting this. I've gotten a few like this already, so I'm pinning this issue until it is resolved.

**Comment by MikulDev** [comment]
I have released two prototype fixes for this issue on the Discord server. If you would like to test them out, please report back if it's been fixed. I unfortunately don't have the resources to test with enough accounts to trigger the issue reliably.

**Comment by MikulDev** [comment]
Update: Beta 5 attempts to fix this issue in 1.18.

**Comment by MikulDev** [comment]
Marking this issue as closed since nobody has reported syncing issues for the last few betas.
