### ISSUE TITLE
minor QoL fix; chat being covered bu temprature UI element

### ISSUE THREAD

**Issue by Shibva** [Momo-Studios/Cold-Sweat-Rework-Forge#67]
as the name implies the chat gets put behind the temperature UI element
![image](https://user-images.githubusercontent.com/38770780/173480820-0632598a-2f04-40e4-b205-4c9477de6502.png)

![image](https://user-images.githubusercontent.com/38770780/173480897-7b2762ce-f226-4e91-be33-70a8f16ffacd.png)

please fix this when you have the time; just a minor QoL bug

**Comment by MikulDev** [comment]
I've confirmed a fix for this in 1.18. I'll port it to 1.16.5 as well if I can.
