### ISSUE TITLE
Wrong colors of slots in every GUI

### ISSUE THREAD

**Issue by realredman** [Momo-Studios/Cold-Sweat-Rework-Forge#68]
All of the GUIs from the mod have the wrong colors (assuming vanilla colors are correct)

here's some proof:

![wrongguicolorscoldsweat](https://user-images.githubusercontent.com/106761360/174917272-7e763e3d-6cbb-4929-bdf5-c16fc2b6a99c.png)
applies to every GUI from the mod

Using version 2.1.9.2 for Minecraft 1.18.2

**Comment by MikulDev** [comment]
An interesting development. I'm fixing this now.

**Comment by MikulDev** [comment]
Fixed in 2.1.10-b05b for 1.16.5 and 1.18
