### ISSUE TITLE
1.16.5 crash upon config attempt

### ISSUE THREAD

**Issue by DMJessus** [Momo-Studios/Cold-Sweat-Rework-Forge#69]
unable to configure any settings from the main screen "mods" button. any attempt to click an "edit" button immediately crashes the game. 

The game crashed whilst mouseclicked event handler
Error: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
Exit Code: -1

**Comment by MikulDev** [comment]
I can't seem to replicate this issue. If the crash doesn't impact the usage of other mods, I'd suggest using the config files or Cold Sweat's in-game config menu instead.
