### ISSUE TITLE
waterskins duplicate and rename themselves like in an anvil 1.18.1 last beta

### ISSUE THREAD

**Issue by FruitySkyLine** [Momo-Studios/Cold-Sweat-Rework-Forge#71]
When I use a waterskin on me, the waterskin does not empty and it gives me another waterskin renamed like in an anvil.

**Comment by MikulDev** [comment]
I believe this has already been resolved internally. You can try the latest experimental build by joining our Discord and looking in the #updates-and-info section.

**Comment by MikulDev** [comment]
This has been fixed as of 2.1.10-b05.
