### ISSUE TITLE
Compatability with "active: true" blocks

### ISSUE THREAD

**Issue by AveryCorvus** [Momo-Studios/Cold-Sweat-Rework-Forge#72]
I'm wondering if there's a way (or if there's a way it can be added) that I can enable blocks to only add to the ambient temperature if they have a particular value set?

E.g. Tinker's Construct, having been updated to the latest versions, I'm interested in making the melter/smeltery/foundry heat up a room when "active" = true. For now I'm just setting them to be hot all the time, but it would be cool if it was an on/off thing.

**Comment by MikulDev** [comment]
_Maybe_ in the future. The problem with this is that every block has their "active" attribute defined in a different way. For example, a furnace's version of "lit" isn't the same as a campfire's version of "lit," despite them having the same name and meaning the same thing. It would be extremely slow (in a computational sense) to dig through all of the block's properties to find out if it's "active" or not. It would utterly destroy the mod.

Luckily, this is pretty simple to do with mods. If you can program in Java, then I'd suggest doing that instead.
