### ISSUE TITLE
Feature Request: Ice Resistance Potion and Insulated armour should protect you from powder snow / vanilla freezing mechanics

### ISSUE THREAD

**Issue by SodiumShine** [Momo-Studios/Cold-Sweat-Rework-Forge#74]
Currently drinking an ice resistance potion, or otherwise having the ice resistance effect, doesn't protect you from the effects of powder snow. Obviously leather armour protects you just fine, but it does feel very weird that a magic potion called Ice Resistance Potion wouldn't.

**Comment by SodiumShine** [comment]
ACTUALLY on that note, I just realised insulated armour doesn't protect you either, which makes even less sense in terms of vanilla mechanics.  Putting leather padding inside your diamond armour should protect you from it as if you had leather on.

**Comment by MikulDev** [comment]
Good idea. Consider it done!

**Comment by ExpensiveKoala** [comment]
Adding onto this shouldn't extremely low ambient temperatures affect you like how powdered snow does? Slow you down and freeze you?

**Comment by MikulDev** [comment]
The next major update of Cold Sweat (which at this point is seeming farther and farther away) will have effects similar to this. You will be severely weakened in harsh winter conditions and feel the effects of a heatstroke in a desert
