### ISSUE TITLE
Crash with JEI (And maybe its addons?)

### ISSUE THREAD

**Issue by 1mtwtfss1** [Momo-Studios/Cold-Sweat-Rework-Forge#75]
1.18.2, Singleplayer, Forge_40.1.68, ColdSweat-2.1.10-b05c

When I was playing and moved the cursor to the hellspring lamp in JEI, the game crashed.

![360截图20220723161233331](https://user-images.githubusercontent.com/88222275/180597096-12cb5f9b-14c6-4e54-8914-59c4cc241eda.png)
![360截图20220723162444257](https://user-images.githubusercontent.com/88222275/180597109-51d0078a-8045-47ba-9733-ee7c5d17d1c5.png)

**Comment by MikulDev** [comment]
I found that bug late yesterday and replaced the file on CurseForge with a patched version. Just re-download it to fix the issue.
