### ISSUE TITLE
Suggestion: Make all living entities affected by temperature

### ISSUE THREAD

**Issue by ExpensiveKoala** [Momo-Studios/Cold-Sweat-Rework-Forge#76]
While I do recognize that this change would require a significant rewrite of the mod, I believe it is worth doing.
In vanilla, all mobs can be affected by powdered snow. Once this mod is updated to include support for powdered snow effects (https://github.com/Momo-Studios/Cold-Sweat/issues/74), It would be weird that players are affected by this differently. 

A zombie that picks up your armor should be able to receive the freezing mitigating effects of the insulation within powdered snow.
A snow golem that finds itself in the desert should feel the affects of the heat much more than the player.
The list can go on.

Another added benefit of implementing this, is that you can make animal husbandry more interactive. Sheep and goats can be farmed  in extremely cold environments etc... Added bonus if you give ai for mobs to walk towards / stay within a "comfortable" temperature area.

For compatibility, you can leave it up to the player/modpack maker to define the temperature settings of each individual mob, or even use the biomes they can spawn in's temperatures to guess.

**Comment by MikulDev** [comment]
This was a feature of very old versions of Cold Sweat, but I've had to shift it to the backburner while I try to get the core of the mod in order. I absolutely plan for this to be a part of Cold Sweat in the future, with as much or more functionality than you described, but for now it still has to wait. I'll keep this open until I get around to it.

**Comment by MikulDev** [comment]
Newer versions of Cold Sweat now have ways to implement this via 3rd party mods. You can do this by subscribing to `EnableTemperatureEvent`, which is called to determine which entities should do temperature calculations. This also gives them a basic temperature `Capability`, which your mod can access using the methods provided in the `Temperature` helper class, and handle more advanced stuff. I don't think this feature will make its way into the base mod, though.
