### ISSUE TITLE
Hearth Fuel consumption bug. Hearth become useless. b05c Issue.

### ISSUE THREAD

**Issue by MAGGen-hub** [Momo-Studios/Cold-Sweat-Rework-Forge#78]
Minecraft - 1.16.5
Forge - 36.2.39
Mod version - ColdSweat-2.1.10-b05c (last)
Serene Seasons - SereneSeasons-1.16.5-4.0.1.126-universal
Better Weather - not installed
Total mod count in modpack: 135 (ask me if you need names of mods)

For some reason when I add one peace of coal in hearth it completly fill the scale. But if I use stack of coal (64) - it consumes a lot of it (always different values). Sometimes it can consume 27 in other time 53 peaces of coal. I... Well I confused... 

Also hearth optimisation in 2.1.10-b05c damage my house designe: in previous versions of mod I have only one hearth on the basement floor of my house. And it was perfect... It even heats first floor of my windmill (it was in 20 blocks range). 
Now I need to build a hearth on each floor of my house - It still works but only partly: only 1 of 10 hearth work cycles can reach the last (second floor (roof)) of my house... So I moved my hearth to first floor from basement floor, BUT EVEN THIS DONT HELP! So now it's very easy for me to freeze to death in my house now... For some reason hearth become very hard to use. It don't even heat my first floor sometimes( Maybe thats because my roof made with halfblocks and stairs blocks???

Previous version of mod have problem too: It's so cold outside when winter starts so even campfire can't heat me (even if I STAND on campfire block - body temperature still dereasing...) so it become very hard for me to survive.

Please help. I even set hearth strengs value to 1.0, but it dont change anyhing...

Any ideas what can be the reason of this hearth behaviour?

**Comment by MikulDev** [comment]
Try 2.1.10.1 and see if this issue persists. I think it was just an issue with the spreading algorithm that has since been solved.

**Comment by SisterVersio** [comment]
Hearth is still non-functional in 2.1.10.1
