### ISSUE TITLE
SUGGESTION: Mod pack creators configs & hydration?

### ISSUE THREAD

**Issue by TheSexyYeti** [Momo-Studios/Cold-Sweat-Rework-Forge#79]
Can you add a config for mod pack creators to manually add other items from other mods that increase/decrease temperature?. Oh and how about adding a hydration meter?. I was thinking an easy and non-intrusive texture for this would be just to make the outline of the hunger bar blue to indicate hydration level.  Something along those lines.

**Comment by MikulDev** [comment]
I believe there is already a config in Cold Sweat to make consumables (food, drinks) change the player's temperature.

As for the thirst bar, that's going to have to be a firm "no". Neither I nor any of the people that have helped me develop Cold Sweat really like thirst mods, so we wouldn't know how to make one that people enjoy if we don't enjoy it ourselves.
