### ISSUE TITLE
Filled waterskin in inventory gradually slows the game down over time

### ISSUE THREAD

**Issue by UnderscoreKilburn** [Momo-Studios/Cold-Sweat-Rework-Forge#80]
Happens on 2.1.10, I've tested this on 1.18.2 without any other mods installed. Heat up or chill some waterskins, put them in your inventory, the game will eventually slow down to a crawl until it becomes unplayable. Previous versions seem to work fine and don't have this issue.

After doing a tiny bit of debugging, it looks like the temperature modifier applied by waterskins never gets cleared, it just stays there forever and more and more instances of it get added every frame.

**Comment by MikulDev** [comment]
Fixed in 2.1.10.1. Thanks for the info! :)
