### ISSUE TITLE
Mixin error

### ISSUE THREAD

**Issue by UnderclassZero** [Momo-Studios/Cold-Sweat-Rework-Forge#83]
Apparently it crashes, from what another forum says mixins are causing my game to crash.
It also mentions a ticking entity error with a quartz item, so maybe a quartz incompatibility ?

**Comment by MikulDev** [comment]
Please post a crash log. I can't do anything with so little information.

**Comment by UnderclassZero** [comment]
Oh right, sorry, forgot about it. Here it is 
[crash-2022-08-25_20.47.33-server.txt](https://github.com/Momo-Studios/Cold-Sweat/files/9436497/crash-2022-08-25_20.47.33-server.txt)
:

**Comment by MikulDev** [comment]
The crash happened when a minecart was broken (chest minecarts from abandoned mineshafts get broken all the time during world generation). A fix for the issue will be in 2.1.10.2

**Comment by UnderclassZero** [comment]
Alright thanks !
