### ISSUE TITLE
Using TNT to blast the minecart will crash the game

### ISSUE THREAD

**Issue by Accidey** [Momo-Studios/Cold-Sweat-Rework-Forge#84]
[crash-2022-08-27_23.11.50-server.txt](https://github.com/Momo-Studios/Cold-Sweat/files/9438207/crash-2022-08-27_23.11.50-server.txt)
Minecraft 1.16.5 Forge 36.2.39 ColdSweat-2.1.10.1
Here is the crash log，I spent a night looking for the cause of the crash and finally found this problem. In addition to the TNT minecart will cause the game to crash, chest_minecart will also cause the game to crash during world generation, which are all problems that occur when only the Cold Sweat mod is installed.
ColdSweat-2.1.10-b05c does not crash the game.

**Comment by Accidey** [comment]
Let me correct the problem. When you use TNT to ignite with chest_ minecarts next to it, the game will crash directly, and chest_ minecarts will also crash the game directly when the block is loaded.

**Comment by MikulDev** [comment]
This issue has already been solved (#83). It will be fixed in the next release soon.
