### ISSUE TITLE
1.16.5 Crash (no other mods installed)

### ISSUE THREAD

**Issue by OverEarth12** [Momo-Studios/Cold-Sweat-Rework-Forge#86]
[crash-2022-09-09_13.55.38-server.txt](https://github.com/Momo-Studios/Cold-Sweat/files/9533008/crash-2022-09-09_13.55.38-server.txt)
Forge 36.2.34
Mod Version 2.1.10.1
Crash when I'm flying explore in my world (Test with this mod alone)

**Comment by MikulDev** [comment]
This issue has been fixed internally and will be part of the next update. Thanks for your report.
