### ISSUE TITLE
[1.16.5] Hearth does not affect temperature

### ISSUE THREAD

**Issue by SisterVersio** [Momo-Studios/Cold-Sweat-Rework-Forge#87]
In lethally cold or hot temperatures, the hearth block has no impact on temperature when supplied with the correct fuel. Same behaviour with no other mods loaded

Cold Sweat 2.1.10.1
Forge 36.2.39

![2022-09-09_10 26 53](https://user-images.githubusercontent.com/25148746/189397289-baf5b4a9-78c3-4335-a081-3a6edfc28536.png)

**Comment by SisterVersio** [comment]
The hearth does function when downgrading the mod version back to 2.1.10-b05c

**Comment by MikulDev** [comment]
This issue will be fixed in 2.1.10.3 (next update). Thank you for the report.
