### ISSUE TITLE
Sewing Table Duplication Glitch

### ISSUE THREAD

**Issue by BookerCatch** [Momo-Studios/Cold-Sweat-Rework-Forge#9]
To reproduce, insert a leather tunic and any chestplate armor in the chestplate slot. Now replace the chestplate armor just inserted with another chestplate armor. The recipe output does not change accordingly, resulting in a duplication of the initially inserted chestplate armor.

![image](https://user-images.githubusercontent.com/43504436/139609517-baffb0bc-0fc2-400f-9509-73d07cc5051f.png)

**Comment by chubbymomo** [comment]
Thanks for the bug report!

We'll work on getting this fixed up.

**Comment by MikulGamour** [comment]
This bug has been squashed, so I'm closing this issue. Thanks again for the report!
