### ISSUE TITLE
Game crashes, version 2.1.10.3 game version 1.16.5

### ISSUE THREAD

**Issue by Accidey** [Momo-Studios/Cold-Sweat-Rework-Forge#91]
I downloaded the latest version, and then the game crashed when using the TP command.
[crash-2022-09-25_14.39.02-client.txt](https://github.com/Momo-Studios/Cold-Sweat/files/9640175/crash-2022-09-25_14.39.02-client.txt)

**Comment by sixstepsaway** [comment]
Came here to report the same error. Seems like it's having trouble calculating a fast temperature shift and crashes the game.

**Comment by SamayaNL** [comment]
Yes, happens to me as well. Also when dying and respawning
