### ISSUE TITLE
Suggestion: Allow armour to be configured to modify temperature in addition to insulation

### ISSUE THREAD

**Issue by DavGam** [Momo-Studios/Cold-Sweat-Rework-Forge#96]
G'day!  

I realise this is similar to a request you've already received a couple of times - sorry if such is a hassle.

I've been playing around with the configuration of Cold Sweat, and find myself wondering if we could be given the ability to add flat temperature changes to individual pieces of armour - similar to how we can apply temperature changes to consumables, but in the same way that we currently configure insulation for clothing.  

I'm running Cold Sweat alongside Serene Seasons on a server with particularly large biomes.  My hope with this suggestion is that I can encourage my players to prioritise different sets of armour and clothing based upon the current season and where they're living / traveling - ideally resulting in different wardrobes for summer, winter, temperate, tropical, and expected amount of combat (and, therefore, incentivise players to raise / grow / hunt different resources to create those wardrobes).  

While the ability to configure the insulation value of armour is certainly nice, it's limited in how I can balance different armour sets - higher insulation is always better than lower, and so the same armour is being worn in both very hot and very cold climates.  Being able to change the temperature would also mean I could further balance some of the higher tier armour, such as the Ice Dragon armour from Ice and Fire - making it significantly reduce temperature would make it more viable in some environments, but unfeasible in others.

Ta for reading such a long request!

**Comment by MikulDev** [comment]
I won't spoil anything, but I've been tossing an idea like this around for a long time. I definitely agree that there should be more strategy in how you build your armor set.
I think Armor Underwear is working on adding this kind of functionality to its items as well.
