### ISSUE TITLE
Cannot access any world when using valhelsia_structures mod

### ISSUE THREAD

**Issue by Accidey** [Momo-Studios/Cold-Sweat-Rework-Forge#97]
MC 1.16.5 Forge36.2.39 ColdSweat 2.1.11 valhelsia structures 0.1.6
I spent a lot of time finding that only Cold Sweat with valhelsia structures mod was unable to access any of the saves, older versions of Cold Sweat did not have this problem.
My English is not good, I used the translation software to translate, I hope you can understand.

**Comment by MikulDev** [comment]
Please send your latest.log file.

**Comment by Accidey** [comment]
[latest.log](https://github.com/Momo-Studios/Cold-Sweat/files/9895335/latest.log)

**Comment by MikulDev** [comment]
After hours of diagnosing, I finally was able to fix the issue. Basically Valhelsia tries to edit blocks while the world is still loading, which messes up Cold Sweat's code that detects block updates. I added a check to see if the world is loaded and it seems to have fixed the issue for both existing and new worlds. An update with the fix will be out shortly.
