### ISSUE TITLE
1.16.5 World gets stuck at loading screen (either new world, or previously started world) with latest update

### ISSUE THREAD

**Issue by SamayaNL** [Momo-Studios/Cold-Sweat-Rework-Forge#98]
I wanted to mention that after the recent update, any world I create or any save I open, it gets stuck at the loading world screen. It's a heavily modded instance, so I realize it can be any number of reasons why it doesn't work. I experimented with several configurations though, and at least Dynamic Trees causes a conflict with Cold Sweat. But in another instance I had where I disabled Dynamic Trees, but still had a lot of other mods enabled, the issue persists, so it's probably not just Dynamic Trees.

I realize this is very vague, but short of testing every single mod combination, I cannot really find out what mod combination is causing issues. I hope the fact that it at the very least occurs with Dynamic Trees, and it just stops world loading, but doesn't crash the game, might point you to something.

Take care.

**Comment by MikulDev** [comment]
Please provide your latest.log file. That might help narrow down the issue, since Forge often logs when mods clash like this.

**Comment by SamayaNL** [comment]
Sure, here you go
[latest.log](https://github.com/Momo-Studios/Cold-Sweat/files/9893978/latest.log)

**Comment by MikulDev** [comment]
I can't find any reason why this would be happening from the log file, nor could I re-create the issue with just Dynamic Trees and Cold Sweat. Unfortunately, I don't know how to help you at this point. I've gotten a similar report about worlds not loading but they have yet to send me their log file.

**Comment by SamayaNL** [comment]
After experimenting a bit more it seems this issue occurs with other
configurations as well, without cold sweat.

Thanks for trying anyways!

Op za 29 okt. 2022 20:45 schreef MikulDev ***@***.***>:

**Comment by MikulDev** [comment]
Good luck with your search!
