### ISSUE TITLE
world generation stuck at 0%

### ISSUE THREAD

**Issue by Rambling-rose** [Momo-Studios/Cold-Sweat-Rework-Forge#99]
[latest.log](https://github.com/Momo-Studios/Cold-Sweat/files/9895261/latest.log)
[debug.log](https://github.com/Momo-Studios/Cold-Sweat/files/9895267/debug.log)

im running into some issues using the 2.1.11 version doesn't allow the world to generate no crash report world generation is just stuck at 0% (i figured out cold sweat was the issue with a binary search) and the log stops updating after a short amount of time

**Comment by Subthy** [comment]
Same thing for me.

[debug.log](https://github.com/Momo-Studios/Cold-Sweat/files/9896872/debug.log)
[latest.log](https://github.com/Momo-Studios/Cold-Sweat/files/9896873/latest.log)

**Comment by MikulDev** [comment]
It was an issue with Valhelsia Structures trying to change blocks while the world was still loading, which messed with Cold Sweat. Luckily, I found a fix that will be out soon.
